import { Recipe } from './types';

export const RECIPES: Recipe[] = [
  {
    id: '1',
    title: 'Classic Chocolate Chip Cookies',
    description: 'The quintessential cookie recipe featuring crispy edges, a chewy center, and pools of bittersweet chocolate.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAZMGuBcj9GgW2miaR5e4GZxcAxEH8bq1A2sISq-l2alPuUaHh1MBd1Xx0wPKMAXPyl0BJ2K2vbPlCQ1hodOZtS7kT8D3L407c70tlPocf9keQyo8_MjWBPSPflDgCxnBh_iNS6ahHlbEArIvFw7Jb7nDtsozvS9j9tWLCAvrvelnz1j2A0y1ZYA4JfiivfGkPb3LVSlIFN1d_qnZewvPkUR8gJlGzFYqtiQ6-FCwzVQ458_eyvbd2sdyofILeDPjxeRbqTG3m_4A',
    difficulty: 'Easy',
    time: '20 mins',
    prepTime: '15 mins',
    bakeTime: '10 mins',
    yields: '24 cookies',
    category: 'Heirloom Recipe',
    tags: ['cookies', 'dessert', 'chocolate', 'baking', 'oven'],
    isHeirloom: true,
    chefNote: 'For a deeper toffee-like flavor, chill the dough for at least 24 hours before baking. This hydrates the flour and concentrates the sugars, resulting in a superior crust and chew.',
    ingredients: [
      { name: 'Unsalted Butter', amount: '1 cup', image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCXYw7e6ZbAXgTnZzJBLQB_eWXQ4aRKxY29-ZAAS466F_MTTgdICm_tIpijLrZNADK9AqS4Sma3ZTk2E8wc-6pN5MjfxuRCvCtOqfjToFhw-hhXds5LWP_3lnIV9NCisBhN0iKUhjt4dlOyAwTv5ao__yohwCGq0Sm-NKq5ykeO20n5n5DGIb95imqrsH8m3YNwLKqHJMe_TQiSjyJuzkApvG9BPF-_aZ6Yjlx2aLQc5tCvLfV-Ms1OxeV25D76FtDMDm1-P-Xmyg' },
      { name: 'White Sugar', amount: '1 cup' },
      { name: 'Packed Brown Sugar', amount: '1 cup' },
      { name: 'Large Eggs', amount: '2' },
      { name: 'Vanilla Extract', amount: '2 tsp' },
      { name: 'All-purpose Flour', amount: '3 cups' },
      { name: 'Semisweet Choc Chips', amount: '2 cups' },
      { name: 'Baking Soda', amount: '1 tsp' },
    ],
    steps: [
      { title: 'Preheat and Prep', description: 'Preheat your oven to 350°F (175°C). Line a large baking sheet with parchment paper or a silicone baking mat. This ensures even heat distribution and prevents the cookies from sticking.' },
      { title: 'Cream Butter and Sugars', description: 'In a large bowl, cream together the softened butter, white sugar, and brown sugar until the mixture is light, fluffy, and smooth. This process incorporates air and provides the classic texture.', timer: 600 },
      { title: 'Incorporate Wet Ingredients', description: 'Beat in the eggs one at a time, then stir in the vanilla extract. Make sure each egg is fully combined before adding the next to maintain a stable emulsion.' },
      { title: 'Mix Dry and Fold', description: 'Dissolve baking soda in hot water. Add to batter along with salt. Stir in flour, chocolate chips, and nuts. Use a large spatula to fold the dry ingredients gently until no streaks remain.' },
      { title: 'Bake to Perfection', description: 'Drop by large spoonfuls onto prepared pans. Bake for about 10 minutes in the preheated oven, or until edges are nicely browned. Let cool on the baking sheet for 5 minutes before moving to a wire rack.', timer: 600 },
    ]
  },
  {
    id: '2',
    title: 'Artisan Glazed Donuts',
    description: 'Golden brown homemade glazed donuts stacked on a wire cooling rack with light powdered sugar dusting.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCavk_6yxpyqQNjXHY_JHR3XclLjSR8B4l0nCiOo3UT3i-Pg_1fTdIOecK9ZJAECQHRRjnBV-iH1cqsJFznvPvJjODFjTMx-DxHdiJDnoDKizCxbQ_7cne6CzcqXAKBT7Us1D5Fn27GEDfmeFQoXImMx6NozeYRjWUaJEWWnfIsH2Xnr1IRALOWi9x72VjdTNSpIQJ_UxtA9hrWTlY1220J2oJLcUwL_RNFc8olxcb7sJQWJ4hq8Dz68LczRpUuXhZiH9-2Nw2yUw',
    difficulty: 'Advanced',
    time: '2 hrs',
    prepTime: '45 mins',
    bakeTime: '3 mins per side',
    yields: '12 donuts',
    category: 'Bakery Classic',
    tags: ['donuts', 'fried', 'breakfast', 'yeast', 'glaze'],
    chefNote: 'Oil temperature is everything: aim for a steady 350°F (175°C). Too cool and the donuts absorb grease; too hot and the outside burns before the center cooks. Use a deep-fry or candy thermometer and adjust the burner in small increments so each batch fries evenly.',
    ingredients: [
      { name: 'Active Dry Yeast', amount: '2¼ tsp (1 packet)' },
      { name: 'Whole Milk', amount: '¾ cup, warmed to 105–110°F' },
      { name: 'Granulated Sugar', amount: '¼ cup' },
      { name: 'Large Eggs', amount: '2' },
      { name: 'Unsalted Butter', amount: '¼ cup, melted and cooled' },
      { name: 'All-purpose Flour', amount: '4 cups' },
      { name: 'Kosher Salt', amount: '1 tsp' },
      { name: 'Vegetable Oil', amount: 'about 2 qt, for deep frying' },
      { name: 'Powdered Sugar', amount: '2 cups' },
      { name: 'Pure Vanilla Extract', amount: '1 tsp' },
      { name: 'Milk', amount: '3–4 tbsp, for glaze' },
    ],
    steps: [
      { title: 'Activate the Yeast', description: 'In the bowl of a stand mixer (or a large bowl), whisk the warm milk, granulated sugar, and yeast. Let stand until foamy, 5–10 minutes—if nothing bubbles, your yeast may be inactive and you should start again with fresh yeast and properly warmed milk.' },
      { title: 'Build and Knead the Dough', description: 'Beat in the eggs and melted butter until smooth. Add the flour and salt; mix on low until a shaggy dough forms, then knead by machine or hand until the dough is smooth, elastic, and passes the windowpane test when stretched thin. It should feel tacky but not hopelessly sticky.' },
      { title: 'First Rise', description: 'Transfer to a lightly oiled bowl, turn once to coat, and cover with plastic wrap or a damp towel. Let rise in a warm, draft-free spot until roughly doubled in volume. A proper first rise sets the structure for light, airy donuts.', timer: 3600 },
      { title: 'Shape the Donuts', description: 'Punch down the dough and roll on a lightly floured surface to about ½ inch thick. Cut rounds with a 3-inch cutter and use a smaller cutter or piping tip for the centers; reroll scraps once to avoid tough dough. Place cut donuts and holes on parchment-lined sheets, spacing them so they can expand.' },
      { title: 'Second Rise', description: 'Cover loosely and let proof until the donuts look puffed and spring back slowly when gently pressed—under-proofed rings will be dense; over-proofed ones may collapse in the oil.', timer: 1800 },
      { title: 'Fry Until Golden', description: 'Heat oil in a heavy pot to 350°F (175°C). Fry a few donuts at a time without crowding, turning once, until deep golden on both sides. Drain on a wire rack set over paper towels. Whisk powdered sugar, vanilla, and milk until pourable; dip warm donuts in the glaze and return to the rack to set.', timer: 120 },
    ]
  },
  {
    id: '3',
    title: 'Zesty Lemon Meringue Tart',
    description: 'A masterclass in restraint. This dish relies on the heat of Calabrian chilies and the sweetness of sun-ripened tomatoes.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBKfTDHbRHr2takOlyyzOBMk3YOVc4Z0h_F1Ob0yDfCJK1Qy2raT31YXAgJtS_yWxvkNBNL2UUXS9c7_bRQ9AGh_QJlI3omUHAPTr0K2mrVrCEFYCwBenExzL3JYFYV9DjDhGQT4jocFLOFE5QPpg4Uyqb0cujZu_lMXA7XhPLAQIlSEXufIjdpcMFFIONTqZjge_zOG7rIbG_ieWlV5PTnBA9lBYfb1UzIsbTEyaUxgrRxxR86rJFhByG8nJEp9qkhRDT6YTqM4w',
    difficulty: 'Medium',
    time: '45 mins',
    prepTime: '30 mins',
    category: 'Main Course',
    tags: ['pasta', 'italian', 'weeknight', 'spicy', 'tomatoes'],
    ingredients: [
      { name: 'Tomatoes', amount: '400g', image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAyfCJRpnAEbfHrCJbZ8ydvnwL_c5y8E4ELwWOFYLFLBHqBGOXUFkKQbdmVIMFWpqEpKJ0jieBXl2h3b3-TfGOVc-KXddgKWUQgd-Ujg4cB4cG4fnhPsuVZ1TgBd8G0DLRZ9MFM0FbmUTBnqhAh2U_N9kGQEW75uOm5tsyAzaYe2H4hj-VR17L0zYL8xOXe12HKOocgpF8kPYshyLRF4c9eMBZTH6ex_iEXny8Z6YgmC13IM3OHlhb8vgxIWBRpeaYa58t8sli-qw' },
      { name: 'Pasta', amount: '200g', image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC57ir0ORU_gyZhLs6cSuHJlk0kkvqwFZ8bVOQVhMTWvJncG4BWKJWMlWKQ-R6tQJhTSs_xxkXsNo1bHrsPyf5xGherYBTb-1bUDvtc2Zy-BUFvfPTNTKWA9ZkyCBJqXO4_uBygZ3cQEFGjZRLbbtClu5OxPe9SBmitKPJk-p99iVcrZILOskbTPo0bE30hh3LAm4XWMvCF7zg4oyXlmS__mL1Go4wcTxfX6VuJaq_B9hvInKDNqIRr_wEPeCEePhV8wMW_NW7OOA' },
      { name: 'Garlic', amount: '3 Cloves', image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAcfHJb0Rct2IUmiQZR_jJiIQxnRQgxnxxBSJch7HNdcJdFEV7VL0790z5roK638nFjickdliH43DKqDpaEyAr9D7LdAOmnC1Bw1MxVb2oC_NLiSTsAwDlU8qbciC_wUUgzhf7heQTholE6pB1eZwlXR1Mz46QXvsyOjrGHT9SZAPKaGtrRtdVuCzs8jIQ-J90552FFYSdKESw7t-CI22wGsixGN9Sgsire7MatCsSKYYgPtqzviPdH0rVVXaLJuO4cgqrtGqdcEA' },
      { name: 'Dried Chilies', amount: '2', image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBFiVCzM56dlndPC8HAaPFGf869LscOPVAogegHVRGrSIsdqd7gBdVtGHaH29s6G4cG_gMGfGZR48SViroqTNlgTBXYzuzGOIC7pxCyC7g3DqSedz-67P-iapQYBrkjazoX-ETDS0EHlY1RGis77b0POlKgfxER01Ii7zQEc6nMO6KQu5eaLPM1ggRRQ7Xu_TnYCfZEfXoE-Ve181BwjcKLiFjTXYQfMB5lPO6MX4TtUTEx9HRAmLPseX4UZ5yPaiBl4MAy-LR6Mg' },
      { name: 'Oil', amount: '2 tbsp', image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCXYw7e6ZbAXgTnZzJBLQB_eWXQ4aRKxY29-ZAAS466F_MTTgdICm_tIpijLrZNADK9AqS4Sma3ZTk2E8wc-6pN5MjfxuRCvCtOqfjToFhw-hhXds5LWP_3lnIV9NCisBhN0iKUhjt4dlOyAwTv5ao__yohwCGq0Sm-NKq5ykeO20n5n5DGIb95imqrsH8m3YNwLKqHJMe_TQiSjyJuzkApvG9BPF-_aZ6Yjlx2aLQc5tCvLfV-Ms1OxeV25D76FtDMDm1-P-Xmyg' },
      { name: 'Fresh Basil', amount: 'Handful', image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDmCokkEI0Cd8sWgeqOHwJnFtHtg-Qur6yVV_onc3mQAu7ekwxHHN4kgYCAneTKP7rH5rw5xjGo2RFMRfqlShVhGQQpSb1ccLpYfIMnRYaICUdh6C54FV78SFKluGgU0KlgbstNHW-qR9CIvCaB1rrNoy5xV-z9X3gkik9kmf25wRbon6ztTbmmhF_yDO7pYayE2Erc_rjOU9_V5AY-TTQfbFPsODGwYgLjiTkB_pu9KUIy8B6gxJY883Q0MFqO7FQR7MzbeoblwA' },
    ],
    steps: [
      { title: 'The Foundation', description: 'Heat the olive oil in a wide skillet over medium-low heat. Add sliced garlic and crushed chilies. Sauté gently until the garlic is golden but never burnt.' },
      { title: 'The Reduction', description: 'Pour in the tomatoes. Increase the heat slightly and simmer for 15 minutes. Use a wooden spoon to break the tomatoes down into a thick, glossy sauce.' },
      { title: 'The Marriage', description: 'Cook your pasta until very al dente. Transfer directly into the skillet with a splash of starchy pasta water. Toss vigorously until the sauce clings to every strand.' },
    ]
  },
  {
    id: '4',
    title: 'Overnight Country Sourdough',
    description: 'Rustic loaf of sourdough bread with intricate scoring patterns on a wooden board with flour dusting.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDpb0SiokUo29bCG4pSqhH1OTS_hebScWy8uyr-4umhxWLOcAv9QCT_BYgraHODltutk3tLcNWEx9wzOSslJ39OoAeKKI-MKoY078uIPOvbSs-tPxB0PQ9qTDbU5hPFe1qU0rk4Plcv-NiNfkeTxaRm15cAFnCZaQ74aw4FsVIr4HwLjR3z4VIhzbt7F1tdHj91Pk8lbr8FVmvoru3VwO0npKqFZBhfRvVOtjxN6Wpfq1lHNkvh4krJbVy7oglyx-teC7QzKciupg',
    difficulty: 'Expert',
    time: '24 hrs',
    prepTime: '1 hr',
    bakeTime: '45 mins',
    yields: '1 loaf',
    category: 'Bread',
    tags: ['sourdough', 'bread', 'fermentation', 'overnight', 'dutch oven'],
    isHeirloom: true,
    chefNote: 'The overnight cold retard is where this loaf earns its name: slow fermentation deepens acidity and complexity in the crumb while the chilled, firm dough scores cleanly and opens dramatically in the oven—listen for that crackling crust as it cools; that is the sound of a well-timed retard.',
    ingredients: [
      { name: 'Bread Flour', amount: '3½ cups' },
      { name: 'Whole Wheat Flour', amount: '¾ cup' },
      { name: 'Water', amount: '1½ cups, room temperature' },
      { name: 'Active Sourdough Starter (100% hydration)', amount: '½ cup, ripe and bubbly' },
      { name: 'Fine Sea Salt', amount: '2 tsp' },
    ],
    steps: [
      { title: 'Autolyse the Flours and Water', description: 'In a large bowl, combine the bread flour, whole wheat flour, and water until no dry pockets remain. Cover and rest—this passive hydration relaxes the gluten and lets enzymes begin breaking down starches, yielding a more extensible dough with less kneading later.', timer: 1800 },
      { title: 'Mix in Levain and Salt', description: 'Add the ripe starter and salt to the autolysed dough. Pinch, squeeze, and fold until the mixture is homogeneous and the salt is fully distributed. The dough will feel wet and shaggy at first; resist adding extra flour unless the formula is clearly off for your environment.' },
      { title: 'Bulk Ferment with Stretch-and-Folds', description: 'Cover and let the dough ferment at cool room temperature, performing a gentle stretch-and-fold from each side of the bowl every 30–45 minutes for the first 2 hours. You are building strength without tearing the gluten: each fold should smooth the surface and help the dough hold its shape.', timer: 14400 },
      { title: 'Preshape and Bench Rest', description: 'Turn the dough onto a lightly floured counter with minimal degassing. Shape into a loose round, seam side down, and let rest 20–30 minutes under a cloth. This relaxes the gluten so the final shaping does not fight you and the skin stays taut.' },
      { title: 'Final Shape and Cold Retard', description: 'Shape into a tight batard or boule, creating surface tension so the loaf holds its form. Place seam-side up in a floured banneton or cloth-lined bowl, cover, and refrigerate overnight. The cold slows yeast activity while bacteria keep developing flavor—this is the “country” character in the crumb and crust.', timer: 43200 },
      { title: 'Preheat, Score, and Bake with Steam', description: 'Place a Dutch oven or baking stone in the oven and preheat to 450°F (230°C). Turn out the cold dough onto parchment, score decisively with a lame or razor so steam can escape in a controlled pattern, then bake with steam (lid on or pan of water) for the first phase, then finish uncovered until the crust is deeply bronzed and the loaf sounds hollow when tapped. Cool completely on a rack before slicing—cutting too early steams the crumb and dulls the crust.', timer: 2700 },
    ]
  },
  {
    id: '5',
    title: 'Classic Miso Soup',
    description: 'A light Japanese starter with silky tofu, wakame, and savory white or red miso—comforting in minutes.',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=800&q=80',
    difficulty: 'Easy',
    time: '20 mins',
    prepTime: '10 mins',
    yields: '4 servings',
    category: 'Japanese',
    tags: ['miso', 'soup', 'tofu', 'quick', 'vegetarian'],
    ingredients: [
      { name: 'Dashi (or water)', amount: '4 cups' },
      { name: 'White or awase miso', amount: '3–4 tbsp' },
      { name: 'Silken tofu', amount: '½ block, cubed' },
      { name: 'Dried wakame', amount: '1 tbsp, soaked' },
      { name: 'Green onions', amount: '2, thinly sliced' },
    ],
    steps: [
      { title: 'Warm the dashi', description: 'Bring dashi to a bare simmer in a pot—do not boil vigorously or the miso aroma will flatten.', timer: 300 },
      { title: 'Dissolve miso', description: 'Ladle a cup of hot liquid into a bowl, whisk miso until smooth, then stir back into the pot. Taste and adjust saltiness.' },
      { title: 'Add tofu and wakame', description: 'Gently add tofu cubes and soaked wakame; simmer 1–2 minutes until heated through.' },
      { title: 'Serve', description: 'Ladle into bowls; top with green onions. Serve immediately while fragrant.' },
    ],
  },
  {
    id: '6',
    title: 'Spanish Tortilla Española',
    description: 'A thick potato and onion omelette, golden outside and tender inside—perfect warm or at room temperature.',
    image: 'https://images.unsplash.com/photo-1565299507177-b0ac66763828?auto=format&fit=crop&w=800&q=80',
    difficulty: 'Easy',
    time: '45 mins',
    prepTime: '15 mins',
    bakeTime: '25 mins covered',
    yields: '6 slices',
    category: 'Tapas',
    tags: ['spanish', 'eggs', 'potato', 'pantry'],
    ingredients: [
      { name: 'Yukon or waxy potatoes', amount: '1 lb, peeled, sliced ⅛ inch' },
      { name: 'Yellow onion', amount: '1 large, sliced' },
      { name: 'Extra-virgin olive oil', amount: '1½ cups' },
      { name: 'Large eggs', amount: '6' },
      { name: 'Kosher salt', amount: '1¼ tsp' },
    ],
    steps: [
      { title: 'Slow-cook potatoes', description: 'In a 10-inch oven-safe skillet, gently fry potato and onion in oil over medium-low until potatoes yield to a knife without browning heavily—about 20–25 minutes. Drain most oil; reserve for later.', timer: 1500 },
      { title: 'Bind with eggs', description: 'Beat eggs with salt in a large bowl. Fold in warm potatoes and onions. Let sit 5 minutes so flavors meld.', timer: 300 },
      { title: 'Set the tortilla', description: 'Wipe skillet; heat 2 tbsp reserved oil. Pour in egg mixture; cook on medium-low, running a spatula around edges until bottom is set but top is moist.', timer: 600 },
      { title: 'Flip or finish', description: 'Invert carefully onto a plate, slide back into pan to cook the second side, or finish under a broiler until just set in the center. Cool 10 minutes before slicing.', timer: 600 },
    ],
  },
  {
    id: '7',
    title: 'Korean Bibimbap Bowl',
    description: 'Rice topped with colorful vegetables, gochujang sauce, and optional egg—a customizable weeknight favorite.',
    image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&w=800&q=80',
    difficulty: 'Easy',
    time: '35 mins',
    prepTime: '25 mins',
    yields: '4 bowls',
    category: 'Korean',
    tags: ['bibimbap', 'rice', 'vegetables', 'gochujang'],
    ingredients: [
      { name: 'Short-grain rice', amount: '2 cups cooked' },
      { name: 'Spinach', amount: '6 oz, blanched and squeezed' },
      { name: 'Carrots', amount: '1 cup julienned, lightly sautéed' },
      { name: 'Bean sprouts', amount: '1 cup, blanched' },
      { name: 'Mushrooms', amount: '6 oz, sliced, sautéed' },
      { name: 'Gochujang', amount: '3 tbsp' },
      { name: 'Sesame oil', amount: '1 tbsp' },
      { name: 'Soy sauce', amount: '1 tbsp' },
      { name: 'Eggs', amount: '4, fried sunny-side up' },
      { name: 'Toasted sesame seeds', amount: '1 tbsp' },
    ],
    steps: [
      { title: 'Prep the toppings', description: 'Season spinach with a pinch of salt and sesame oil. Arrange carrots, sprouts, and mushrooms in separate piles—each lightly seasoned with salt or soy.' },
      { title: 'Make the sauce', description: 'Whisk gochujang with 1 tsp sesame oil, soy sauce, and 1–2 tbsp water until pourable.' },
      { title: 'Assemble', description: 'Divide rice among bowls; arrange vegetables in sections. Top with a fried egg and drizzle sauce. Sprinkle sesame seeds and serve.' },
    ],
  },
  {
    id: '8',
    title: 'Lebanese Fattoush',
    description: 'Crunchy pita, sumac, and fresh herbs make this bright salad a staple across the Levant.',
    image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&w=800&q=80',
    difficulty: 'Easy',
    time: '25 mins',
    prepTime: '25 mins',
    yields: '4 servings',
    category: 'Levant',
    tags: ['salad', 'sumac', 'mezze', 'fresh'],
    ingredients: [
      { name: 'Romaine or mixed greens', amount: '6 cups chopped' },
      { name: 'Cucumber', amount: '1, diced' },
      { name: 'Tomatoes', amount: '2 medium, chopped' },
      { name: 'Radishes', amount: '4, sliced' },
      { name: 'Flatbread or pita', amount: '2, toasted and broken' },
      { name: 'Fresh mint and parsley', amount: '1 cup combined, chopped' },
      { name: 'Olive oil', amount: '¼ cup' },
      { name: 'Lemon juice', amount: '3 tbsp' },
      { name: 'Ground sumac', amount: '1½ tsp' },
      { name: 'Pomegranate molasses', amount: '1 tbsp optional' },
    ],
    steps: [
      { title: 'Toast the bread', description: 'Brush pita with oil; bake or pan-toast until crisp. Break into shards.' },
      { title: 'Whisk dressing', description: 'Combine olive oil, lemon juice, sumac, salt, pepper, and pomegranate molasses if using.' },
      { title: 'Toss and serve', description: 'Combine greens, cucumber, tomatoes, radishes, and herbs. Toss with dressing; add pita at the last moment so it stays crisp.' },
    ],
  },
  {
    id: '9',
    title: 'Mexican Esquites',
    description: 'Street-style charred corn cups with lime, mayonnaise, cotija, and chili—snackable and bold.',
    image: 'https://images.unsplash.com/photo-1529042410759-befb1204b468?auto=format&fit=crop&w=800&q=80',
    difficulty: 'Easy',
    time: '20 mins',
    prepTime: '15 mins',
    yields: '4 cups',
    category: 'Street Food',
    tags: ['corn', 'mexican', 'snack', 'grill'],
    ingredients: [
      { name: 'Corn kernels', amount: '4 cups fresh or thawed frozen' },
      { name: 'Neutral oil', amount: '2 tbsp' },
      { name: 'Mayonnaise', amount: '¼ cup' },
      { name: 'Mexican crema or sour cream', amount: '2 tbsp' },
      { name: 'Lime', amount: '1, juiced' },
      { name: 'Cotija or feta', amount: '½ cup, crumbled' },
      { name: 'Chili powder or Tajín', amount: '½–1 tsp' },
      { name: 'Cilantro', amount: '¼ cup chopped' },
    ],
    steps: [
      { title: 'Char the corn', description: 'In a hot skillet with oil, cook corn without stirring until blistered; stir and repeat until lightly charred.' },
      { title: 'Dress', description: 'Off heat, fold in mayo, crema, lime juice, half the cheese, and chili. Season with salt.' },
      { title: 'Serve', description: 'Spoon into cups; top with remaining cheese and cilantro. Serve warm.' },
    ],
  },
  {
    id: '10',
    title: 'Turkish Menemen',
    description: 'Soft-scrambled eggs with peppers, tomatoes, and spices—breakfast from Istanbul to your table.',
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80',
    difficulty: 'Easy',
    time: '30 mins',
    prepTime: '10 mins',
    yields: '3 servings',
    category: 'Turkish',
    tags: ['eggs', 'breakfast', 'peppers', 'one-pan'],
    ingredients: [
      { name: 'Green bell pepper or Turkish çarliston', amount: '2, chopped' },
      { name: 'Ripe tomatoes', amount: '3 medium, diced' },
      { name: 'Olive oil or butter', amount: '2 tbsp' },
      { name: 'Aleppo pepper or paprika', amount: '½ tsp' },
      { name: 'Large eggs', amount: '4' },
      { name: 'Feta', amount: '2 oz optional, crumbled' },
      { name: 'Crusty bread', amount: 'for serving' },
    ],
    steps: [
      { title: 'Soften peppers', description: 'Cook peppers in oil over medium until tender, 6–8 minutes.', timer: 420 },
      { title: 'Jammy tomatoes', description: 'Add tomatoes and spice; cook until saucy but not watery, stirring occasionally.', timer: 600 },
      { title: 'Fold in eggs', description: 'Make wells; crack eggs in and stir gently for soft curds, or cover and poach until whites set. Top with feta if using. Serve with bread.' },
    ],
  },
  {
    id: '11',
    title: 'Indian Masoor Dal',
    description: 'Red lentils simmered with turmeric, tomatoes, and tadka—a weeknight dal that loves basmati on the side.',
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80',
    difficulty: 'Easy',
    time: '35 mins',
    prepTime: '10 mins',
    yields: '4 servings',
    category: 'Curry Night',
    tags: ['dal', 'lentils', 'indian', 'vegan'],
    ingredients: [
      { name: 'Red lentils (masoor)', amount: '1 cup, rinsed' },
      { name: 'Water or vegetable broth', amount: '3 cups' },
      { name: 'Tomato', amount: '1 medium, diced' },
      { name: 'Turmeric', amount: '½ tsp' },
      { name: 'Ghee or oil', amount: '2 tbsp' },
      { name: 'Cumin seeds', amount: '1 tsp' },
      { name: 'Garlic', amount: '3 cloves, minced' },
      { name: 'Ginger', amount: '1 tbsp grated' },
      { name: 'Garam masala', amount: '½ tsp' },
      { name: 'Lemon', amount: '½, to finish' },
      { name: 'Cilantro', amount: 'handful' },
    ],
    steps: [
      { title: 'Simmer dal', description: 'Combine lentils, water, tomato, and turmeric in a pot. Simmer until dal falls apart, 20–25 minutes, stirring often.', timer: 1500 },
      { title: 'Tadka', description: 'In a small pan, heat ghee; sizzle cumin, then add garlic and ginger until fragrant. Add garam masala off heat.' },
      { title: 'Finish', description: 'Stir tadka into dal; season with salt and lemon. Garnish with cilantro.' },
    ],
  },
  {
    id: '12',
    title: 'Citrus-Marinated Shrimp Ceviche Tostada',
    description: 'Gently poached shrimp chilled in lime and orange—bright and safe for home cooks who prefer cooked seafood.',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80',
    difficulty: 'Easy',
    time: '40 mins',
    prepTime: '25 mins',
    yields: '6 tostadas',
    category: 'Coastal Latin',
    tags: ['ceviche', 'shrimp', 'lime', 'tostada'],
    chefNote: 'This version poaches shrimp first, then marinates—ideal if you want classic ceviche flavor without raw seafood.',
    ingredients: [
      { name: 'Large shrimp, peeled', amount: '1 lb' },
      { name: 'Lime juice', amount: '½ cup' },
      { name: 'Orange juice', amount: '¼ cup' },
      { name: 'Red onion', amount: '½ small, thinly sliced' },
      { name: 'Jalapeño', amount: '1, minced' },
      { name: 'Cherry tomatoes', amount: '1 cup, halved' },
      { name: 'Cucumber', amount: '½ cup diced' },
      { name: 'Avocado', amount: '1, diced' },
      { name: 'Tostadas or fried tortillas', amount: '6' },
      { name: 'Cilantro', amount: '¼ cup' },
    ],
    steps: [
      { title: 'Poach shrimp', description: 'Briefly poach shrimp in salted simmering water until just pink; plunge in ice water, drain, chop bite-size.', timer: 180 },
      { title: 'Marinate', description: 'Combine shrimp with citrus, onion, and jalapeño; chill 20 minutes. Season with salt.', timer: 1200 },
      { title: 'Assemble', description: 'Fold in tomatoes and cucumber; top tostadas with mixture and avocado. Serve immediately.' },
    ],
  },
  {
    id: '13',
    title: 'Thai Green Curry',
    description: 'Coconut milk, green curry paste, and Thai basil in harmony—adjust heat to your table.',
    image: 'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?auto=format&fit=crop&w=800&q=80',
    difficulty: 'Medium',
    time: '40 mins',
    prepTime: '20 mins',
    yields: '4 servings',
    category: 'Thai',
    tags: ['curry', 'coconut', 'chicken', 'aromatic'],
    ingredients: [
      { name: 'Coconut milk', amount: '2 cans (about 28 oz)' },
      { name: 'Green curry paste', amount: '3–4 tbsp' },
      { name: 'Chicken thighs, boneless', amount: '1½ lb, cubed' },
      { name: 'Fish sauce', amount: '2 tbsp' },
      { name: 'Palm or brown sugar', amount: '1 tbsp' },
      { name: 'Thai eggplant or zucchini', amount: '2 cups, chunked' },
      { name: 'Bell pepper', amount: '1, sliced' },
      { name: 'Thai basil', amount: '1 cup' },
      { name: 'Lime', amount: '1, for serving' },
    ],
    steps: [
      { title: 'Bloom paste', description: 'Simmer ½ can thick coconut cream (or top of a can) with curry paste until oil speckles appear.', timer: 300 },
      { title: 'Build curry', description: 'Add chicken; cook until sealed. Pour remaining coconut milk; simmer until chicken is nearly done.', timer: 900 },
      { title: 'Vegetables and finish', description: 'Add vegetables, fish sauce, and sugar; simmer until tender. Fold in basil; squeeze lime. Serve with jasmine rice.' },
    ],
  },
  {
    id: '14',
    title: 'Moroccan Chicken Tagine',
    description: 'Warm spices, olives, and preserved lemon give this braise its signature North African aroma.',
    image: 'https://images.unsplash.com/photo-1551218808-94e220e084d2?auto=format&fit=crop&w=800&q=80',
    difficulty: 'Medium',
    time: '1 hr 15 mins',
    prepTime: '20 mins',
    yields: '6 servings',
    category: 'North African',
    tags: ['tagine', 'chicken', 'olives', 'preserved lemon'],
    ingredients: [
      { name: 'Chicken pieces', amount: '3–4 lb' },
      { name: 'Onion', amount: '2, sliced' },
      { name: 'Garlic', amount: '4 cloves' },
      { name: 'Ginger', amount: '1 tbsp grated' },
      { name: 'Ras el hanout', amount: '2 tsp' },
      { name: 'Cinnamon stick', amount: '1' },
      { name: 'Chicken broth', amount: '1 cup' },
      { name: 'Diced tomatoes', amount: '1 can (14 oz)' },
      { name: 'Green olives', amount: '1 cup' },
      { name: 'Preserved lemon', amount: '1, flesh removed, rind sliced' },
      { name: 'Cilantro', amount: 'handful' },
    ],
    steps: [
      { title: 'Brown the chicken', description: 'Season chicken; brown in a tagine or Dutch oven. Set aside.', timer: 600 },
      { title: 'Sweat aromatics', description: 'Cook onion until golden; add garlic, ginger, ras el hanout, and cinnamon. Return chicken.', timer: 600 },
      { title: 'Braise', description: 'Add broth and tomatoes; simmer covered until chicken pulls from bone, 35–45 minutes.', timer: 2400 },
      { title: 'Finish', description: 'Stir in olives and preserved lemon; rest 10 minutes. Top with cilantro; serve with couscous.', timer: 600 },
    ],
  },
  {
    id: '15',
    title: 'Sichuan Mapo Tofu',
    description: 'Silken tofu in a spicy fermented bean and pork sauce—serve with plenty of steamed rice.',
    image: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?auto=format&fit=crop&w=800&q=80',
    difficulty: 'Medium',
    time: '35 mins',
    prepTime: '15 mins',
    yields: '4 servings',
    category: 'Sichuan',
    tags: ['tofu', 'spicy', 'pork', 'stir-fry'],
    ingredients: [
      { name: 'Silken or medium tofu', amount: '14–16 oz block, cubed' },
      { name: 'Ground pork', amount: '6 oz optional' },
      { name: 'Doubanjiang (chili bean paste)', amount: '2 tbsp' },
      { name: 'Douchi (fermented black beans)', amount: '1 tbsp, rinsed, chopped' },
      { name: 'Garlic and ginger', amount: '2 tsp each, minced' },
      { name: 'Chicken stock', amount: '¾ cup' },
      { name: 'Cornstarch slurry', amount: '1 tsp cornstarch + 2 tbsp water' },
      { name: 'Sichuan peppercorn oil or toasted Sichuan pepper', amount: 'to taste' },
      { name: 'Green onion', amount: '2, sliced' },
    ],
    steps: [
      { title: 'Bloom the paste', description: 'Stir-fry pork if using until browned; add doubanjiang, douchi, garlic, and ginger until fragrant.', timer: 300 },
      { title: 'Simmer tofu', description: 'Add stock; gently slide in tofu. Simmer 5–8 minutes without rough stirring.', timer: 420 },
      { title: 'Thicken and finish', description: 'Stir in slurry to glossy; drizzle pepper oil. Top with green onion. Serve hot.' },
    ],
  },
  {
    id: '16',
    title: 'Greek Moussaka (Simplified)',
    description: 'Layered eggplant, spiced lamb, and béchamel—royal comfort without a full-day project.',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80',
    difficulty: 'Medium',
    time: '2 hrs',
    prepTime: '45 mins',
    bakeTime: '45 mins',
    yields: '8 servings',
    category: 'Greek',
    tags: ['eggplant', 'lamb', 'casserole', 'béchamel'],
    ingredients: [
      { name: 'Globe eggplants', amount: '2 large, sliced ½ inch' },
      { name: 'Ground lamb or beef', amount: '1½ lb' },
      { name: 'Onion', amount: '1, chopped' },
      { name: 'Garlic', amount: '3 cloves' },
      { name: 'Canned tomatoes', amount: '1 can (28 oz)' },
      { name: 'Cinnamon and oregano', amount: 'pinch + 1 tsp' },
      { name: 'Butter', amount: '4 tbsp' },
      { name: 'Flour', amount: '4 tbsp' },
      { name: 'Milk', amount: '2 cups' },
      { name: 'Egg yolks', amount: '2' },
      { name: 'Kefalotyri or parmesan', amount: '½ cup grated' },
    ],
    steps: [
      { title: 'Prepare eggplant', description: 'Salt slices, rest, pat dry; broil or roast until golden. Set aside.', timer: 1200 },
      { title: 'Meat sauce', description: 'Brown meat with onion and garlic; add tomatoes, cinnamon, oregano. Simmer 25 minutes until thick.', timer: 1500 },
      { title: 'Béchamel', description: 'Cook butter and flour; whisk in milk until thick. Off heat, temper in yolks and half the cheese.', timer: 600 },
      { title: 'Layer and bake', description: 'Layer eggplant, meat, repeat; top with béchamel and cheese. Bake at 375°F (190°C) until bubbling and bronzed.', timer: 2700 },
    ],
  },
  {
    id: '17',
    title: 'Vietnamese Bún Chả-Style Noodle Bowl',
    description: 'Grilled pork patties in nuoc cham with cool vermicelli and herbs—a Hanoi favorite at home.',
    image: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&w=800&q=80',
    difficulty: 'Medium',
    time: '50 mins',
    prepTime: '30 mins',
    yields: '4 bowls',
    category: 'Vietnamese',
    tags: ['noodles', 'pork', 'herbs', 'grill'],
    ingredients: [
      { name: 'Ground pork', amount: '1 lb' },
      { name: 'Fish sauce', amount: '3 tbsp, divided' },
      { name: 'Shallots', amount: '2, minced' },
      { name: 'Sugar', amount: '2 tbsp' },
      { name: 'Rice vinegar', amount: '3 tbsp' },
      { name: 'Lime juice', amount: '¼ cup' },
      { name: 'Warm water', amount: '½ cup' },
      { name: 'Vermicelli noodles', amount: '12 oz cooked, cooled' },
      { name: 'Herb platter', amount: 'mint, cilantro, lettuce, bean sprouts' },
    ],
    steps: [
      { title: 'Shape and grill pork', description: 'Mix pork with 1 tbsp fish sauce and shallots; form small patties. Grill or broil until caramelized.', timer: 600 },
      { title: 'Nuoc cham', description: 'Whisk remaining fish sauce, sugar, vinegar, lime, and water until balanced; add sliced chili if desired.' },
      { title: 'Serve', description: 'Divide noodles and herbs; top with pork. Pass nuoc cham at the table.' },
    ],
  },
  {
    id: '18',
    title: 'Brazilian Moqueca',
    description: 'Fish and shrimp in coconut–dende oil stew with peppers—a taste of Bahia.',
    image: 'https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?auto=format&fit=crop&w=800&q=80',
    difficulty: 'Medium',
    time: '45 mins',
    prepTime: '20 mins',
    yields: '6 servings',
    category: 'Brazilian',
    tags: ['seafood', 'coconut', 'stew', 'bahia'],
    ingredients: [
      { name: 'Firm white fish', amount: '1½ lb, chunked' },
      { name: 'Shrimp', amount: '½ lb optional' },
      { name: 'Bell peppers', amount: '2, sliced' },
      { name: 'Onion', amount: '1, sliced' },
      { name: 'Garlic', amount: '4 cloves' },
      { name: 'Tomatoes', amount: '3, chopped' },
      { name: 'Coconut milk', amount: '2 cans' },
      { name: 'Palm oil (dende) or olive oil', amount: '1–2 tbsp' },
      { name: 'Palm vinegar or lime', amount: '1 tbsp' },
      { name: 'Cilantro', amount: 'handful' },
    ],
    steps: [
      { title: 'Layer the stew', description: 'In a wide pot, layer onion, peppers, tomatoes, garlic, then fish and shrimp. Pour coconut milk and dende; season.', timer: 60 },
      { title: 'Poach gently', description: 'Simmer uncovered until fish flakes and shrimp curl—avoid boiling hard.', timer: 900 },
      { title: 'Finish', description: 'Stir in vinegar or lime; garnish with cilantro. Serve with rice and farofa if available.' },
    ],
  },
  {
    id: '19',
    title: 'Jamaican Jerk Chicken',
    description: 'Allspice, thyme, and Scotch bonnet heat—grilled or oven-roasted until lacquered.',
    image: 'https://images.unsplash.com/photo-1529042410759-befb1204b468?auto=format&fit=crop&w=800&q=80',
    difficulty: 'Medium',
    time: '3 hrs',
    prepTime: '30 mins',
    bakeTime: '1 hr',
    yields: '6 servings',
    category: 'Caribbean',
    tags: ['jerk', 'grill', 'chicken', 'spicy'],
    ingredients: [
      { name: 'Chicken pieces', amount: '3–4 lb' },
      { name: 'Scotch bonnet or habanero', amount: '1–2' },
      { name: 'Scallions', amount: '4' },
      { name: 'Fresh thyme', amount: '1 bunch' },
      { name: 'Allspice berries, ground', amount: '1 tbsp' },
      { name: 'Soy sauce', amount: '2 tbsp' },
      { name: 'Brown sugar', amount: '2 tbsp' },
      { name: 'Lime juice', amount: '¼ cup' },
      { name: 'Ginger and garlic', amount: '2 tbsp and 4 cloves' },
      { name: 'Neutral oil', amount: '2 tbsp' },
    ],
    steps: [
      { title: 'Blend marinade', description: 'Puree chiles, scallions, thyme, allspice, soy, sugar, lime, ginger, garlic, and oil. Taste for heat.', timer: 120 },
      { title: 'Marinate', description: 'Coat chicken; refrigerate at least 2 hours or overnight.', timer: 7200 },
      { title: 'Cook', description: 'Grill over medium indirect heat or roast at 400°F (200°C), basting with reserved marinade, until juices run clear and skin chars in spots.', timer: 3600 },
    ],
  },
  {
    id: '20',
    title: 'Polish Potato-Cheese Pierogi',
    description: 'Tender dumplings filled with farmer cheese and mashed potato—boil, then butter-fry for the full experience.',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80',
    difficulty: 'Advanced',
    time: '3 hrs',
    prepTime: '2 hrs',
    yields: 'About 40 pierogi',
    category: 'Polish',
    tags: ['pierogi', 'dumplings', 'potato', 'weekend project'],
    chefNote: 'Keep dough covered; roll thin but not translucent—practice makes evenly sealed crescents.',
    ingredients: [
      { name: 'All-purpose flour', amount: '4 cups' },
      { name: 'Large eggs', amount: '2' },
      { name: 'Warm water', amount: 'about 1 cup' },
      { name: 'Kosher salt', amount: '1 tsp dough + pinch filling' },
      { name: 'Russet potatoes', amount: '1½ lb, boiled and mashed' },
      { name: 'Farmer cheese or dry curd cottage cheese', amount: '1 cup' },
      { name: 'Caramelized onion', amount: '1 large, cooled' },
      { name: 'Butter', amount: '4 tbsp for frying' },
    ],
    steps: [
      { title: 'Dough', description: 'Mix flour, eggs, water, and salt to a smooth, slightly sticky dough; rest 30 minutes wrapped.', timer: 1800 },
      { title: 'Filling', description: 'Combine potatoes, cheese, onion, and salt; cool completely so dough does not steam open.' },
      { title: 'Fill and seal', description: 'Roll dough thin; cut 3-inch rounds. Spoon filling, fold, pinch tightly. Line on floured sheet.', timer: 3600 },
      { title: 'Cook', description: 'Boil in salted water until they float plus 1 minute. Optionally pan-fry in butter until crisp. Serve with sour cream.' },
    ],
  },
  {
    id: '21',
    title: 'French Beef Bourguignon',
    description: 'Red wine, pearl onions, and mushrooms transform chuck into a banquet-worthy braise.',
    image: 'https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&w=800&q=80',
    difficulty: 'Advanced',
    time: '4 hrs',
    prepTime: '45 mins',
    bakeTime: '2 hrs 30 mins low',
    yields: '8 servings',
    category: 'French',
    tags: ['beef', 'wine', 'braise', 'classic'],
    ingredients: [
      { name: 'Beef chuck', amount: '3 lb, cubed' },
      { name: 'Red wine (Burgundy-style)', amount: '3 cups' },
      { name: 'Beef stock', amount: '2 cups' },
      { name: 'Salt pork or bacon', amount: '4 oz, diced' },
      { name: 'Pearl onions', amount: '12, peeled' },
      { name: 'Carrots', amount: '2, chunked' },
      { name: 'Mushrooms', amount: '8 oz, halved' },
      { name: 'Tomato paste', amount: '2 tbsp' },
      { name: 'Bouquet garni', amount: 'thyme, bay, parsley' },
      { name: 'Butter and flour', amount: '2 tbsp each for beurre manié optional' },
    ],
    steps: [
      { title: 'Sear meat', description: 'Pat beef dry; brown deeply in batches. Render bacon; set aside.', timer: 1200 },
      { title: 'Build braise', description: 'Deglaze with wine; reduce slightly. Add stock, paste, bacon, beef, onions, carrots, and bouquet. Bring to simmer.', timer: 600 },
      { title: 'Oven braise', description: 'Cover; cook at 325°F (165°C) until fork-tender, about 2½ hours.', timer: 9000 },
      { title: 'Finish', description: 'Sauté mushrooms separately; fold in. Thicken with beurre manié if desired; rest 20 minutes before serving.', timer: 1200 },
    ],
  },
  {
    id: '22',
    title: 'Indonesian Beef Rendang',
    description: 'Coconut, galangal, and lemongrass cook down until the oil splits—patience rewards with concentrated flavor.',
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=80',
    difficulty: 'Advanced',
    time: '4 hrs',
    prepTime: '30 mins',
    yields: '8 servings',
    category: 'Indonesian',
    tags: ['rendang', 'coconut', 'beef', 'slow cook'],
    ingredients: [
      { name: 'Beef chuck or shin', amount: '3 lb, cubed' },
      { name: 'Coconut milk', amount: '2 cans' },
      { name: 'Lemongrass stalks', amount: '3, bruised' },
      { name: 'Galangal', amount: '2 tbsp sliced' },
      { name: 'Dried chilies', amount: '6–10, soaked' },
      { name: 'Shallots and garlic', amount: '8 shallots + 6 cloves' },
      { name: 'Ginger', amount: '1 inch' },
      { name: 'Coconut sugar or palm sugar', amount: '2 tbsp' },
      { name: 'Tamarind paste', amount: '1 tbsp' },
      { name: 'Kaffir lime leaves', amount: '6' },
    ],
    steps: [
      { title: 'Paste', description: 'Blend chilies, shallots, garlic, ginger, and galangal with water to a fine paste.' },
      { title: 'Initial simmer', description: 'Combine paste, beef, coconut milk, lemongrass, lime leaves in a heavy pot. Simmer uncovered 1 hour, stirring often.', timer: 3600 },
      { title: 'Reduce', description: 'Continue cooking on low, stirring and scraping, as liquid evaporates and oils surface—2+ more hours until dark and almost dry.', timer: 7200 },
      { title: 'Balance', description: 'Stir in sugar and tamarind; season with salt. Rest before serving with rice.' },
    ],
  },
  {
    id: '23',
    title: 'Tonkotsu-Style Ramen at Home',
    description: 'Pork bones, long simmer, and careful straining build a milky broth worthy of a weekend project.',
    image: 'https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=800&q=80',
    difficulty: 'Expert',
    time: '14+ hrs',
    prepTime: '1 hr',
    yields: '8 bowls broth',
    category: 'Japanese',
    tags: ['ramen', 'broth', 'pork', 'overnight'],
    chefNote: 'Maintain a rolling boil for the first hours to emulsify fat and collagen—skim scum but do not fear a vigorous bubble early on.',
    ingredients: [
      { name: 'Pork marrow/femur bones', amount: '4–5 lb' },
      { name: 'Pork back fat or trotters', amount: '1–2 lb' },
      { name: 'Water', amount: '6 qt, plus replenishing' },
      { name: 'Ginger knob', amount: '1, smashed' },
      { name: 'Green onion whites', amount: '4' },
      { name: 'Onion', amount: '2, halved' },
      { name: 'Garlic heads', amount: '2, halved' },
      { name: 'Soy sauce and mirin', amount: 'for seasoning finished chintan' },
      { name: 'Ramen noodles and toppings', amount: 'per bowl: chashu, egg, nori' },
    ],
    steps: [
      { title: 'Blanch bones', description: 'Cover bones with cold water, bring to boil, discard water; scrub bones clean—this keeps the broth clean.', timer: 600 },
      { title: 'Long boil', description: 'Refill pot; rolling boil 8–12 hours, topping up water. Add aromatics in last 2–3 hours. Expect foaming; skim.', timer: 43200 },
      { title: 'Strain and emulsify', description: 'Strain; use blender stick briefly if needed for extra body (optional). Season with tare (soy blend) at serving.' },
      { title: 'Compose bowls', description: 'Cook noodles al dente; add hot broth, tare, oils, and toppings. Consume immediately—ramen waits for no one.' },
    ],
  },
  {
    id: '24',
    title: 'Crispy Duck with Mandarin Pancakes',
    description: 'Dry-aged duck, high-heat roast, and homemade pancakes—an ambitious home interpretation of a banquet classic.',
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80',
    difficulty: 'Expert',
    time: '2 days',
    prepTime: '2 hrs active',
    bakeTime: '1 hr 30 mins',
    yields: '6 servings',
    category: 'Chinese',
    tags: ['duck', 'roast', 'pancakes', 'celebration'],
    ingredients: [
      { name: 'Whole duck', amount: '5–6 lb' },
      { name: 'Boiling water', amount: 'for scalding skin' },
      { name: 'Maltose or honey + water', amount: '¼ cup glaze' },
      { name: 'Shaoxing wine', amount: '2 tbsp for cavity' },
      { name: 'Scallion and ginger', amount: 'for cavity' },
      { name: 'All-purpose flour', amount: '2 cups for pancakes' },
      { name: 'Boiling water', amount: '¾ cup for dough' },
      { name: 'Sesame oil', amount: 'for separating pancake layers' },
      { name: 'Hoisin, cucumber, scallion', amount: 'for serving' },
    ],
    steps: [
      { title: 'Dry-brine and blanch', description: 'Rinse duck; pour boiling water over skin to tighten; hang or rack uncovered in fridge 24–48 hours with glaze brushed on once cool.', timer: 86400 },
      { title: 'Roast', description: 'Stuff cavity; roast breast-side up at high heat, then finish at moderate heat until leg joints move freely and skin shatters.', timer: 5400 },
      { title: 'Pancakes', description: 'Make hot-water dough; rest; roll pairs brushed with oil; pan-cook in stacks, then peel into thin rounds.', timer: 1800 },
      { title: 'Carve and serve', description: 'Carve skin separately if crisp enough; shred meat. Wrap with hoisin, scallion, and cucumber in fresh pancakes.' },
    ],
  },
];
