import { Recipe } from '../types';

// Generated by scripts/scrape-default-recipes.mjs — DO NOT EDIT BY HAND.
// Default recipe library scraped from public schema.org/Recipe data.
// Regenerate with: npm run scrape:default-recipes
// generatedAt=2026-06-27T13:43:36.280Z
export const RECIPES: Recipe[] = [
  {
    "id": "1",
    "title": "Soft Easy Chocolate Chip Cookies",
    "description": "This is my I need chocolate chip cookies now recipe that makes soft, buttery cookies. No waiting for butter to soften, no electric beater, no refrigeration time, no rolling dough into balls.",
    "image": "/recipe-images/recipe-1.jpg",
    "difficulty": "Expert",
    "time": "32 mins",
    "prepTime": "10 mins",
    "bakeTime": "22 mins",
    "yields": "13",
    "category": "Sweet",
    "tags": [
      "imported",
      "web",
      "chocolate chip cookie recipe",
      "sweet",
      "western",
      "recipetineats.com"
    ],
    "ingredients": [
      {
        "amount": "1 3/4 cups",
        "name": "plain / all purpose flour"
      },
      {
        "amount": "1 tsp",
        "name": "salt"
      },
      {
        "amount": "½ tsp",
        "name": "baking soda ((bi carb soda))"
      },
      {
        "amount": "175g",
        "name": "/ 12 tbsp unsalted butter (, cut into 2 cm/ 4/5\" cubes (1.5 US sticks / 6 oz))"
      },
      {
        "amount": "1/2 cup",
        "name": "brown sugar (, packed (light or dark) (Note 1))"
      },
      {
        "amount": "1/2 cup",
        "name": "caster sugar ((US: granulated sugar))"
      },
      {
        "amount": "1",
        "name": "egg"
      },
      {
        "amount": "1",
        "name": "egg yolk"
      },
      {
        "amount": "2 tsp",
        "name": "vanilla extract"
      },
      {
        "amount": "1 1/4 cups",
        "name": "chocolate chips (, separated (US: semi sweet chocolate chips or chunks))"
      }
    ],
    "steps": [
      {
        "title": "Step 1",
        "description": "Preheat oven to 180C / 350F (standard) or 160C/320F (fan / convection). Place oven shelf in the middle of the oven."
      },
      {
        "title": "Step 2",
        "description": "Line 2 trays with baking / parchment paper."
      },
      {
        "title": "Step 3",
        "description": "Whisk the flour, salt and baking soda in a bowl."
      },
      {
        "title": "Step 4",
        "description": "Place the butter in a large heatproof bowl. Microwave until the butter is almost fully melted (25 sec for room temp butter, 40 sec for fridge cold butter on high)."
      },
      {
        "title": "Step 5",
        "description": "Whisk to finish melting the butter. (Note 2)"
      },
      {
        "title": "Step 6",
        "description": "Add brown and white sugar, whisk energetically for 15 seconds."
      },
      {
        "title": "Step 7",
        "description": "Add egg, yolk and vanilla, whisk well for 15 seconds."
      },
      {
        "title": "Step 8",
        "description": "Add flour mixture and mix until flour is almost fully incorporated."
      },
      {
        "title": "Step 9",
        "description": "Add 1 cup chocolate chips, stir to disperse and flour is fully incorporated. Batter will be quite loose."
      },
      {
        "title": "Step 10",
        "description": "Stand for 5 minutes for batter to firm up a bit so it is scoop-able into mounds. (Note 3)"
      },
      {
        "title": "Step 11",
        "description": "LARGE COOKIES: Scoop up a level ice cream scoop / 3 tbsp / 1/4 cup (Note 4) and place on baking trays 5cm / 2\" apart - 13 balls. Top with remaining choc chips (these remain on surface once baked = prettier)."
      },
      {
        "title": "Step 12",
        "description": "SMALL COOKIES (26 - 30): Scoop up 1.5 tbsp (heaped tbsp measure) OR 1/2 an ice cream scoop (this works well). Place on baking trays 4cm / 1.75\" apart, top with choc chops."
      },
      {
        "title": "Step 13",
        "description": "Bake 1 tray at a time. LARGE COOKIES: Bake for 8 minutes, then rotate the tray and bake for 3 minutes (11 minutes in total). SMALL COOKIES: Bake 6 minutes, turn then bake 3 minutes (9 min total). The cookies should be just golden on the edges and pale golden on top. They will be slightly puffed up."
      },
      {
        "title": "Step 14",
        "description": "Cool on the tray - they finish cooking. They will lose the puffiness while resting. Dig in and get your cookie fix!"
      }
    ],
    "sourceUrl": "https://www.recipetineats.com/chocolate-chip-cookies/",
    "addedAt": 1782567803366
  },
  {
    "id": "2",
    "title": "My Favorite Banana Bread",
    "description": "With its super-moist and buttery texture, banana and brown sugar flavors, soft crumb, and 1,000+ reviews, this is a delicious AND undeniably popular banana bread recipe. You need 4 large ripe bananas.",
    "image": "/recipe-images/recipe-2.jpg",
    "difficulty": "Advanced",
    "time": "3 hr",
    "prepTime": "10 mins",
    "bakeTime": "1 hr 5 mins",
    "yields": "1",
    "category": "Bread",
    "tags": [
      "imported",
      "web",
      "banana bread",
      "bread",
      "american",
      "sallysbakingaddiction.com"
    ],
    "ingredients": [
      {
        "amount": "2 cups",
        "name": "(250g) all-purpose flour (spooned & leveled)"
      },
      {
        "amount": "1 teaspoon",
        "name": "baking soda"
      },
      {
        "amount": "1/4 teaspoon",
        "name": "salt"
      },
      {
        "amount": "1/2 teaspoon",
        "name": "ground cinnamon"
      },
      {
        "amount": "1/2 cup",
        "name": "(8 Tbsp; 113g) unsalted butter, softened to room temperature"
      },
      {
        "amount": "3/4 cup",
        "name": "(150g) packed light or dark brown sugar"
      },
      {
        "amount": "2",
        "name": "large eggs, at room temperature"
      },
      {
        "amount": "1",
        "name": "and 1/2 cups (345g) mashed bananas (about 3–4 ripe bananas)"
      },
      {
        "amount": "1/3 cup",
        "name": "(80g) plain Greek yogurt or full-fat sour cream, at room temperature"
      },
      {
        "amount": "1 teaspoon",
        "name": "pure vanilla extract"
      },
      {
        "amount": "",
        "name": "optional: 3/4 cup (90g) chopped pecans or walnuts, or 1 cup (180g) semi-sweet chocolate chips"
      }
    ],
    "steps": [
      {
        "title": "Step 1",
        "description": "Adjust the oven rack to the lower third position and preheat the oven to 350°F (177°C). Lowering the oven rack prevents the top of your bread from browning too much, too soon. Grease a 9×5-inch loaf pan with nonstick spray. Set aside."
      },
      {
        "title": "Step 2",
        "description": "In a medium bowl, whisk the flour, baking soda, salt, and cinnamon together. Set aside."
      },
      {
        "title": "Step 3",
        "description": "In a large bowl using a handheld or stand mixer fitted with a paddle attachment, beat the butter and brown sugar together on medium-high speed until light and creamy, about 3 minutes. (Here’s a helpful tutorial if you need guidance on how to cream butter and sugar.) With the mixer running on medium speed, add the eggs one at a time, beating well after each addition. Scrape down the sides of the bowl as needed. Beat in the mashed bananas, yogurt/sour cream, and vanilla until combined."
      },
      {
        "title": "Step 4",
        "description": "Add the dry ingredients into the wet ingredients and beat on low speed just until combined. Do not over-mix. Fold in the nuts/chocolate chips, if using. The batter should be thick."
      },
      {
        "title": "Step 5",
        "description": "Pour and spread the batter into the prepared baking pan. Bake for 60–65 minutes, making sure to loosely cover the pan with aluminum foil halfway through, to prevent the top from getting too brown. The bread is done when a toothpick inserted in the center comes out clean with only a few small moist crumbs. Cool the bread in the pan set on a cooling rack for 1 hour. Remove the bread from the pan and place it directly on the rack to cool completely before slicing and serving."
      },
      {
        "title": "Step 6",
        "description": "Store wrapped tightly at room temperature for up to 3 days or in the refrigerator for up to 1 week."
      }
    ],
    "sourceUrl": "https://sallysbakingaddiction.com/best-banana-bread-recipe/",
    "addedAt": 1782567803882
  },
  {
    "id": "3",
    "title": "Best ever chocolate brownies recipe",
    "description": "A super easy brownie recipe for a squidgy chocolate bake. Watch our foolproof recipe video to help you get a perfect traybake every time.",
    "image": "/recipe-images/recipe-3.jpg",
    "difficulty": "Expert",
    "time": "1 hr",
    "prepTime": "25 mins",
    "bakeTime": "35 mins",
    "yields": "Cuts into 16 squares or 32 triangles",
    "category": "Afternoon tea, Dessert, Treat",
    "tags": [
      "imported",
      "web",
      "best",
      "best-ever",
      "brownies",
      "chocolate",
      "cocoa powder",
      "dark chocolate",
      "ever",
      "golden caster sugar",
      "large egg",
      "large eggs"
    ],
    "ingredients": [
      {
        "amount": "185g",
        "name": "unsalted butter"
      },
      {
        "amount": "185g",
        "name": "best dark chocolate"
      },
      {
        "amount": "85g",
        "name": "plain flour"
      },
      {
        "amount": "40g",
        "name": "cocoa powder"
      },
      {
        "amount": "50g",
        "name": "white chocolate"
      },
      {
        "amount": "50g",
        "name": "milk chocolate"
      },
      {
        "amount": "3",
        "name": "large eggs"
      },
      {
        "amount": "275g",
        "name": "golden caster sugar"
      }
    ],
    "steps": [
      {
        "title": "Step 1",
        "description": "Cut 185g unsalted butter into small cubes and tip into a medium bowl. Break 185g dark chocolate into small pieces and drop into the bowl."
      },
      {
        "title": "Step 2",
        "description": "Fill a small saucepan about a quarter full with hot water, then sit the bowl on top so it rests on the rim of the pan, not touching the water. Put over a low heat until the butter and chocolate have melted, stirring occasionally to mix them."
      },
      {
        "title": "Step 3",
        "description": "Remove the bowl from the pan. Alternatively, cover the bowl loosely with cling film and put in the microwave for 2 minutes on High. Leave the melted mixture to cool to room temperature."
      },
      {
        "title": "Step 4",
        "description": "While you wait for the chocolate to cool, position a shelf in the middle of your oven and turn the oven on to 180C/160C fan/gas 4."
      },
      {
        "title": "Step 5",
        "description": "Using a shallow 20cm square tin, cut out a square of kitchen foil (or non-stick baking parchment) to line the base. Tip 85g plain flour and 40g cocoa powder into a sieve held over a medium bowl. Tap and shake the sieve so they run through together and you get rid of any lumps."
      },
      {
        "title": "Step 6",
        "description": "Chop 50g white chocolate and 50g milk chocolate into chunks on a board."
      },
      {
        "title": "Step 7",
        "description": "Break 3 large eggs into a large bowl and tip in 275g golden caster sugar. With an electric mixer on maximum speed, whisk the eggs and sugar. They will look thick and creamy, like a milk shake. This can take 3-8 minutes, depending on how powerful your mixer is. You’ll know it’s ready when the mixture becomes really pale and about double its original volume. Another check is to turn off the mixer, lift out the beaters and wiggle them from side to side. If the mixture that runs off the beaters leaves a trail on the surface of the mixture in the bowl for a second or two, you’re there."
      },
      {
        "title": "Step 8",
        "description": "Pour the cooled chocolate mixture over the eggy mousse, then gently fold together with a rubber spatula. Plunge the spatula in at one side, take it underneath and bring it up the opposite side and in again at the middle. Continue going under and over in a figure of eight, moving the bowl round after each folding so you can get at it from all sides, until the two mixtures are one and the colour is a mottled dark brown. The idea is to marry them without knocking out the air, so be as gentle and slow as you like."
      },
      {
        "title": "Step 9",
        "description": "Hold the sieve over the bowl of eggy chocolate mixture and resift the cocoa and flour mixture, shaking the sieve from side to side, to cover the top evenly."
      },
      {
        "title": "Step 10",
        "description": "Gently fold in this powder using the same figure of eight action as before. The mixture will look dry and dusty at first, and a bit unpromising, but if you keep going very gently and patiently, it will end up looking gungy and fudgy. Stop just before you feel you should, as you don’t want to overdo this mixing."
      },
      {
        "title": "Step 11",
        "description": "Finally, stir in the white and milk chocolate chunks until they’re dotted throughout."
      },
      {
        "title": "Step 12",
        "description": "Pour the mixture into the prepared tin, scraping every bit out of the bowl with the spatula. Gently ease the mixture into the corners of the tin and paddle the spatula from side to side across the top to level it."
      },
      {
        "title": "Step 13",
        "description": "Put in the oven and set your timer for 25 mins. When the buzzer goes, open the oven, pull the shelf out a bit and gently shake the tin. If the brownie wobbles in the middle, it’s not quite done, so slide it back in and bake for another 5 minutes until the top has a shiny, papery crust and the sides are just beginning to come away from the tin. Take out of the oven."
      },
      {
        "title": "Step 14",
        "description": "Leave the whole thing in the tin until completely cold, then, if you’re using the brownie tin, lift up the protruding rim slightly and slide the uncut brownie out on its base. If you’re using a normal tin, lift out the brownie with the foil (or parchment). Cut into quarters, then cut each quarter into four squares and finally into triangles."
      },
      {
        "title": "Step 15",
        "description": "They’ll keep in an airtight container for a good two weeks and in the freezer for up to a month."
      }
    ],
    "sourceUrl": "https://www.bbcgoodfood.com/recipes/best-ever-chocolate-brownies-recipe",
    "addedAt": 1782567804396
  },
  {
    "id": "4",
    "title": "Classic Victoria sandwich recipe",
    "description": "The perfect party cake, a Victoria sponge is a traditional bake everyone will love. Makes an easy wedding cake, too",
    "image": "/recipe-images/recipe-4.jpg",
    "difficulty": "Advanced",
    "time": "1 hr",
    "prepTime": "40 mins",
    "bakeTime": "20 mins",
    "yields": "Cuts into 10 slices",
    "category": "Afternoon tea, Buffet, Supper, Treat",
    "tags": [
      "imported",
      "web",
      "bbc good food",
      "birthday cake",
      "cake",
      "classic",
      "classic sponge",
      "eggs",
      "good food",
      "indulgent",
      "jam",
      "mother"
    ],
    "ingredients": [
      {
        "amount": "200g",
        "name": "caster sugar"
      },
      {
        "amount": "200g",
        "name": "softened butter"
      },
      {
        "amount": "4",
        "name": "eggs beaten"
      },
      {
        "amount": "200g",
        "name": "self-raising flour"
      },
      {
        "amount": "1 tsp",
        "name": "baking powder"
      },
      {
        "amount": "2 tbsp",
        "name": "milk"
      },
      {
        "amount": "100g",
        "name": "butter softened"
      },
      {
        "amount": "140g",
        "name": "icing sugar sifted"
      },
      {
        "amount": "",
        "name": "drop vanilla extract (optional)"
      },
      {
        "amount": "",
        "name": "half a 340g jar good-quality strawberry jam"
      },
      {
        "amount": "",
        "name": "icing sugar to decorate"
      }
    ],
    "steps": [
      {
        "title": "Step 1",
        "description": "Heat oven to 190C/fan 170C/gas 5. Butter two 20cm sandwich tins and line with non-stick baking paper."
      },
      {
        "title": "Step 2",
        "description": "In a large bowl, beat 200g caster sugar, 200g softened butter, 4 beaten eggs, 200g self-raising flour, 1 tsp baking powder and 2 tbsp milk together until you have a smooth, soft batter."
      },
      {
        "title": "Step 3",
        "description": "Divide the mixture between the tins, smooth the surface with a spatula or the back of a spoon."
      },
      {
        "title": "Step 4",
        "description": "Bake for about 20 mins until golden and the cake springs back when pressed."
      },
      {
        "title": "Step 5",
        "description": "Turn onto a cooling rack and leave to cool completely."
      },
      {
        "title": "Step 6",
        "description": "To make the filling, beat the 100g softened butter until smooth and creamy, then gradually beat in 140g sifted icing sugar and a drop of vanilla extract (if you’re using it)."
      },
      {
        "title": "Step 7",
        "description": "Spread the buttercream over the bottom of one of the sponges. Top it with 170g strawberry jam and sandwich the second sponge on top."
      },
      {
        "title": "Step 8",
        "description": "Dust with a little icing sugar before serving. Keep in an airtight container and eat within 2 days."
      }
    ],
    "sourceUrl": "https://www.bbcgoodfood.com/recipes/classic-victoria-sandwich-recipe",
    "addedAt": 1782567804821
  },
  {
    "id": "5",
    "title": "Apple Pie Baked Apples",
    "description": "Everything you love about apple pie—the gooey cinnamon filling, the warm apples, the buttery homemade pie crust—all baked inside an apple. These apple pie baked apples are a fun and festive dessert that everyone will love.",
    "image": "/recipe-images/recipe-5.jpg",
    "difficulty": "Advanced",
    "time": "2 hr",
    "prepTime": "45 mins",
    "bakeTime": "25 mins",
    "yields": "4",
    "category": "Pie",
    "tags": [
      "imported",
      "web",
      "apple pie baked apples",
      "baked apples",
      "pie",
      "american",
      "sallysbakingaddiction.com"
    ],
    "ingredients": [
      {
        "amount": "1/2",
        "name": "recipe homemade pie crust*"
      },
      {
        "amount": "1 teaspoon",
        "name": "cornstarch"
      },
      {
        "amount": "1 Tablespoon",
        "name": "(15ml) warm water"
      },
      {
        "amount": "5",
        "name": "large, perfectly round and firm apples (I prefer Granny Smith or Honeycrisp)"
      },
      {
        "amount": "1 teaspoon",
        "name": "ground cinnamon"
      },
      {
        "amount": "1/2 cup",
        "name": "(100g) granulated sugar"
      },
      {
        "amount": "1 teaspoon",
        "name": "pure vanilla extract"
      },
      {
        "amount": "1",
        "name": "large egg"
      },
      {
        "amount": "1 teaspoon",
        "name": "milk"
      },
      {
        "amount": "",
        "name": "optional: homemade salted caramel sauce, for drizzling"
      }
    ],
    "steps": [
      {
        "title": "Step 1",
        "description": "Prepare the pie crust, including allowing it to chill for at least 2 hours. I usually prepare it the night before and leave it in the refrigerator until the next day when it’s time to begin the apples. The colder the pie crust, the better."
      },
      {
        "title": "Step 2",
        "description": "In a very small bowl, mix the cornstarch and warm water together until smooth, creamy, and the cornstarch has dissolved. Set aside. Peel and dice 1 apple. In a medium saucepan over medium heat, cook the apple pieces, cornstarch/water mixture, cinnamon, and sugar. Stir constantly for 5 minutes. Switch to low heat and allow to simmer for 5 minutes. Remove from heat, stir in the vanilla, and allow to cool off for 20 minutes."
      },
      {
        "title": "Step 3",
        "description": "On a floured work surface, roll out the pie dough. Turn the dough about a quarter turn after every few rolls until you have a circle 10-11 inches in diameter. Cut into fourths, as if you were cutting a pizza. (Pizza cutter works best here!) Then, cut each quarter into 1/4-inch wide strips. I like to chill the strips as I cut out the apples. I suggest putting them on a large cutting board and placing in the fridge. Remember, you always want your pie dough to be COLD."
      },
      {
        "title": "Step 4",
        "description": "Preheat oven to 375°F (191°C)."
      },
      {
        "title": "Step 5",
        "description": "Slice off the tops of the 4 remaining apples. Using a spoon (or melon baller), dig out the core. It doesn’t have to look perfect. Spoon the prepared apple filling into the cored-out apples. You may have some filling leftover—it’s great warmed up over vanilla ice cream. Lay 3-4 strips of the pie dough on top of the apple. Then, working with one new strip at a time, alternate weaving it over and under the dough strips already in place. Repeat until the top of the apple has been covered in this lattice style crust. Using a sharp paring knife, trim excess pie crust around the edges. Repeat with remaining apples and pie dough strips."
      },
      {
        "title": "Step 6",
        "description": "Place apples into an 8-inch square baking pan, 9-inch square baking pan or 9-inch pie dish—really any size baking pan works. In a small dish, whisk the egg and milk together. Lightly brush the tops with egg wash. I sprinkled a little bit of cinnamon on top of the egg wash before going into the oven—this is optional. Bake for 25-30 minutes or until the crust is browned and the filling is bubbly."
      },
      {
        "title": "Step 7",
        "description": "If desired, drizzle each with salted caramel. We ate ours with a knife and fork and vanilla ice cream on the side. These apples are best enjoyed immediately. Store any leftovers in the refrigerator for up to 2 days."
      }
    ],
    "sourceUrl": "https://sallysbakingaddiction.com/apple-pie-baked-apples/",
    "addedAt": 1782567805318
  },
  {
    "id": "6",
    "title": "Homemade Bagels Recipe",
    "description": "Make fresh bagels right at home with this tested dough recipe. Don't skip the water bath and egg wash—both provide an extra chewy and golden brown crust. This recipe is also in my cookbook, Sally's Baking 101.",
    "image": "/recipe-images/recipe-6.jpg",
    "difficulty": "Advanced",
    "time": "3 hr",
    "prepTime": "2 hr 10 mins",
    "bakeTime": "25 mins",
    "yields": "8",
    "category": "Bread",
    "tags": [
      "imported",
      "web",
      "homemade bagels recipe",
      "bread",
      "american",
      "sallysbakingaddiction.com"
    ],
    "ingredients": [
      {
        "amount": "1",
        "name": "and 1/2 cups (360g/ml) warm water (between 100–110°F/38–43°C)"
      },
      {
        "amount": "2",
        "name": "and 3/4 teaspoons (8g) instant or active dry yeast*"
      },
      {
        "amount": "1 Tablespoon",
        "name": "barley malt syrup, granulated sugar, or brown sugar*"
      },
      {
        "amount": "4 cups",
        "name": "(520g) bread flour (spooned & leveled), plus more as needed*"
      },
      {
        "amount": "2 teaspoons",
        "name": "salt"
      },
      {
        "amount": "",
        "name": "for coating the bowl: nonstick spray, butter, or oil"
      },
      {
        "amount": "2",
        "name": "quarts (1.9L) water"
      },
      {
        "amount": "1/4 cup",
        "name": "(85g) barley malt syrup or honey"
      },
      {
        "amount": "",
        "name": "egg wash: 1 egg white beaten with 1 Tablespoon water"
      }
    ],
    "steps": [
      {
        "title": "Step 1",
        "description": "In the bowl of a stand mixer fitted with a dough hook attachment, whisk the warm water, barley malt syrup/sugar, and yeast together. Cover and allow to sit for 5 minutes. *If you don’t have a stand mixer, use a large mixing bowl and mix the dough with a wooden spoon or silicone spatula in the next step.*"
      },
      {
        "title": "Step 2",
        "description": "Add the flour and salt, and beat on medium speed for 2 minutes, until the dough comes together and pulls away from the sides of the bowl. If it seems too sticky and clings to the sides of the bowl instead of forming a rough mass around the dough hook or spoon, add more flour, 1 Tablespoon at a time, and continue to mix until the dough pulls away from the sides of the bowl. The dough should be stiff and somewhat dry. If it is crumbly and breaks off in pieces, add more water, 1 teaspoon at a time, mixing well after each addition."
      },
      {
        "title": "Step 3",
        "description": "When the dough has reached the proper consistency, beat on low speed with the dough hook for an additional 6–7 minutes, or knead by hand on a lightly floured surface for 6–7 minutes, until the dough feels smooth, supple, and elastic. (If you’re new to bread-making, my How to Knead Dough video tutorial can help here.) If the dough becomes too sticky during the kneading process, sprinkle 1 teaspoon of flour at a time on the dough or on the work surface/in the bowl to make a soft, slightly tacky dough. Do not add more flour than you need because you do not want a dry dough. After kneading, the dough should still feel a little soft. Poke it with your finger—if it slowly bounces back, your dough is ready to rise. You can also do a “windowpane test” to see if your dough has been kneaded long enough: tear off a small (roughly golfball-size) piece of dough and gently stretch it out until it’s thin enough for light to pass through it. Hold it up to a window or light. Does light pass through the stretched dough without the dough tearing first? If so, your dough has been kneaded long enough and is ready to rise. If not, keep kneading until it passes the windowpane test."
      },
      {
        "title": "Step 4",
        "description": "Lightly grease a large bowl with nonstick spray, butter, or oil. Place the dough in the bowl, turning it to coat all sides in the oil. Cover the bowl with plastic wrap or a clean kitchen towel. Allow the dough to rise at room temperature for 1.5–2 hours, or until doubled in size."
      },
      {
        "title": "Step 5",
        "description": "Line two large baking sheets with parchment paper or silicone baking mats."
      },
      {
        "title": "Step 6",
        "description": "When the dough is risen, punch it down to release the air. On a lightly floured surface, divide the dough into 8 equal pieces, about 4 ounces (113g) each. Shape each piece into a ball. Press your index finger through the center of each ball to make a hole, then stretch and widen the hole to about 1.5–2 inches in diameter. Arrange the shaped bagels on the prepared baking sheets. Loosely cover the shaped bagels with a kitchen towel or plastic wrap and let them rest for 5–10 minutes as you prepare the water bath."
      },
      {
        "title": "Step 7",
        "description": "Preheat the oven to 425°F (218°C)."
      },
      {
        "title": "Step 8",
        "description": "Fill a large, wide pot with 2 quarts (1.9L) of water. Whisk in the barley malt syrup or honey. Bring to a boil over high heat, then reduce heat to medium-high. Drop 2 or 3 bagels in at a time, making sure they have enough room to float around. Boil the bagels for 1 minute, then use a spatula to flip each bagel over and boil for 1 minute more. Using a slotted metal spatula, lift the bagels out of the water, letting the excess water drain off. Place the bagels back on the lined baking sheets. Repeat with remaining bagels."
      },
      {
        "title": "Step 9",
        "description": "Using a pastry brush, brush the egg wash on top and around the sides of each bagel. If you’re adding toppings, dip the tops of the bagels into the toppings immediately after applying the egg wash."
      },
      {
        "title": "Step 10",
        "description": "Bake for 20–25 minutes, rotating the pans halfway through, until the bagels are dark golden brown. Allow the bagels to cool on the baking sheets for 20 minutes, then transfer to a cooling rack to cool completely."
      },
      {
        "title": "Step 11",
        "description": "Slice, toast, top, enjoy however you want! Cover leftover bagels tightly and store at room temperature for up to 4 days or in the refrigerator for up to 1 week."
      }
    ],
    "sourceUrl": "https://sallysbakingaddiction.com/homemade-bagels/",
    "addedAt": 1782567805783
  },
  {
    "id": "7",
    "title": "How to Make Perfect Scones",
    "description": "Use this basic scone dough for any sweet scone variety. See blog post for a couple savory scone options. Feel free to increase the vanilla extract and/or add other flavor extracts such as lemon extract or coconut extract.",
    "image": "/recipe-images/recipe-7.jpg",
    "difficulty": "Advanced",
    "time": "1 hr",
    "prepTime": "30 mins",
    "bakeTime": "25 mins",
    "yields": "8",
    "category": "Breakfast",
    "tags": [
      "imported",
      "web",
      "scones",
      "breakfast",
      "american",
      "sallysbakingaddiction.com"
    ],
    "ingredients": [
      {
        "amount": "2 cups",
        "name": "(250g) all-purpose flour (spooned & leveled), plus more for hands and work surface"
      },
      {
        "amount": "1/2 cup",
        "name": "(100g) granulated sugar"
      },
      {
        "amount": "1/2 teaspoon",
        "name": "salt"
      },
      {
        "amount": "2",
        "name": "and 1/2 teaspoons baking powder"
      },
      {
        "amount": "1/2 cup",
        "name": "(8 Tbsp; 113g) unsalted butter, frozen"
      },
      {
        "amount": "1/2 cup",
        "name": "(120ml) heavy cream or buttermilk (plus 2 Tbsp for brushing)"
      },
      {
        "amount": "1",
        "name": "large egg"
      },
      {
        "amount": "1",
        "name": "and 1/2 teaspoons pure vanilla extract"
      },
      {
        "amount": "",
        "name": "1-1.5 cups add-ins such as chocolate chips, berries, nuts, fruit, etc"
      },
      {
        "amount": "",
        "name": "optional: coarse sugar for topping"
      }
    ],
    "steps": [
      {
        "title": "Step 1",
        "description": "Whisk flour, sugar, salt, and baking powder together in a large bowl. Grate the frozen butter using a box grater. Add it to the flour mixture and combine with a pastry cutter, two forks, or your fingers until the mixture comes together in pea-sized crumbs. See video above for a closer look at the texture. Place in the refrigerator or freezer as you mix the wet ingredients together."
      },
      {
        "title": "Step 2",
        "description": "Whisk 1/2 cup heavy cream, the egg, and vanilla extract together in a small bowl. Drizzle over the flour mixture, add the add-ins, then mix together until everything appears moistened."
      },
      {
        "title": "Step 3",
        "description": "Pour onto the counter and, with floured hands, work dough into a ball as best you can. Dough will be sticky. If it’s too sticky, add a little more flour. If it seems too dry, add 1-2 more Tablespoons heavy cream. Press into an 8-inch disc and, with a sharp knife or bench scraper, cut into 8 wedges. For smaller scones, press dough into two 5-inch discs and cut each into 8 wedges. To make 10-12 drop scones: Keep mixing dough in the bowl until it comes together. Drop scones, about 1/4 cup of dough each, 3 inches apart on a lined baking sheet. To make mini (petite) scones, see recipe note."
      },
      {
        "title": "Step 4",
        "description": "Brush scones with remaining heavy cream and for extra crunch, sprinkle with coarse sugar. (You can do this before or after refrigerating in the next step.)"
      },
      {
        "title": "Step 5",
        "description": "Place scones on a plate or lined baking sheet (if your fridge has space!) and refrigerate for at least 15 minutes."
      },
      {
        "title": "Step 6",
        "description": "Meanwhile, preheat oven to 400°F (204°C)."
      },
      {
        "title": "Step 7",
        "description": "Line a large baking sheet with parchment paper or silicone baking mat(s). If making mini or drop scones, use 2 baking sheets. After refrigerating, arrange scones 2-3 inches apart on the prepared baking sheet(s)."
      },
      {
        "title": "Step 8",
        "description": "Bake for 18-26 minutes or until golden brown around the edges and lightly browned on top. Larger scones take closer to 25 minutes. Remove from the oven and cool for a few minutes. Feel free to top with any of the toppings listed in the recipe Note below."
      },
      {
        "title": "Step 9",
        "description": "Leftover scones keep well at room temperature for 2 days or in the refrigerator for 5 days."
      }
    ],
    "sourceUrl": "https://sallysbakingaddiction.com/scones-recipe/",
    "addedAt": 1782567806244
  },
  {
    "id": "8",
    "title": "Pizza Dough recipe",
    "description": "This pizza dough can be made by hand with 5 minutes of kneading, or in 40 seconds flat using a food processor (see 2nd recipe card below).",
    "image": "/recipe-images/recipe-8.jpg",
    "difficulty": "Advanced",
    "time": "1 hr",
    "prepTime": "30 mins",
    "bakeTime": "30 mins",
    "yields": "3",
    "category": "Mains",
    "tags": [
      "imported",
      "web",
      "easy pizza dough",
      "pizza dough",
      "mains",
      "italian",
      "recipetineats.com"
    ],
    "ingredients": [
      {
        "amount": "600g",
        "name": "(4 cups) bread flour or pizza flour ((or plain/all purpose) (Note 1))"
      },
      {
        "amount": "2 tsp",
        "name": "(6g) rapid rise or instant yeast ((Note 2))"
      },
      {
        "amount": "2 1/2 tsp",
        "name": "/ 15g salt (, kosher / cooking salt (Note 3))"
      },
      {
        "amount": "4 tsp",
        "name": "/ 20g white sugar"
      },
      {
        "amount": "4 tbsp",
        "name": "extra virgin olive oil"
      },
      {
        "amount": "330 ml",
        "name": "(1 1/3 cups) warm tap water ((330g, Note 4))"
      },
      {
        "amount": "1 tbsp",
        "name": "Extra Flour"
      },
      {
        "amount": "2 tsp",
        "name": "Extra Olive Oil"
      },
      {
        "amount": "130g",
        "name": "/ 1 1/3 cups tightly packed mozzarella cheese, freshly grated (per pizza, (Note 8))"
      },
      {
        "amount": "1/4 cup",
        "name": "pizza sauce (per pizza)"
      },
      {
        "amount": "",
        "name": "Toppings of choice"
      }
    ],
    "steps": [
      {
        "title": "Step 1",
        "description": "Dough:"
      },
      {
        "title": "Step 2",
        "description": "Rise #1:"
      },
      {
        "title": "Step 3",
        "description": "Optional fridge - flavour development:"
      },
      {
        "title": "Step 4",
        "description": "Form small balls, Rise #2:"
      },
      {
        "title": "Step 5",
        "description": "Stretch pizza base:"
      },
      {
        "title": "Step 6",
        "description": "Topping / Cooking (work quickly!):"
      }
    ],
    "sourceUrl": "https://www.recipetineats.com/pizza-dough-recipe/",
    "addedAt": 1782567806671
  },
  {
    "id": "9",
    "title": "Fluffy Homemade Pancakes",
    "description": "This easy homemade pancake recipe makes the most delicious and fluffy stack of pancakes around! Perfect for a cozy weekend breakfast.",
    "image": "/recipe-images/recipe-9.jpg",
    "difficulty": "Advanced",
    "time": "45 mins",
    "prepTime": "10 mins",
    "bakeTime": "20 mins",
    "yields": "4",
    "category": "Breakfast",
    "tags": [
      "imported",
      "web",
      "fluffy pancakes",
      "homemade pancakes",
      "pancakes",
      "breakfast",
      "american",
      "budgetbytes.com"
    ],
    "ingredients": [
      {
        "amount": "1 cup",
        "name": "all-purpose flour (150g, $0.17*)"
      },
      {
        "amount": "1½ tsp",
        "name": "baking powder (8g, $0.07**)"
      },
      {
        "amount": "½ tsp",
        "name": "salt (4g, $0.02)"
      },
      {
        "amount": "¾ cup",
        "name": "milk (warm, $0.15***)"
      },
      {
        "amount": "2 Tbsp",
        "name": "butter (melted, $0.19)"
      },
      {
        "amount": "1",
        "name": "large egg ($0.18)"
      },
      {
        "amount": "2 Tbsp",
        "name": "granulated sugar (25g, $0.04)"
      },
      {
        "amount": "½ tsp",
        "name": "vanilla extract ($0.25)"
      },
      {
        "amount": "4 tsp",
        "name": "cooking oil ($0.05****)"
      }
    ],
    "steps": [
      {
        "title": "Step 1",
        "description": "Gather and prepare all ingredients."
      },
      {
        "title": "Step 2",
        "description": "Whisk together the flour, baking powder, and salt in a medium-sized bowl."
      },
      {
        "title": "Step 3",
        "description": "In a separate medium-sized bowl, whisk together the milk, egg, melted butter, sugar, and vanilla extract."
      },
      {
        "title": "Step 4",
        "description": "Pour the wet ingredients into the bowl of dry ingredients and stir until just combined. DO NOT overmix. The batter should be thick yet still pourable, with a few lumps remaining. If it isn’t pourable, add an additional 1-2 tablespoons of milk until it reaches the right consistency. A batter that’s too thick can turn out slightly dry once cooked."
      },
      {
        "title": "Step 5",
        "description": "Next, let the batter rest for 15 minutes. This allows the flour to hydrate fully, relaxes the gluten, and activates the baking powder, resulting in tender, thicker, and more evenly cooked pancakes."
      },
      {
        "title": "Step 6",
        "description": "Heat a large skillet or griddle over medium. Once hot, add enough cooking oil to coat the surface (I use about ½ tsp per pancake). Add the batter to the hot griddle, ¼ cup at a time. Use the back of the measuring cup to spread the batter into a 4.5-inch diameter circle."
      },
      {
        "title": "Step 7",
        "description": "Cook until bubbles form over the surface and begin to pop, the edges look dry, and the bottom is golden brown, about 1-2 minutes. Flip them and cook on the second side until golden brown, for about 30 seconds."
      },
      {
        "title": "Step 8",
        "description": "Repeat with the remaining batter, adding more oil to the skillet between batches or as needed, until all the pancakes have been cooked. Keep them warm on a plate under a towel or in a warm oven until all the remaining batter is cooked. Serve warm with your favorite toppings!"
      }
    ],
    "sourceUrl": "https://www.budgetbytes.com/homemade-pancakes/",
    "addedAt": 1782567807176
  },
  {
    "id": "10",
    "title": "Shakshuka Recipe",
    "description": "Shakshuka is a classic North African and Middle Eastern breakfast dish. This recipe is simple and satisfying, featuring gently poached eggs in a bell pepper and tomato sauce.",
    "image": "/recipe-images/recipe-10.jpg",
    "difficulty": "Medium",
    "time": "35 mins",
    "prepTime": "10 mins",
    "bakeTime": "25 mins",
    "yields": "4",
    "category": "Breakfast",
    "tags": [
      "imported",
      "web",
      "shakshuka",
      "shakshuka recipe",
      "breakfast",
      "middle eastern",
      "loveandlemons.com"
    ],
    "ingredients": [
      {
        "amount": "2 tablespoons",
        "name": "extra-virgin olive oil"
      },
      {
        "amount": "1",
        "name": "small white onion (diced)"
      },
      {
        "amount": "1",
        "name": "red bell pepper (stemmed, seeded, and diced)"
      },
      {
        "amount": "3",
        "name": "garlic cloves (minced)"
      },
      {
        "amount": "1 teaspoon",
        "name": "ground cumin"
      },
      {
        "amount": "½ teaspoon",
        "name": "paprika"
      },
      {
        "amount": "",
        "name": "Pinch cayenne pepper (optional)"
      },
      {
        "amount": "1",
        "name": "(28-ounce) can fire-roasted crushed tomatoes"
      },
      {
        "amount": "½ teaspoon",
        "name": "sea salt (plus more to taste)"
      },
      {
        "amount": "",
        "name": "Freshly ground black pepper"
      },
      {
        "amount": "6",
        "name": "large eggs"
      },
      {
        "amount": "¼ cup",
        "name": "fresh parsley or cilantro leaves"
      },
      {
        "amount": "¼ cup",
        "name": "crumbled feta cheese"
      },
      {
        "amount": "",
        "name": "Pita (for serving)"
      }
    ],
    "steps": [
      {
        "title": "Step 1",
        "description": "Heat the olive oil in a large lidded skillet over medium heat. Add the onion and red peppers and cook for 5 to 8 minutes, or until softened. Add the garlic, cumin, paprika, and cayenne, if using, and cook, stirring, for 30 seconds, or until fragrant."
      },
      {
        "title": "Step 2",
        "description": "Add the tomatoes, salt, and several grinds of pepper. Simmer over low heat, stirring often, for 15 minutes, or until the sauce has thickened."
      },
      {
        "title": "Step 3",
        "description": "Make 6 wells in the sauce and crack one egg into each well. Cover and cook until the eggs are set, 4 to 8 minutes. The timing will depend on how runny or firm you like your eggs. Season to taste with salt and pepper and top with the parsley and feta. Serve with pita."
      }
    ],
    "sourceUrl": "https://www.loveandlemons.com/shakshuka-recipe/",
    "addedAt": 1782567807690
  },
  {
    "id": "11",
    "title": "Carbonara (real)",
    "description": "These days, so many carbonara recipes cheat with cream which is a shame. The traditional method uses raw egg which is mixed vigorously with hot pasta and parmigiana reggiano cheese which transforms into a silky, creamy, luxurious sauce…",
    "image": "/recipe-images/recipe-11.jpg",
    "difficulty": "Advanced",
    "time": "20 mins",
    "prepTime": "5 mins",
    "bakeTime": "15 mins",
    "yields": "4",
    "category": "Mains",
    "tags": [
      "imported",
      "web",
      "carbonara",
      "spaghetti alla carbonara",
      "mains",
      "italian",
      "recipetineats.com"
    ],
    "ingredients": [
      {
        "amount": "",
        "name": "175g/6 oz guanciale (pancetta or block bacon), ( weight after skin removed (Note 1))"
      },
      {
        "amount": "2",
        "name": "large eggs ((Note 2))"
      },
      {
        "amount": "2",
        "name": "egg yolks ((Note 2))"
      },
      {
        "amount": "",
        "name": "100g/3.5 oz parmigiano reggiano (, finely shredded (or pecorino romano, sub parmesan, Note 3))"
      },
      {
        "amount": "1/4 tsp",
        "name": "black pepper"
      },
      {
        "amount": "",
        "name": "400g/14 oz spaghetti"
      },
      {
        "amount": "1 tbsp",
        "name": "cooking/kosher salt ((for cooking pasta))"
      },
      {
        "amount": "1/2 cup",
        "name": "pasta cooking water"
      },
      {
        "amount": "1",
        "name": "garlic clove (, finely minced (optional, Note 4))"
      },
      {
        "amount": "",
        "name": "Parsley (, finely chopped)"
      },
      {
        "amount": "",
        "name": "Parmigiano reggiano"
      }
    ],
    "steps": [
      {
        "title": "Step 1",
        "description": "Guanciale - Cut into 0.5cm / 1/5\" thick slices then into batons."
      },
      {
        "title": "Step 2",
        "description": "Carbonara sauce - Place eggs and yolks in a large bowl. Whisk to combine. Then stir in the parmesan and pepper."
      },
      {
        "title": "Step 3",
        "description": "Cook pasta - Bring 4 litres (4 quarts) of water to the boil with the salt. Add pasta and cook per the packet directions."
      },
      {
        "title": "Step 4",
        "description": "Reserve pasta water - Just before draining, scoop out 1 cup of pasta cooking water, then drain the pasta."
      },
      {
        "title": "Step 5",
        "description": "Cook guanciale - While the pasta is cooking, place guanciale in a non stick pan over medium high heat. Cook for 4 to 5 minutes until golden. No oil needed - as the guanciale heats up, the fat will melt so it fries in its own fat. If using garlic, add it in the last minute."
      },
      {
        "title": "Step 6",
        "description": "Pasta in pan - Tip the hot pasta into the pan and toss to coat in guanciale fat."
      },
      {
        "title": "Step 7",
        "description": "Mix pasta in sauce - Transfer the pasta and any residual fat in the pan into the bowl with the egg. Add 1/2 cup (125 ml) pasta cooking water. Stir vigorously using the handle of a wooden spoon for 1 minute and watch as the sauce transforms from watery to creamy and clings to the pasta strands!"
      },
      {
        "title": "Step 8",
        "description": "Serve - Transfer into warm bowls. Serve immediately, garnished with a little extra parmigiana reggiano if desired, and a pinch of black pepper and finely chopped parsley."
      }
    ],
    "sourceUrl": "https://www.recipetineats.com/carbonara/",
    "addedAt": 1782567808121
  },
  {
    "id": "12",
    "title": "Spaghetti with Hidden Vegetable Pasta Sauce",
    "description": "Give your spaghetti an upgrade with this hidden vegetable pasta sauce that contains a medley of vegetables plus extra herbs and spices for maximum flavor.",
    "image": "/recipe-images/recipe-12.jpg",
    "difficulty": "Advanced",
    "time": "45 mins",
    "prepTime": "15 mins",
    "bakeTime": "30 mins",
    "yields": "4",
    "category": "Imported",
    "tags": [
      "imported",
      "web",
      "no tomato pasta sauce",
      "red sauce",
      "spaghetti sauce",
      "budgetbytes.com"
    ],
    "ingredients": [
      {
        "amount": "1",
        "name": "small zucchini ($0.57)"
      },
      {
        "amount": "2",
        "name": "carrots ($0.16)"
      },
      {
        "amount": "1",
        "name": "yellow onion ($0.25)"
      },
      {
        "amount": "2 cloves",
        "name": "garlic ($0.16)"
      },
      {
        "amount": "1 Tbsp",
        "name": "olive oil ($0.16)"
      },
      {
        "amount": "1/2",
        "name": "lb. ground beef ($2.50)"
      },
      {
        "amount": "1/2 tsp",
        "name": "dried basil ($0.05)"
      },
      {
        "amount": "1/2 tsp",
        "name": "dried oregano ($0.05)"
      },
      {
        "amount": "1/4 tsp",
        "name": "salt ($0.02)"
      },
      {
        "amount": "1/4 tsp",
        "name": "Freshly cracked black pepper ($0.03)"
      },
      {
        "amount": "1 pinch",
        "name": "crushed red pepper (optional) ($0.02)"
      },
      {
        "amount": "1",
        "name": "24oz. jar pasta sauce* ($1.49)"
      },
      {
        "amount": "12",
        "name": "oz. spaghetti ( $0.75)"
      }
    ],
    "steps": [
      {
        "title": "Step 1",
        "description": "Use a cheese grater to grate the zucchini and carrots. You'll want about 1.5 cups of each, but the amount is flexible. Dice the onion and mince the garlic."
      },
      {
        "title": "Step 2",
        "description": "Add the olive oil and ground beef to a large, deep skillet. Cook the ground beef over medium heat until it is fully browned. Add the diced onion and garlic and continue to sauté a few minutes more, or until the onions are soft and translucent."
      },
      {
        "title": "Step 3",
        "description": "Add the shredded zucchini and carrots to the skillet along with the basil, oregano, salt, freshly cracked pepper, and a pinch of red pepper. Continue to sauté until the vegetables are wilted (about five minutes)."
      },
      {
        "title": "Step 4",
        "description": "Add the pasta sauce to the skillet and stir to combine. Allow the contents of the skillet to come up to a simmer, then turn the heat down to low and simmer the sauce as you prepare the spaghetti. Stir the sauce occasionally as it simmers."
      },
      {
        "title": "Step 5",
        "description": "Cook the spaghetti according to the package directions, then drain in a colander. Return the drained spaghetti to the pot with the heat turned off. Add one cup of the prepared sauce to the pasta and stir to coat. Divide the pasta into serving bowls and top with additional sauce."
      }
    ],
    "sourceUrl": "https://www.budgetbytes.com/spaghetti-with-vegetable-meat-sauce/",
    "addedAt": 1782567808585
  },
  {
    "id": "13",
    "title": "Oven Baked Chicken and Rice",
    "description": "Made entirely in the oven (no stove!), the rice in this recipe is outrageously delicious! It's buttery and garlicky, tender but not mushy.",
    "image": "/recipe-images/recipe-13.jpg",
    "difficulty": "Advanced",
    "time": "1 hr 20 mins",
    "prepTime": "10 mins",
    "bakeTime": "1 hr 10 mins",
    "yields": "5",
    "category": "Dinner",
    "tags": [
      "imported",
      "web",
      "baked chicken thighs with rice",
      "chicken and rice",
      "chicken and rice recipe",
      "dinner",
      "western",
      "recipetineats.com"
    ],
    "ingredients": [
      {
        "amount": "5",
        "name": "bone in chicken thigh fillets, peel skin OFF (, (Note 1))"
      },
      {
        "amount": "1",
        "name": "onion (, chopped (brown, white or yellow))"
      },
      {
        "amount": "2 cloves",
        "name": "garlic (large) (, minced)"
      },
      {
        "amount": "2 tbsp",
        "name": "(30g) butter ((or olive oil))"
      },
      {
        "amount": "1 1/2 cups",
        "name": "(270g) uncooked white rice ((Note 3))"
      },
      {
        "amount": "1 1/2 cups",
        "name": "(375 ml) chicken broth/stock (, hot (I microwave))"
      },
      {
        "amount": "1 1/4 cups",
        "name": "(315 ml) water (, hot (tap is fine))"
      },
      {
        "amount": "1 tsp",
        "name": "paprika powder"
      },
      {
        "amount": "1 tsp",
        "name": "dried thyme"
      },
      {
        "amount": "1/2 tsp",
        "name": "garlic powder"
      },
      {
        "amount": "1/2 tsp",
        "name": "onion powder"
      },
      {
        "amount": "3/4 tsp",
        "name": "salt"
      },
      {
        "amount": "",
        "name": "Black pepper"
      },
      {
        "amount": "",
        "name": "Oil spray"
      },
      {
        "amount": "",
        "name": "Fresh thyme leaves or finely chopped parsley"
      }
    ],
    "steps": [
      {
        "title": "Step 1",
        "description": "Preheat oven to 180°C/350°F."
      },
      {
        "title": "Step 2",
        "description": "Scatter onion and garlic in a baking dish (about 10 x 15\" / 25 x 35 cm), then place butter in the centre. Bake for 15 minutes (check at 12 minutes, mix if some bits are browning too much)."
      },
      {
        "title": "Step 3",
        "description": "Meanwhile, mix together Chicken Rub. Sprinkle on both sides of the chicken."
      },
      {
        "title": "Step 4",
        "description": "Remove baking dish from the oven. Add rice then mix."
      },
      {
        "title": "Step 5",
        "description": "Place chicken on rice. Then pour chicken broth and water around the chicken."
      },
      {
        "title": "Step 6",
        "description": "Cover with foil, then bake for 30 minutes. Remove foil, spray chicken with oil (optional, gives chicken nicer finish), then bake for a further 20 minutes until liquid is absorbed."
      },
      {
        "title": "Step 7",
        "description": "Stand for 5 minutes, then remove chicken and fluff up rice. Garnish with parsley or thyme if desired, serve and enjoy!"
      },
      {
        "title": "Step 8",
        "description": "Optional gravy"
      }
    ],
    "sourceUrl": "https://www.recipetineats.com/oven-baked-chicken-and-rice/",
    "addedAt": 1782567809230
  },
  {
    "id": "14",
    "title": "Butter Chicken",
    "description": "This is a Chef recipe and is one of the easiest Indian curries to make. The Butter Chicken Sauce is so good that you will want it on tap!",
    "image": "/recipe-images/recipe-14.jpg",
    "difficulty": "Advanced",
    "time": "35 mins",
    "prepTime": "10 mins",
    "bakeTime": "25 mins",
    "yields": "3",
    "category": "Chicken",
    "tags": [
      "imported",
      "web",
      "butter chicken",
      "chicken",
      "indian",
      "recipetineats.com"
    ],
    "ingredients": [
      {
        "amount": "1/2 cup",
        "name": "plain yoghurt (, full fat)"
      },
      {
        "amount": "1 tbsp",
        "name": "lemon juice"
      },
      {
        "amount": "1 tsp",
        "name": "tumeric powder"
      },
      {
        "amount": "2 tsp",
        "name": "garam masala ((Note 1))"
      },
      {
        "amount": "1/2 tsp",
        "name": "chilli powder or cayenne pepper powder ((Note 2))"
      },
      {
        "amount": "1 tsp",
        "name": "ground cumin"
      },
      {
        "amount": "1 tbsp",
        "name": "ginger, freshly grated"
      },
      {
        "amount": "2 cloves",
        "name": "garlic, crushed"
      },
      {
        "amount": "1.5 lb",
        "name": "/ 750 g chicken thigh fillets, cut into bite size pieces"
      },
      {
        "amount": "2 tbsp",
        "name": "(30 g) ghee or butter, ( OR 1 tbsp vegetable oil (Note 3))"
      },
      {
        "amount": "1 cup",
        "name": "tomato passata (aka tomato puree) ((Note 4))"
      },
      {
        "amount": "1 cup",
        "name": "heavy / thickened cream ((Note 5))"
      },
      {
        "amount": "1 tbsp",
        "name": "sugar"
      },
      {
        "amount": "1 1/4 tsp",
        "name": "salt"
      },
      {
        "amount": "",
        "name": "Basmati rice"
      },
      {
        "amount": "",
        "name": "White rice"
      },
      {
        "amount": "",
        "name": "Coriander/cilantro (optional)"
      }
    ],
    "steps": [
      {
        "title": "Step 1",
        "description": "Optional blitz: for an extra smooth sauce, combine the Marinade ingredients (except the chicken) in a food processor and blend until smooth. (I do not do this)"
      },
      {
        "title": "Step 2",
        "description": "Marinade: Combine the Marinade ingredients with the chicken in a bowl. Cover and refrigerate overnight, or up to 24 hours (minimum 3 hrs)."
      },
      {
        "title": "Step 3",
        "description": "Cook chicken: Heat the ghee (butter or oil) over high heat in a large fry pan. Take the chicken out of the Marinade but do not wipe or shake off the marinade from the chicken (but don't pour the Marinade left in the bowl into the fry pan)."
      },
      {
        "title": "Step 4",
        "description": "Place chicken in the fry pan and cook for around 3 minutes, or until the chicken is white all over (it doesn't really brown because of the Marinade)."
      },
      {
        "title": "Step 5",
        "description": "Sauce: Add the tomato passata, cream, sugar and salt. Also add any remaining marinade left in the bowl. Turn down to low and simmer for 20 minutes. Do a taste test to see if it needs more salt."
      },
      {
        "title": "Step 6",
        "description": "Garnish with coriander/cilantro leaves if using. Serve with basmati rice."
      },
      {
        "title": "Step 7",
        "description": "The Butter Chicken is pictured with my very easy No Yeast Flatbread and no-fry papadums (Note 5)."
      }
    ],
    "sourceUrl": "https://www.recipetineats.com/butter-chicken/",
    "addedAt": 1782567809663
  },
  {
    "id": "15",
    "title": "Thai Green Curry",
    "description": "This is how to make a really great QUICK green curry by pimping up curry in a jar, OR using a homemade green curry paste! Don't skip frying off the curry paste, this makes all the difference.",
    "image": "/recipe-images/recipe-15.jpg",
    "difficulty": "Expert",
    "time": "35 mins",
    "prepTime": "15 mins",
    "bakeTime": "20 mins",
    "yields": "4",
    "category": "Mains",
    "tags": [
      "imported",
      "web",
      "green curry",
      "thai green curry",
      "mains",
      "thai",
      "recipetineats.com"
    ],
    "ingredients": [
      {
        "amount": "4",
        "name": "- 6 tbsp Thai Green Curry Paste (Maesri best) OR ((Note 1))"
      },
      {
        "amount": "1",
        "name": "quantity homemade green curry paste ((Note 1))"
      },
      {
        "amount": "2",
        "name": "large garlic cloves (, minced)"
      },
      {
        "amount": "2 tsp",
        "name": "fresh ginger (, finely grated)"
      },
      {
        "amount": "1 tbsp",
        "name": "lemongrass paste ((Note 2))"
      },
      {
        "amount": "2 tbsp",
        "name": "vegetable oil"
      },
      {
        "amount": "1 cup",
        "name": "(250ml) chicken or vegetable broth, low sodium"
      },
      {
        "amount": "400",
        "name": "g/14oz coconut milk (, full fat (Note 4))"
      },
      {
        "amount": "1",
        "name": "- 3 tsp fish sauce *"
      },
      {
        "amount": "1",
        "name": "- 3 tsp white sugar *"
      },
      {
        "amount": "1/8 tsp",
        "name": "salt *"
      },
      {
        "amount": "6",
        "name": "kaffir lime leaves (, torn in half (Note 5))"
      },
      {
        "amount": "350",
        "name": "g/12 oz chicken thigh (, skinless boneless, sliced (Note 6))"
      },
      {
        "amount": "2",
        "name": "Japanese eggplants, (, small, 1cm / 2/5\" slices (Note 7))"
      },
      {
        "amount": "1 1/2 cups",
        "name": "snow peas (, small, trimmed)"
      },
      {
        "amount": "16",
        "name": "Thai basil leaves ((Note 8))"
      },
      {
        "amount": "",
        "name": "Juice of 1/2 lime (, to taste)"
      },
      {
        "amount": "",
        "name": "Crispy fried Asian shallots (, high recommended (Note 9))"
      },
      {
        "amount": "",
        "name": "Thai basil or cilantro/coriander (, recommended)"
      },
      {
        "amount": "",
        "name": "Green or red chillies slices (, optional)"
      },
      {
        "amount": "",
        "name": "Steamed jasmine rice"
      }
    ],
    "steps": [
      {
        "title": "Step 1",
        "description": "Heat oil in a heavy based skillet or pot over medium high heat."
      },
      {
        "title": "Step 2",
        "description": "Add curry paste (and garlic, ginger and lemongrass Extras, if using) and cook for 2 to 3 minutes until it mostly \"dries out\" - see video. Don't breath in the fumes!!"
      },
      {
        "title": "Step 3",
        "description": "Add chicken broth and coconut milk, mix to dissolve paste."
      },
      {
        "title": "Step 4",
        "description": "Curry in a jar seasonings: Add 1 tsp fish sauce, 1 tsp sugar, no salt."
      },
      {
        "title": "Step 5",
        "description": "Homemade curry paste seasonings: Add 3 tsp fish sauce, 3 tsp sugar, 1/8 tsp salt."
      },
      {
        "title": "Step 6",
        "description": "Add kaffir lime leaves. Mix then bring to simmer."
      },
      {
        "title": "Step 7",
        "description": "Add chicken, stir then lower heat to medium so it's bubbling gently. Cook 7 minutes."
      },
      {
        "title": "Step 8",
        "description": "Add eggplants, cook 5 minutes until soft."
      },
      {
        "title": "Step 9",
        "description": "Taste sauce. Add fish sauce or salt for more saltiness, sugar for sweetness."
      },
      {
        "title": "Step 10",
        "description": "Add snow peas, cook 2 minutes until a bit softened, then stir through basil and lime juice. Sauce should have reduced but will still be a be on the thin side, not thick - that's how it's should be. DO NOT keep simmering - sauce will darken."
      },
      {
        "title": "Step 11",
        "description": "Serve curry over jasmine rice with garnishes of choice."
      }
    ],
    "sourceUrl": "https://www.recipetineats.com/thai-green-curry/",
    "addedAt": 1782567810101
  },
  {
    "id": "16",
    "title": "12 Minute Baked Salmon Fajitas",
    "description": "Here is a big Fajita dinner spread that's all cooked in the oven at the same time!",
    "image": "/recipe-images/recipe-16.jpg",
    "difficulty": "Advanced",
    "time": "30 mins",
    "prepTime": "18 mins",
    "bakeTime": "12 mins",
    "yields": "4",
    "category": "Dinner",
    "tags": [
      "imported",
      "web",
      "baked fajitas",
      "baked salmon recipe",
      "salmon fajitas",
      "salmon recipe",
      "tray bake dinner",
      "tray bake recipe",
      "dinner",
      "mexican",
      "recipetineats.com"
    ],
    "ingredients": [
      {
        "amount": "600g",
        "name": "/ 1.2lb skinless salmon fillets (, cut into 2.5cm/1\" cubes (Note 1))"
      },
      {
        "amount": "1 1/2 tbsp",
        "name": "extra virgin olive oil"
      },
      {
        "amount": "2 tsp",
        "name": "smoked paprika ((or regular paprika))"
      },
      {
        "amount": "1 tsp",
        "name": "EACH garlic, onion, cumin powder"
      },
      {
        "amount": "1/2 tsp",
        "name": "dried oregano"
      },
      {
        "amount": "3/4 tsp",
        "name": "cooking salt / kosher salt ((halve for cooking salt, double for flakes))"
      },
      {
        "amount": "1 tsp",
        "name": "(tightly packed) brown sugar ((helps the salmon brown!))"
      },
      {
        "amount": "1/4 tsp",
        "name": "cayenne pepper ((optional), for small spiciness)"
      },
      {
        "amount": "3",
        "name": "capsicums (1 each red, yellow, green) (, deseeded, cut into 0.75cm / 1/3\" strips)"
      },
      {
        "amount": "1",
        "name": "red onion (, cut into 0.75cm / 1/3\"wedges)"
      },
      {
        "amount": "1 1/2 tbsp",
        "name": "extra virgin olive oil"
      },
      {
        "amount": "1",
        "name": "garlic clove (, minced using garlic press or knife)"
      },
      {
        "amount": "1/2 tsp",
        "name": "cooking salt / kosher salt"
      },
      {
        "amount": "",
        "name": "Creamy Jalapeno Sauce"
      },
      {
        "amount": "",
        "name": "Pink Taco Sauce ((2 ingredients!))"
      },
      {
        "amount": "",
        "name": "Sour cream"
      },
      {
        "amount": "12",
        "name": "- 16 taco-size tortillas (, corn or flour (3 to 4 per person, depending on size), wrapped in foil (make 2 parcels))"
      },
      {
        "amount": "1",
        "name": "avocado (, sliced)"
      },
      {
        "amount": "2 tbsp",
        "name": "roughly chopped coriander ((cilantro), optional but recommended)"
      },
      {
        "amount": "",
        "name": "Lime wedges (, optional)"
      }
    ],
    "steps": [
      {
        "title": "Step 1",
        "description": "ABBREVIATED RECIPE"
      },
      {
        "title": "Step 2",
        "description": "FULL RECIPE"
      },
      {
        "title": "Step 3",
        "description": "SERVING"
      }
    ],
    "sourceUrl": "https://www.recipetineats.com/baked-salmon-fajita-spread/",
    "addedAt": 1782567810590
  },
  {
    "id": "17",
    "title": "Roast Chicken",
    "description": "Slathered with a garlic-herb-lemon butter, this roast chicken is juicy on the inside with crispy golden skin on the outside. An all round flavour bomb with the most incredible liquid gold pan juices to use as the sauce!",
    "image": "/recipe-images/recipe-17.jpg",
    "difficulty": "Expert",
    "time": "1 hr 45 mins",
    "prepTime": "15 mins",
    "bakeTime": "1 hr 30 mins",
    "yields": "5",
    "category": "Dinner",
    "tags": [
      "imported",
      "web",
      "roast chicken",
      "dinner",
      "recipetineats.com"
    ],
    "ingredients": [
      {
        "amount": "1.75",
        "name": "- 2 kg / 3.5 - 4lb whole chicken (, patted dry)"
      },
      {
        "amount": "",
        "name": "Salt and pepper"
      },
      {
        "amount": "2 tsp",
        "name": "olive oil"
      },
      {
        "amount": "1",
        "name": "lemon, quartered"
      },
      {
        "amount": "3",
        "name": "rosemary sprigs"
      },
      {
        "amount": "100 g",
        "name": "/ 1 stick unsalted butter (, melted)"
      },
      {
        "amount": "3",
        "name": "garlic cloves (, minced)"
      },
      {
        "amount": "1 tbsp",
        "name": "sage (, finely chopped (Note 1))"
      },
      {
        "amount": "2 tsp",
        "name": "rosemary (, finely chopped (Note 1))"
      },
      {
        "amount": "1 tbsp",
        "name": "parsley (, finely chopped (Note 1))"
      },
      {
        "amount": "1/2 tsp",
        "name": "each salt and black pepper"
      },
      {
        "amount": "1 cup",
        "name": "/ 250 ml dry white wine (, or low sodium chicken broth)"
      },
      {
        "amount": "1",
        "name": "onion (, quartered (Note 2))"
      },
      {
        "amount": "1",
        "name": "garlic bulb (, halved horizontally (Note 2))"
      }
    ],
    "steps": [
      {
        "title": "Step 1",
        "description": "Take the chicken out of the fridge 30 minutes before cooking."
      },
      {
        "title": "Step 2",
        "description": "Preheat oven to 220C/450F (standard) or 200C/430F (fan/convection). Put shelf in the middle."
      },
      {
        "title": "Step 3",
        "description": "Mix together Butter ingredients. Add juice from 2 wedges of lemon."
      },
      {
        "title": "Step 4",
        "description": "Place chicken in a roasting pan. Use a dessert spoon to loosen skin from chicken (see video). Do the top (the breast) and the drumsticks – not the underside."
      },
      {
        "title": "Step 5",
        "description": "Prop chicken upright, drizzle butter under skin, using most of the garlic/herb sludge, but saving a bit of butter for the skin (Note 3)."
      },
      {
        "title": "Step 6",
        "description": "Drizzle / smear remaining butter all over surface of the chicken. Squeeze over juice of 2 lemon wedges."
      },
      {
        "title": "Step 7",
        "description": "Stuff used lemon wedges and rosemary inside chicken."
      },
      {
        "title": "Step 8",
        "description": "Tie drumstick ends with string and tuck wing tips under the chicken."
      },
      {
        "title": "Step 9",
        "description": "Sprinkle all over with salt and pepper."
      },
      {
        "title": "Step 10",
        "description": "Place onion and garlic in the pan, place chicken on top. Pour wine around, drizzle chicken with oil."
      },
      {
        "title": "Step 11",
        "description": "Transfer to oven. Roast for 10 minutes, then turn oven down to 180C/350F (all oven types). Roast for a further 1 hr 15 minutes, or until the internal temperature is 75C/165F or until juices run clear when pierced at the join between the drumstick and the body. Baste twice (30 min then at 1 hr), spooning pan juices over skin."
      },
      {
        "title": "Step 12",
        "description": "Rest for 15 minutes – don’t cover, skin becomes wet."
      },
      {
        "title": "Step 13",
        "description": "Serve with pan juices (see video for how to carve). I discard onion but use the garlic in the pan. See notes for side suggestions & how to use carcass for incredible homemade broth!"
      }
    ],
    "sourceUrl": "https://www.recipetineats.com/roast-chicken/",
    "addedAt": 1782567811024
  },
  {
    "id": "18",
    "title": "Beef Stroganoff",
    "description": "Juicy strips of beef smothered in a sour cream mushroom gravy - a quick dinner everyone will love! KEY STEPS: Sear beef super quickly for maximum juiciness and use a large skillet (for quick sear + fast sauce reduction).",
    "image": "/recipe-images/recipe-18.jpg",
    "difficulty": "Expert",
    "time": "30 mins",
    "prepTime": "15 mins",
    "bakeTime": "15 mins",
    "yields": "4",
    "category": "Main",
    "tags": [
      "imported",
      "web",
      "beef stroganoff",
      "beef stroganoff recipe",
      "main",
      "russian",
      "recipetineats.com"
    ],
    "ingredients": [
      {
        "amount": "600 g",
        "name": "/ 1.2 lb scotch fillet steak / boneless rib eye ((Note 1))"
      },
      {
        "amount": "2 tbsp",
        "name": "vegetable oil (, divided)"
      },
      {
        "amount": "1",
        "name": "large onion ((or 2 small onions), sliced)"
      },
      {
        "amount": "300 g",
        "name": "/ 10 oz mushrooms (, sliced (not too thin))"
      },
      {
        "amount": "40 g",
        "name": "/ 3 tbsp butter"
      },
      {
        "amount": "2 tbsp",
        "name": "flour ((Note 2))"
      },
      {
        "amount": "2 cups",
        "name": "/ 500 ml beef broth (, preferably salt reduced)"
      },
      {
        "amount": "1 tbsp",
        "name": "Dijon mustard"
      },
      {
        "amount": "150 ml",
        "name": "/ 2/3 cup sour cream"
      },
      {
        "amount": "",
        "name": "Salt and pepper"
      },
      {
        "amount": "250",
        "name": "- 300 g / 8 - 10 oz pasta or egg noodles of choice ((Note 3))"
      },
      {
        "amount": "",
        "name": "Chopped chives (, for garnish (optional))"
      }
    ],
    "steps": [
      {
        "title": "Step 1",
        "description": "Use your fist (or rolling pin or mallet) to flatten the steaks to about 3/4cm / 1/3\" thick. Slice into 5mm / 1/5\" strips (cut long ones in half), discarding excess fat."
      },
      {
        "title": "Step 2",
        "description": "Sprinkle with a pinch of salt and pepper."
      },
      {
        "title": "Step 3",
        "description": "Heat 1 tbsp oil in a large skillet over high heat. Scatter half the beef in the skillet, QUICKLY spread it with tongs. Leave untouched for 30 seconds until browned. Turn beef quickly (as best you can!). Leave untouched for 30 seconds to brown. Immediately remove onto a plate. Don't worry about pink bits and that it will be raw inside."
      },
      {
        "title": "Step 4",
        "description": "Add remaining 1 tbsp oil and repeat with remaining beef."
      },
      {
        "title": "Step 5",
        "description": "Turn heat down to medium high. Add butter, melt. Then add onions, cook for 1 minute, then add mushrooms."
      },
      {
        "title": "Step 6",
        "description": "Cook mushrooms until golden. Scrape bottom of fry pan to get all the golden bits off (this is flavour!)."
      },
      {
        "title": "Step 7",
        "description": "Add flour, cook, stirring, for 1 minute."
      },
      {
        "title": "Step 8",
        "description": "Add half the broth while stirring. Once incorporated, add remaining broth."
      },
      {
        "title": "Step 9",
        "description": "Stir, then add sour cream and mustard. Stir until incorporated (don't worry if it looks split, sour cream will \"melt\" as it heats)."
      },
      {
        "title": "Step 10",
        "description": "Bring to simmer ,then reduce heat to medium low. Once it thickens to the consistency of pouring cream (3 - 5 minutes), adjust salt and pepper to taste."
      },
      {
        "title": "Step 11",
        "description": "Add beef back in (including plate juices). Simmer for 1 minute, then remove from stove immediately. (Note 4)"
      },
      {
        "title": "Step 12",
        "description": "Serve over pasta or egg noodles, sprinkled with chives if desired."
      }
    ],
    "sourceUrl": "https://www.recipetineats.com/beef-stroganoff/",
    "addedAt": 1782567811456
  },
  {
    "id": "19",
    "title": "Baked Mac and Cheese",
    "description": "Still the best Baked Mac and Cheese I've ever had in my life! Perfect in every way, this has a stunningly white, ultra creamy cheese sauce with a beautiful crunchy, buttery topping.",
    "image": "/recipe-images/recipe-19.jpg",
    "difficulty": "Medium",
    "time": "1 hr 10 mins",
    "prepTime": "10 mins",
    "bakeTime": "1 hr",
    "yields": "6",
    "category": "Side",
    "tags": [
      "imported",
      "web",
      "baked mac and cheese",
      "best mac and cheese",
      "mac and cheese recipe",
      "macaroni and cheese",
      "side",
      "western",
      "recipetineats.com"
    ],
    "ingredients": [
      {
        "amount": "250g",
        "name": "/ 8 oz macaroni (elbow pasta)"
      },
      {
        "amount": "1 tbsp",
        "name": "(15g) unsalted butter ((or 2 tsp oil))"
      },
      {
        "amount": "2/3 cup",
        "name": "panko breadcrumbs ((Note 1))"
      },
      {
        "amount": "2 tbsp",
        "name": "(30g) unsalted butter (, melted)"
      },
      {
        "amount": "1/4 tsp",
        "name": "salt"
      },
      {
        "amount": "4 tbsp",
        "name": "(60g) unsalted butter"
      },
      {
        "amount": "1/3 cup",
        "name": "flour (, plain / all purpose)"
      },
      {
        "amount": "3 cups",
        "name": "milk (, warmed (low or full fat))"
      },
      {
        "amount": "2 cups",
        "name": "freshly shredded cheese, gruyere best ((followed by cheddar and Colby) (Note 2))"
      },
      {
        "amount": "1 cup",
        "name": "freshly shredded mozzarella cheese (, or more other cheese of choice (Note 2))"
      },
      {
        "amount": "3/4 tsp",
        "name": "salt"
      },
      {
        "amount": "1 tsp",
        "name": "garlic powder"
      },
      {
        "amount": "1/2 tsp",
        "name": "onion powder"
      },
      {
        "amount": "1/2 tsp",
        "name": "mustard powder"
      }
    ],
    "steps": [
      {
        "title": "Step 1",
        "description": "Pasta:"
      },
      {
        "title": "Step 2",
        "description": "Topping:"
      },
      {
        "title": "Step 3",
        "description": "Sauce (video is helpful):"
      },
      {
        "title": "Step 4",
        "description": "Assembling:"
      }
    ],
    "sourceUrl": "https://www.recipetineats.com/baked-mac-and-cheese/",
    "addedAt": 1782567811882
  },
  {
    "id": "20",
    "title": "Caesar Salad Wonton Cups",
    "description": "Everything tastes better in miniature form!",
    "image": "/recipe-images/recipe-20.jpg",
    "difficulty": "Advanced",
    "time": "30 mins",
    "prepTime": "20 mins",
    "bakeTime": "10 mins",
    "yields": "12",
    "category": "Appetizer",
    "tags": [
      "imported",
      "web",
      "appetizer",
      "recipetineats.com"
    ],
    "ingredients": [
      {
        "amount": "12",
        "name": "wonton wrappers"
      },
      {
        "amount": "2 1/2 cups",
        "name": "cos/romaine lettuce (, shredded)"
      },
      {
        "amount": "1 cup",
        "name": "cooked chicken (, diced)"
      },
      {
        "amount": "1 1/2",
        "name": "bacon rashers (, diced)"
      },
      {
        "amount": "1/4 cup",
        "name": "bread (, diced finely (preferably stale))"
      },
      {
        "amount": "2 tbsp",
        "name": "parmesan cheese (, freshly grated)"
      },
      {
        "amount": "2 tsp",
        "name": "fresh parsley (, finely chopped (optional - for garnish))"
      },
      {
        "amount": "",
        "name": "Salt"
      },
      {
        "amount": "",
        "name": "Olive oil spray"
      },
      {
        "amount": "1",
        "name": "garlic clove (, minced)"
      },
      {
        "amount": "2",
        "name": "anchovy fillets"
      },
      {
        "amount": "2 tbsp",
        "name": "fresh lemon juice"
      },
      {
        "amount": "1 tsp",
        "name": "Dijon mustard"
      },
      {
        "amount": "1 tsp",
        "name": "Worcestershire sauce"
      },
      {
        "amount": "1 cup",
        "name": "mayonnaise (, preferably whole egg)"
      },
      {
        "amount": "1/2 cup",
        "name": "freshly grated parmesan cheese"
      },
      {
        "amount": "",
        "name": "Milk (, to adjust consistency)"
      },
      {
        "amount": "1/4 tsp",
        "name": "salt"
      },
      {
        "amount": "",
        "name": "Black pepper"
      }
    ],
    "steps": [
      {
        "title": "Step 1",
        "description": "Preheat oven to 180C/350F. Fit the wonton wrappers into each hole of a standard size muffin / cupcake tin (not mini and not Texas muffin tins!). Spray the wontons lightly with olive oil. Bake for 8 to 12 minutes, until golden and crispy. Remove from oven and set aside to cool."
      },
      {
        "title": "Step 2",
        "description": "Heat a small non stick pan over high heat. Spray with oil, add bacon and sauté until crispy, then remove and drain on absorbent paper towel."
      },
      {
        "title": "Step 3",
        "description": "Return pan to stove, reduce heat to medium high and spray pan with oil. Add finely diced bread. Shake pan (or stir) to brown evenly. Remove mini croutons from pan, scatter over a pinch of salt and set aside."
      },
      {
        "title": "Step 4",
        "description": "Place Dressing ingredients in a blender or food processor and whizz until smooth. If it seems too thick, use a tiny splash of milk to adjust the consistency."
      },
      {
        "title": "Step 5",
        "description": "Place cos lettuce, chicken and bacon in a bowl with 6 to 8 tbsp of dressing (depending on how much dressing you want to use) and toss gently to combine."
      },
      {
        "title": "Step 6",
        "description": "Divide the salad between the wonton cups, top with croutons, a pinch of parmesan and a sprinkle of parsley."
      },
      {
        "title": "Step 7",
        "description": "Serve immediately."
      }
    ],
    "sourceUrl": "https://www.recipetineats.com/caesar-salad-wonton-cups/",
    "addedAt": 1782567812985
  },
  {
    "id": "21",
    "title": "Greek Salad",
    "description": "This easy Greek salad recipe is a flavorful, refreshing summer side dish! If you make it ahead for a gathering, save a few mint leaves to add right before serving.",
    "image": "/recipe-images/recipe-21.jpg",
    "difficulty": "Medium",
    "time": "15 mins",
    "prepTime": "15 mins",
    "yields": "4",
    "category": "Salad",
    "tags": [
      "imported",
      "web",
      "greek salad dressing",
      "greek salad recipe",
      "salad",
      "american",
      "loveandlemons.com"
    ],
    "ingredients": [
      {
        "amount": "¼ cup",
        "name": "extra-virgin olive oil"
      },
      {
        "amount": "3 tablespoons",
        "name": "red wine vinegar"
      },
      {
        "amount": "1",
        "name": "garlic clove (minced)"
      },
      {
        "amount": "½ teaspoon",
        "name": "dried oregano (more for sprinkling)"
      },
      {
        "amount": "¼ teaspoon",
        "name": "Dijon mustard"
      },
      {
        "amount": "¼ teaspoon",
        "name": "sea salt"
      },
      {
        "amount": "",
        "name": "Freshly ground black pepper"
      },
      {
        "amount": "1",
        "name": "English cucumber (cut lengthwise, seeded, and sliced ¼-inch thick)"
      },
      {
        "amount": "1",
        "name": "green bell pepper (chopped into 1-inch pieces)"
      },
      {
        "amount": "2 cups",
        "name": "halved cherry tomatoes"
      },
      {
        "amount": "5 ounces",
        "name": "feta cheese (cut into ½ inch cubes*)"
      },
      {
        "amount": "⅓ cup",
        "name": "thinly sliced red onion"
      },
      {
        "amount": "⅓ cup",
        "name": "pitted Kalamata olives"
      },
      {
        "amount": "⅓ cup",
        "name": "fresh mint leaves"
      }
    ],
    "steps": [
      {
        "title": "Step 1",
        "description": "Make the dressing: In a small bowl, whisk together the olive oil, vinegar, garlic, oregano, mustard, salt, and several grinds of pepper."
      },
      {
        "title": "Step 2",
        "description": "On a large platter, arrange the cucumber, green pepper, cherry tomatoes, feta cheese, red onions, and olives. Drizzle with the dressing and very gently toss. Sprinkle with a few generous pinches of oregano and top with the mint leaves. Season to taste and serve."
      }
    ],
    "sourceUrl": "https://www.loveandlemons.com/greek-salad/",
    "addedAt": 1782567813505
  },
  {
    "id": "22",
    "title": "Best Lentil Soup",
    "description": "This easy lentil soup recipe is healthy and delicious, filled with fresh veggies, herbs, and spices. Serve it with crusty bread for a simple weeknight meal! Skip the cheese to make this recipe vegan.",
    "image": "/recipe-images/recipe-22.jpg",
    "difficulty": "Advanced",
    "time": "1 hr",
    "prepTime": "15 mins",
    "bakeTime": "45 mins",
    "yields": "4",
    "category": "Soup",
    "tags": [
      "imported",
      "web",
      "lentil soup",
      "lentil soup recipe",
      "soup",
      "american",
      "loveandlemons.com"
    ],
    "ingredients": [
      {
        "amount": "2 tablespoons",
        "name": "extra-virgin olive oil"
      },
      {
        "amount": "1",
        "name": "medium yellow onion (chopped)"
      },
      {
        "amount": "4",
        "name": "medium carrots (chopped (2 cups))"
      },
      {
        "amount": "2",
        "name": "celery stalks (chopped)"
      },
      {
        "amount": "6",
        "name": "small or 3 large kale leaves (stems finely diced, leaves chopped (8 cups))"
      },
      {
        "amount": "",
        "name": "Heaping ½ teaspoon ground cumin"
      },
      {
        "amount": "1½ teaspoons",
        "name": "sea salt"
      },
      {
        "amount": "",
        "name": "Freshly ground black pepper"
      },
      {
        "amount": "4",
        "name": "garlic cloves (grated)"
      },
      {
        "amount": "1",
        "name": "(14-ounce) can fire-roasted diced tomatoes"
      },
      {
        "amount": "¾ cup",
        "name": "dry green lentils (rinsed)"
      },
      {
        "amount": "2 tablespoons",
        "name": "white wine vinegar"
      },
      {
        "amount": "12",
        "name": "fresh thyme sprigs (bundled)"
      },
      {
        "amount": "6 cups",
        "name": "vegetable broth"
      },
      {
        "amount": "½ cup",
        "name": "chopped fresh parsley (for garnish)"
      },
      {
        "amount": "",
        "name": "Red pepper flakes"
      },
      {
        "amount": "",
        "name": "Grated Parmesan cheese (for serving, optional)"
      }
    ],
    "steps": [
      {
        "title": "Step 1",
        "description": "Heat the olive oil in a large pot over medium heat. Add the onion, carrots, celery, kale stems, cumin, salt, and several grinds of pepper, and cook, stirring occasionally, for 8 minutes, or until the vegetables begin to soften."
      },
      {
        "title": "Step 2",
        "description": "Stir in the garlic, tomatoes, lentils, vinegar, thyme, and broth. Cover and simmer for 25 to 30 minutes, or until the lentils are tender. Add the kale leaves and cook for 5 minutes, or until wilted."
      },
      {
        "title": "Step 3",
        "description": "Remove the thyme bundle and season to taste. Serve topped with the parsley, red pepper flakes, and Parmesan, if desired."
      }
    ],
    "sourceUrl": "https://www.loveandlemons.com/lentil-soup/",
    "addedAt": 1782567813964
  },
  {
    "id": "23",
    "title": "Creamy Tomato Soup",
    "description": "This homemade tomato soup recipe is the ultimate winter comfort food!",
    "image": "/recipe-images/recipe-23.jpg",
    "difficulty": "Advanced",
    "time": "45 mins",
    "prepTime": "15 mins",
    "bakeTime": "30 mins",
    "yields": "3",
    "category": "Soup",
    "tags": [
      "imported",
      "web",
      "creamy tomato soup",
      "fall",
      "summer",
      "winter",
      "soup",
      "american",
      "loveandlemons.com"
    ],
    "ingredients": [
      {
        "amount": "3",
        "name": "garlic cloves (unpeeled)"
      },
      {
        "amount": "4",
        "name": "medium fresh tomatoes* (see note)"
      },
      {
        "amount": "1",
        "name": "small yellow onion (sliced into quarters)"
      },
      {
        "amount": "1",
        "name": "(14-oz) can diced tomatoes"
      },
      {
        "amount": "1/3 cup",
        "name": "cooked chickpeas"
      },
      {
        "amount": "1 tablespoon",
        "name": "balsamic vinegar"
      },
      {
        "amount": "½ teaspoon",
        "name": "maple syrup"
      },
      {
        "amount": "2 teaspoons",
        "name": "fresh thyme leaves"
      },
      {
        "amount": "1 tablespoon",
        "name": "extra-virgin olive oil"
      },
      {
        "amount": "¼",
        "name": "to ½ teaspoon red pepper flakes"
      },
      {
        "amount": "",
        "name": "Heaping ½ teaspoon sea salt"
      },
      {
        "amount": "",
        "name": "freshly ground black pepper"
      },
      {
        "amount": "8 slices",
        "name": "SimplyNature 7 Grain Bread"
      },
      {
        "amount": "",
        "name": "heaping ½ cup Earth Grown Vegan Mozzarella"
      }
    ],
    "steps": [
      {
        "title": "Step 1",
        "description": "Preheat the oven to 450° F and line a baking sheet with parchment paper."
      },
      {
        "title": "Step 2",
        "description": "Wrap the garlic cloves in a piece of foil and place it on the baking sheet along with the whole tomatoes and the onion wedges. Drizzle with olive oil and a pinch of salt and pepper and roast for 20 to 25 minutes, or until the tomatoes and onions are well browned. Peel the garlic and transfer the roasted vegetables to a blender."
      },
      {
        "title": "Step 3",
        "description": "Reduce the oven heat to 400° F and line the baking sheet with a fresh sheet of parchment paper."
      },
      {
        "title": "Step 4",
        "description": "To the blender, add the canned tomatoes, garbanzo beans, balsamic vinegar, maple syrup, thyme leaves, 1 tablespoon olive oil, red pepper flakes, ½ teaspoon sea salt, and freshly ground pepper and blend until creamy (a Vitamix is ideal here. If using a regular blender, just blend longer!). Taste and adjust seasonings as desired. At this stage, the soup should still be hot. If not, pour it into a pot to reheat it."
      },
      {
        "title": "Step 5",
        "description": "Make the croutons: Sprinkle 4 slices of the bread with a thin layer of cheese. Top with the remaining bread slices to make sandwiches and drizzle the outsides of the bread with olive oil. Bake until the cheese is melted and the bread is golden brown, about 8 minutes. Let cool completely before slicing into croutons so that the cheese doesn’t ooze out when you cut it."
      },
      {
        "title": "Step 6",
        "description": "Serve the soup with the croutons (some in the soup, some on the side) and additional fresh thyme, red pepper flakes, and chickpeas, if desired."
      }
    ],
    "sourceUrl": "https://www.loveandlemons.com/creamy-tomato-soup/",
    "addedAt": 1782567814482
  },
  {
    "id": "24",
    "title": "Best Guacamole Recipe",
    "description": "The BEST guacamole recipe! It's easy to make with simple, fresh ingredients. Serve it as a dip with tortilla chips or with Tex Mex and Mexican dishes like tacos, burritos, and more.",
    "image": "/recipe-images/recipe-24.jpg",
    "difficulty": "Medium",
    "time": "10 mins",
    "prepTime": "10 mins",
    "yields": "4",
    "category": "Appetizer",
    "tags": [
      "imported",
      "web",
      "guacamole",
      "guacamole recipe",
      "how to make guacamole",
      "appetizer",
      "mexican",
      "loveandlemons.com"
    ],
    "ingredients": [
      {
        "amount": "3",
        "name": "avocados (ripe)"
      },
      {
        "amount": "¼ cup",
        "name": "diced red onion"
      },
      {
        "amount": "¼ cup",
        "name": "finely chopped fresh cilantro"
      },
      {
        "amount": "",
        "name": "Zest and juice of 2 limes"
      },
      {
        "amount": "1",
        "name": "small jalapeño pepper (diced)"
      },
      {
        "amount": "½ teaspoon",
        "name": "sea salt (plus more to taste)"
      },
      {
        "amount": "½ teaspoon",
        "name": "ground cumin (optional)"
      },
      {
        "amount": "",
        "name": "optional: 1 to 2 Roma tomatoes (seeded and diced)"
      }
    ],
    "steps": [
      {
        "title": "Step 1",
        "description": "In a large bowl, combine the avocados, onion, cilantro, lime zest and juice, jalapeño, salt, and cumin, if using. Mash until the ingredients are combined but still a bit chunky."
      },
      {
        "title": "Step 2",
        "description": "Fold in the tomatoes, if using."
      },
      {
        "title": "Step 3",
        "description": "Season to taste and serve."
      }
    ],
    "sourceUrl": "https://www.loveandlemons.com/guacamole-recipe/",
    "addedAt": 1782567814941
  },
  {
    "id": "25",
    "title": "BEST Hummus",
    "description": "Try this hummus recipe once, and you'll never go back to buying it at the store! Served with fresh veggies and pita, it's a delicious appetizer or snack.",
    "image": "/recipe-images/recipe-25.jpg",
    "difficulty": "Medium",
    "time": "5 mins",
    "prepTime": "5 mins",
    "yields": "8",
    "category": "Appetizer",
    "tags": [
      "imported",
      "web",
      "how to make hummus",
      "hummus",
      "hummus recipe",
      "what is hummus",
      "appetizer",
      "loveandlemons.com"
    ],
    "ingredients": [
      {
        "amount": "1½ cups",
        "name": "cooked chickpeas (drained and rinsed)"
      },
      {
        "amount": "⅓ cup",
        "name": "smooth tahini*"
      },
      {
        "amount": "2 tablespoons",
        "name": "extra-virgin olive oil"
      },
      {
        "amount": "2 tablespoons",
        "name": "fresh lemon juice (plus more to taste)"
      },
      {
        "amount": "1",
        "name": "garlic clove"
      },
      {
        "amount": "½ teaspoon",
        "name": "sea salt"
      },
      {
        "amount": "5 tablespoons",
        "name": "water (or as needed to blend)"
      },
      {
        "amount": "",
        "name": "Paprika, red pepper flakes, and/or fresh parsley"
      },
      {
        "amount": "",
        "name": "Warm pita bread (and/or veggies, for serving)"
      }
    ],
    "steps": [
      {
        "title": "Step 1",
        "description": "In a high-speed blender, place the chickpeas, tahini, olive oil, lemon juice, garlic, and salt. Use the blender baton to blend until very smooth, adding water as needed to blend, and/or to reach your desired consistency."
      },
      {
        "title": "Step 2",
        "description": "Transfer to a serving plate and garnish with paprika, red pepper flakes, and/or fresh parsley. Serve with warm pita and veggies, as desired."
      }
    ],
    "sourceUrl": "https://www.loveandlemons.com/hummus-recipe/",
    "addedAt": 1782567815393
  },
  {
    "id": "26",
    "title": "Pesto Gnocchi",
    "description": "Ready in 20 minutes, this pesto gnocchi recipe is a perfect easy dinner for summer weeknights! It's fresh and flavorful, made with bursty cherry tomatoes and a vibrant pesto sauce.",
    "image": "/recipe-images/recipe-26.jpg",
    "difficulty": "Medium",
    "time": "20 mins",
    "prepTime": "10 mins",
    "bakeTime": "10 mins",
    "yields": "2",
    "category": "Main Course",
    "tags": [
      "imported",
      "web",
      "pesto gnocchi",
      "pesto gnocchi recipe",
      "main course",
      "american",
      "loveandlemons.com"
    ],
    "ingredients": [
      {
        "amount": "1 tablespoon",
        "name": "extra-virgin olive oil"
      },
      {
        "amount": "2 cups",
        "name": "cherry tomatoes"
      },
      {
        "amount": "",
        "name": "Sea salt and freshly ground black pepper"
      },
      {
        "amount": "1 pound",
        "name": "uncooked store-bought or homemade gnocchi"
      },
      {
        "amount": "½ cup",
        "name": "store-bought pesto (or homemade pesto made with ⅓ cup olive oil)"
      },
      {
        "amount": "1 tablespoon",
        "name": "toasted pine nuts"
      },
      {
        "amount": "",
        "name": "Fresh basil leaves (for garnish)"
      },
      {
        "amount": "",
        "name": "Freshly grated Parmesan cheese (for serving)"
      }
    ],
    "steps": [
      {
        "title": "Step 1",
        "description": "Bring a large pot of salted water to a boil."
      },
      {
        "title": "Step 2",
        "description": "Meanwhile, heat the olive oil in a medium skillet over medium-low heat. Add the cherry tomatoes, a pinch of salt, and several grinds of pepper and cook, stirring occasionally, for 6 minutes, or until the tomatoes burst, soften slightly, and begin to release their flavorful juices. Remove from the heat."
      },
      {
        "title": "Step 3",
        "description": "Cook the gnocchi in the boiling water for 2 to 3 minutes, or until they float. Use a slotted spoon or spider to transfer the gnocchi directly from the boiling water to the skillet with the tomatoes. Reserve the gnocchi cooking water."
      },
      {
        "title": "Step 4",
        "description": "Gently stir to combine the gnocchi with the tomatoes, then add the pesto and gently stir until the gnocchi and tomatoes are well coated. If the pesto is too thick, add gnocchi cooking water, a few tablespoons at a time, to loosen it until it lightly coats the gnocchi."
      },
      {
        "title": "Step 5",
        "description": "Season to taste and divide into bowls. Top with the pine nuts and fresh basil and serve with freshly grated Parmesan cheese."
      }
    ],
    "sourceUrl": "https://www.loveandlemons.com/pesto-gnocchi/",
    "addedAt": 1782567815879
  }
];
