import type { Recipe } from '../types';

// Generated by scripts/fetch-themealdb-recipes.mjs
// Source: themealdb.com, areas=Greek,Italian,Spanish,Moroccan,Egyptian,Turkish, generatedAt=2026-06-23T00:39:58.904Z
export const MEALDB_SEED_RECIPES = [
  {
    "id": "mealdb_53011",
    "title": "Chicken Quinoa Greek Salad",
    "description": "Cook the quinoa following the pack instructions, then rinse in cold water and drain thoroughly.",
    "image": "https://www.themealdb.com/images/media/meals/k29viq1585565980.jpg",
    "difficulty": "Medium",
    "time": "—",
    "prepTime": "—",
    "category": "Chicken",
    "tags": [
      "chicken",
      "greek",
      "imported",
      "mealdb",
      "mediterranean"
    ],
    "ingredients": [
      {
        "name": "Quinoa",
        "amount": "225g"
      },
      {
        "name": "Butter",
        "amount": "25g"
      },
      {
        "name": "Red Chilli",
        "amount": "1 chopped"
      },
      {
        "name": "Garlic",
        "amount": "1 clove finely chopped"
      },
      {
        "name": "Chicken Breast",
        "amount": "400g"
      },
      {
        "name": "Olive Oil",
        "amount": "2 tbs"
      },
      {
        "name": "Black Olives",
        "amount": "Handful"
      },
      {
        "name": "Red Onions",
        "amount": "1 chopped"
      },
      {
        "name": "Feta",
        "amount": "100g"
      },
      {
        "name": "Mint",
        "amount": "Chopped"
      },
      {
        "name": "Lemon",
        "amount": "Juice of 1/2"
      }
    ],
    "steps": [
      {
        "title": "Step 1",
        "description": "Cook the quinoa following the pack instructions, then rinse in cold water and drain thoroughly."
      },
      {
        "title": "Step 2",
        "description": "Meanwhile, mix the butter, chilli and garlic into a paste."
      },
      {
        "title": "Step 3",
        "description": "Toss the chicken fillets in 2 tsp of the olive oil with some seasoning."
      },
      {
        "title": "Step 4",
        "description": "Lay in a hot griddle pan and cook for 3-4 mins each side or until cooked through."
      },
      {
        "title": "Step 5",
        "description": "Transfer to a plate, dot with the spicy butter and set aside to melt."
      },
      {
        "title": "Step 6",
        "description": "Next, tip the tomatoes, olives, onion, feta and mint into a bowl."
      },
      {
        "title": "Step 7",
        "description": "Toss in the cooked quinoa."
      },
      {
        "title": "Step 8",
        "description": "Stir through the remaining olive oil, lemon juice and zest, and season well."
      },
      {
        "title": "Step 9",
        "description": "Serve with the chicken fillets on top, drizzled with any buttery chicken juices."
      }
    ],
    "chefNote": "Source: https://www.bbcgoodfood.com/recipes/griddled-chicken-quinoa-greek-salad",
    "addedAt": 1782175191658
  },
  {
    "id": "mealdb_52764",
    "title": "Garides Saganaki",
    "description": "Place the prawns in a pot and add enough water to cover.",
    "image": "https://www.themealdb.com/images/media/meals/wuvryu1468232995.jpg",
    "difficulty": "Medium",
    "time": "—",
    "prepTime": "—",
    "category": "Seafood",
    "tags": [
      "greek",
      "imported",
      "mealdb",
      "mediterranean",
      "seafood",
      "shellfish"
    ],
    "ingredients": [
      {
        "name": "Raw king prawns",
        "amount": "500g"
      },
      {
        "name": "Olive oil",
        "amount": "3 tablespoons"
      },
      {
        "name": "Chopped onion",
        "amount": "1"
      },
      {
        "name": "Freshly chopped parsley",
        "amount": "pinch"
      },
      {
        "name": "White wine",
        "amount": "250ml"
      },
      {
        "name": "Chopped tomatoes",
        "amount": "1 (400g) tin"
      },
      {
        "name": "Minced garlic",
        "amount": "1/2 teaspoon"
      },
      {
        "name": "Cubed Feta cheese",
        "amount": "1 (200g) pack"
      }
    ],
    "steps": [
      {
        "title": "Step 1",
        "description": "Place the prawns in a pot and add enough water to cover."
      },
      {
        "title": "Step 2",
        "description": "Boil for 5 minutes."
      },
      {
        "title": "Step 3",
        "description": "Drain, reserving the liquid, and set aside."
      },
      {
        "title": "Step 4",
        "description": "Heat 2 tablespoons of oil in a saucepan."
      },
      {
        "title": "Step 5",
        "description": "Add the onion; cook and stir until soft."
      },
      {
        "title": "Step 6",
        "description": "Mix in the parsley, wine, tomatoes, garlic and remaining olive oil."
      },
      {
        "title": "Step 7",
        "description": "Simmer, stirring occasionally, for about 30 minutes, or until the sauce is thickened."
      },
      {
        "title": "Step 8",
        "description": "While the sauce is simmering, the prawns should become cool enough to handle."
      },
      {
        "title": "Step 9",
        "description": "First remove the legs by pinching them, and then pull off the shells, leaving the head and tail on."
      },
      {
        "title": "Step 10",
        "description": "When the sauce has thickened, stir in the prawns."
      },
      {
        "title": "Step 11",
        "description": "Bring to a simmer again if the sauce has cooled with the prawns, and cook for about 5 minutes."
      },
      {
        "title": "Step 12",
        "description": "Add the feta and remove from the heat."
      },
      {
        "title": "Step 13",
        "description": "Let stand until the cheese starts to melt."
      },
      {
        "title": "Step 14",
        "description": "Serve warm with slices of crusty bread."
      },
      {
        "title": "Step 15",
        "description": "Though completely untraditional, you can add a few tablespoons of stock or passata to this recipe to make a delicious pasta sauce."
      },
      {
        "title": "Step 16",
        "description": "Toss with pasta after adding the feta, and serve."
      }
    ],
    "addedAt": 1782175191963
  },
  {
    "id": "mealdb_53012",
    "title": "Gigantes Plaki",
    "description": "Soak the beans overnight in plenty of water.",
    "image": "https://www.themealdb.com/images/media/meals/b79r6f1585566277.jpg",
    "difficulty": "Medium",
    "time": "—",
    "prepTime": "—",
    "category": "Vegetarian",
    "tags": [
      "greek",
      "imported",
      "mealdb",
      "mediterranean",
      "vegetarian"
    ],
    "ingredients": [
      {
        "name": "Butter Beans",
        "amount": "400g"
      },
      {
        "name": "Olive Oil",
        "amount": "3 tbs"
      },
      {
        "name": "Onion",
        "amount": "1 chopped"
      },
      {
        "name": "Garlic Clove",
        "amount": "2 chopped"
      },
      {
        "name": "Tomato Puree",
        "amount": "2 tbs"
      },
      {
        "name": "Tomatoes",
        "amount": "800g"
      },
      {
        "name": "Sugar",
        "amount": "1 tbs"
      },
      {
        "name": "Dried Oregano",
        "amount": "1 tbs"
      },
      {
        "name": "Cinnamon",
        "amount": "Pinch"
      },
      {
        "name": "Chopped Parsley",
        "amount": "2 tbs"
      }
    ],
    "steps": [
      {
        "title": "Step 1",
        "description": "Soak the beans overnight in plenty of water."
      },
      {
        "title": "Step 2",
        "description": "Drain, rinse, then place in a pan covered with water."
      },
      {
        "title": "Step 3",
        "description": "Bring to the boil, reduce the heat, then simmer for approx 50 mins until slightly tender but not soft."
      },
      {
        "title": "Step 4",
        "description": "Drain, then set aside."
      },
      {
        "title": "Step 5",
        "description": "Heat oven to 180C/160C fan/gas 4."
      },
      {
        "title": "Step 6",
        "description": "Heat the olive oil in a large frying pan, tip in the onion and garlic, then cook over a medium heat for 10 mins until softened but not browned."
      },
      {
        "title": "Step 7",
        "description": "Add the tomato purée, cook for a further min, add remaining ingredients, then simmer for 2-3 mins."
      },
      {
        "title": "Step 8",
        "description": "Season generously, then stir in the beans."
      },
      {
        "title": "Step 9",
        "description": "Tip into a large ovenproof dish, then bake for approximately 1 hr, uncovered and without stirring, until the beans are tender."
      },
      {
        "title": "Step 10",
        "description": "The beans will absorb all the fabulous flavours and the sauce will thicken."
      },
      {
        "title": "Step 11",
        "description": "Allow to cool, then scatter with parsley and drizzle with a little more olive oil to serve."
      }
    ],
    "chefNote": "Source: https://www.bbcgoodfood.com/recipes/gigantes-plaki",
    "addedAt": 1782175192264
  },
  {
    "id": "mealdb_53007",
    "title": "Honey Yogurt Cheesecake",
    "description": "Heat oven to 160C/140C fan/gas 3.",
    "image": "https://www.themealdb.com/images/media/meals/y2irzl1585563479.jpg",
    "difficulty": "Medium",
    "time": "—",
    "prepTime": "—",
    "category": "Dessert",
    "tags": [
      "dessert",
      "greek",
      "imported",
      "mealdb",
      "mediterranean",
      "sweet"
    ],
    "ingredients": [
      {
        "name": "Digestive Biscuits",
        "amount": "100g"
      },
      {
        "name": "Almonds",
        "amount": "85g"
      },
      {
        "name": "Butter",
        "amount": "85g"
      },
      {
        "name": "Greek Yogurt",
        "amount": "250ml"
      },
      {
        "name": "Mascarpone",
        "amount": "750g"
      },
      {
        "name": "Eggs",
        "amount": "2"
      },
      {
        "name": "Lemon",
        "amount": "Zest of 1"
      },
      {
        "name": "Orange",
        "amount": "Zest of 1"
      },
      {
        "name": "Honey",
        "amount": "250ml"
      },
      {
        "name": "Fruit Mix",
        "amount": "To serve"
      }
    ],
    "steps": [
      {
        "title": "Step 1",
        "description": "Heat oven to 160C/140C fan/gas 3."
      },
      {
        "title": "Step 2",
        "description": "Crush the biscuits and most of the almonds inside a plastic food bag using a rolling pin."
      },
      {
        "title": "Step 3",
        "description": "Mix with the butter, then press into the bottom of a deep, oval, 23cm dish (or something similar in size – a roasting tin, baking dish or cake tin will work)."
      },
      {
        "title": "Step 4",
        "description": "Bake for 10 mins until crisp."
      },
      {
        "title": "Step 5",
        "description": "Stir or mash together the yogurt and mascarpone, then whisk in the eggs, one at a time."
      },
      {
        "title": "Step 6",
        "description": "Stir in the lemon and orange zests, then stir in most of the honey, reserving about 3 tbsp."
      },
      {
        "title": "Step 7",
        "description": "Spread over the biscuit base, cover loosely with foil and cook for 1 hr."
      },
      {
        "title": "Step 8",
        "description": "Remove the foil and cook for 15 mins more until lightly golden and the top is firm with just the slightest wobble in the middle."
      },
      {
        "title": "Step 9",
        "description": "Leave to cool."
      },
      {
        "title": "Step 10",
        "description": "Can be kept in the fridge for up to 2 days."
      },
      {
        "title": "Step 11",
        "description": "To serve, scatter with almonds, drizzle over the remaining honey, and hand around fresh fruit to go with it."
      }
    ],
    "chefNote": "Source: https://www.bbcgoodfood.com/recipes/honey-yogurt-cheesecake",
    "addedAt": 1782175192566
  },
  {
    "id": "mealdb_53009",
    "title": "Lamb and Lemon Souvlaki",
    "description": "Pound the garlic with sea salt in a pestle and mortar (or use a small food processor), until the garlic forms a paste.",
    "image": "https://www.themealdb.com/images/media/meals/rjhf741585564676.jpg",
    "difficulty": "Medium",
    "time": "—",
    "prepTime": "—",
    "category": "Lamb",
    "tags": [
      "greek",
      "imported",
      "lamb",
      "mealdb",
      "mediterranean"
    ],
    "ingredients": [
      {
        "name": "Garlic",
        "amount": "2 cloves"
      },
      {
        "name": "Sea Salt",
        "amount": "2 tsp"
      },
      {
        "name": "Olive Oil",
        "amount": "4 tbs"
      },
      {
        "name": "Lemon",
        "amount": "Zest and juice of 1"
      },
      {
        "name": "Dill",
        "amount": "1 tbs"
      },
      {
        "name": "Lamb Leg",
        "amount": "750g"
      },
      {
        "name": "Pita Bread",
        "amount": "To serve"
      }
    ],
    "steps": [
      {
        "title": "Step 1",
        "description": "Pound the garlic with sea salt in a pestle and mortar (or use a small food processor), until the garlic forms a paste."
      },
      {
        "title": "Step 2",
        "description": "Whisk together the oil, lemon juice, zest, dill and garlic."
      },
      {
        "title": "Step 3",
        "description": "Mix in the lamb and combine well."
      },
      {
        "title": "Step 4",
        "description": "Cover and marinate for at least 2 hrs or overnight in the fridge."
      },
      {
        "title": "Step 5",
        "description": "If you’re going to use bamboo skewers, soak them in cold water."
      },
      {
        "title": "Step 6",
        "description": "If you’ve prepared the lamb the previous day, take it out of the fridge 30 mins before cooking."
      },
      {
        "title": "Step 7",
        "description": "Thread the meat onto the soaked or metal skewers."
      },
      {
        "title": "Step 8",
        "description": "Heat the grill to high or have a hot griddle pan or barbecue ready."
      },
      {
        "title": "Step 9",
        "description": "Cook the skewers for 2-3 mins on each side, basting with the remaining marinade."
      },
      {
        "title": "Step 10",
        "description": "Heat the pitta or flatbreads briefly, then stuff with the souvlaki."
      },
      {
        "title": "Step 11",
        "description": "Add Greek salad (see 'Goes well with', right) and Tzatziki (below), if you like."
      }
    ],
    "chefNote": "Source: https://www.bbcgoodfood.com/recipes/lamb-lemon-dill-souvlaki",
    "addedAt": 1782175192864
  },
  {
    "id": "mealdb_53010",
    "title": "Lamb Tzatziki Burgers",
    "description": "Tip the bulghar into a pan, cover with water and boil for 10 mins.",
    "image": "https://www.themealdb.com/images/media/meals/k420tj1585565244.jpg",
    "difficulty": "Medium",
    "time": "—",
    "prepTime": "—",
    "category": "Lamb",
    "tags": [
      "greek",
      "imported",
      "lamb",
      "mealdb",
      "mediterranean"
    ],
    "ingredients": [
      {
        "name": "Bulgur Wheat",
        "amount": "25g"
      },
      {
        "name": "Lamb Mince",
        "amount": "500g"
      },
      {
        "name": "Cumin",
        "amount": "1 tsp"
      },
      {
        "name": "Coriander",
        "amount": "1 tsp"
      },
      {
        "name": "Paprika",
        "amount": "1 tsp"
      },
      {
        "name": "Garlic",
        "amount": "1 clove finely chopped"
      },
      {
        "name": "Olive Oil",
        "amount": "For frying"
      },
      {
        "name": "Bun",
        "amount": "4"
      },
      {
        "name": "Cucumber",
        "amount": "Grated"
      },
      {
        "name": "Greek Yogurt",
        "amount": "200g"
      },
      {
        "name": "Mint",
        "amount": "2 tbs"
      }
    ],
    "steps": [
      {
        "title": "Step 1",
        "description": "Tip the bulghar into a pan, cover with water and boil for 10 mins."
      },
      {
        "title": "Step 2",
        "description": "Drain really well in a sieve, pressing out any excess water."
      },
      {
        "title": "Step 3",
        "description": "To make the tzatziki, squeeze and discard the juice from the cucumber, then mix into the yogurt with the chopped mint and a little salt."
      },
      {
        "title": "Step 4",
        "description": "Work the bulghar into the lamb with the spices, garlic (if using) and seasoning, then shape into 4 burgers."
      },
      {
        "title": "Step 5",
        "description": "Brush with a little oil and fry or barbecue for about 5 mins each side until cooked all the way through."
      },
      {
        "title": "Step 6",
        "description": "Serve in the buns (toasted if you like) with the tzatziki, tomatoes, onion and a few mint leaves."
      }
    ],
    "chefNote": "Source: https://www.bbcgoodfood.com/recipes/lamb-burgers-tzatziki",
    "addedAt": 1782175193233
  },
  {
    "id": "mealdb_53006",
    "title": "Moussaka",
    "description": "Heat the grill to high.",
    "image": "https://www.themealdb.com/images/media/meals/ctg8jd1585563097.jpg",
    "difficulty": "Medium",
    "time": "—",
    "prepTime": "—",
    "category": "Beef",
    "tags": [
      "beef",
      "greek",
      "imported",
      "mealdb",
      "mediterranean"
    ],
    "ingredients": [
      {
        "name": "Beef",
        "amount": "500g"
      },
      {
        "name": "Aubergine",
        "amount": "1 large"
      },
      {
        "name": "Greek Yogurt",
        "amount": "150g"
      },
      {
        "name": "Egg",
        "amount": "1 beaten"
      },
      {
        "name": "Parmesan",
        "amount": "3 tbs"
      },
      {
        "name": "Tomato",
        "amount": "400g"
      },
      {
        "name": "Tomato Puree",
        "amount": "4 tbs"
      },
      {
        "name": "Potatoes",
        "amount": "350g"
      }
    ],
    "steps": [
      {
        "title": "Step 1",
        "description": "Heat the grill to high."
      },
      {
        "title": "Step 2",
        "description": "Brown the beef in a deep ovenproof frying pan over a high heat for 5 mins."
      },
      {
        "title": "Step 3",
        "description": "Meanwhile, prick the aubergine with a fork, then microwave on High for 3-5 mins until soft."
      },
      {
        "title": "Step 4",
        "description": "Mix the yogurt, egg and parmesan together, then add a little seasoning."
      },
      {
        "title": "Step 5",
        "description": "Stir the tomatoes, purée and potatoes in with the beef with some seasoning and heat through."
      },
      {
        "title": "Step 6",
        "description": "Smooth the surface of the beef mixture with the back of a spoon, then slice the cooked aubergine and arrange on top."
      },
      {
        "title": "Step 7",
        "description": "Pour the yogurt mixture over the aubergines, smooth out evenly, then grill until the topping has set and turned golden."
      }
    ],
    "chefNote": "Source: https://www.bbcgoodfood.com/recipes/must-make-moussaka",
    "addedAt": 1782175193572
  },
  {
    "id": "mealdb_53008",
    "title": "Stuffed Lamb Tomatoes",
    "description": "Heat oven to 180C/160C fan/gas 4.",
    "image": "https://www.themealdb.com/images/media/meals/u55lbp1585564013.jpg",
    "difficulty": "Medium",
    "time": "—",
    "prepTime": "—",
    "category": "Lamb",
    "tags": [
      "greek",
      "imported",
      "lamb",
      "mealdb",
      "mediterranean"
    ],
    "ingredients": [
      {
        "name": "Tomatoes",
        "amount": "4 large"
      },
      {
        "name": "Sugar",
        "amount": "Pinch"
      },
      {
        "name": "Olive Oil",
        "amount": "4 tbs"
      },
      {
        "name": "Onion",
        "amount": "1 chopped"
      },
      {
        "name": "Garlic Clove",
        "amount": "2 finely chopped"
      },
      {
        "name": "Lamb",
        "amount": "200g"
      },
      {
        "name": "Cinnamon",
        "amount": "1 tbs"
      },
      {
        "name": "Tomato Puree",
        "amount": "2 tbs chopped"
      },
      {
        "name": "Rice",
        "amount": "50g"
      },
      {
        "name": "Chicken Stock",
        "amount": "100ml"
      },
      {
        "name": "Dill",
        "amount": "4 tbs"
      },
      {
        "name": "Chopped Parsley",
        "amount": "2 tbs"
      },
      {
        "name": "Mint",
        "amount": "1 tbs"
      }
    ],
    "steps": [
      {
        "title": "Step 1",
        "description": "Heat oven to 180C/160C fan/gas 4."
      },
      {
        "title": "Step 2",
        "description": "Slice the tops off the tomatoes and reserve."
      },
      {
        "title": "Step 3",
        "description": "Scoop out most of the pulp with a teaspoon, being careful not to break the skin."
      },
      {
        "title": "Step 4",
        "description": "Finely chop the pulp, and keep any juices."
      },
      {
        "title": "Step 5",
        "description": "Sprinkle the insides of the tomatoes with a little sugar to take away the acidity, then place them on a baking tray."
      },
      {
        "title": "Step 6",
        "description": "Heat 2 tbsp olive oil in a large frying pan, add the onion and garlic, then gently cook for about 10 mins until soft but not coloured."
      },
      {
        "title": "Step 7",
        "description": "Add the lamb, cinnamon and tomato purée, turn up the heat, then fry until the meat is browned."
      },
      {
        "title": "Step 8",
        "description": "Add the tomato pulp and juice, the rice and the stock."
      },
      {
        "title": "Step 9",
        "description": "Season generously."
      },
      {
        "title": "Step 10",
        "description": "Bring to the boil, then simmer for 15 mins or until the rice is tender and the liquid has been absorbed."
      },
      {
        "title": "Step 11",
        "description": "Set aside to cool a little, then stir in the herbs."
      },
      {
        "title": "Step 12",
        "description": "Stuff the tomatoes up to the brim, top tomatoes with their lids, drizzle with 2 tbsp more olive oil, sprinkle 3 tbsp water into the tray, then bake for 35 mins."
      },
      {
        "title": "Step 13",
        "description": "Serve with salad and crusty bread, hot or cold."
      }
    ],
    "chefNote": "Source: https://www.bbcgoodfood.com/recipes/stuffed-tomatoes-lamb-mince-dill-rice",
    "addedAt": 1782175193884
  },
  {
    "id": "mealdb_52961",
    "title": "Budino Di Ricotta",
    "description": "Mash the ricotta and beat well with the egg yolks, stir in the flour, sugar, cinnamon, grated lemon rind and the rum and mix well.",
    "image": "https://www.themealdb.com/images/media/meals/1549542877.jpg",
    "difficulty": "Medium",
    "time": "—",
    "prepTime": "—",
    "category": "Dessert",
    "tags": [
      "alcoholic",
      "baking",
      "cake",
      "calorific",
      "desert",
      "dessert",
      "imported",
      "italian",
      "mealdb",
      "mediterranean",
      "sweet"
    ],
    "ingredients": [
      {
        "name": "Ricotta",
        "amount": "500g"
      },
      {
        "name": "Eggs",
        "amount": "4 large"
      },
      {
        "name": "Flour",
        "amount": "3 tbs"
      },
      {
        "name": "Sugar",
        "amount": "250g"
      },
      {
        "name": "Cinnamon",
        "amount": "1 tsp"
      },
      {
        "name": "Lemons",
        "amount": "Grated Zest of 2"
      },
      {
        "name": "Dark Rum",
        "amount": "5 tbs"
      },
      {
        "name": "Icing Sugar",
        "amount": "sprinking"
      }
    ],
    "steps": [
      {
        "title": "Step 1",
        "description": "Mash the ricotta and beat well with the egg yolks, stir in the flour, sugar, cinnamon, grated lemon rind and the rum and mix well."
      },
      {
        "title": "Step 2",
        "description": "You can do this in a food processor."
      },
      {
        "title": "Step 3",
        "description": "Beat the egg whites until stiff, fold in and pour into a buttered and floured 25cm cake tin."
      },
      {
        "title": "Step 4",
        "description": "Bake in the oven at 180ºC/160ºC fan/gas 4 for about 40 minutes, or until it is firm."
      },
      {
        "title": "Step 5",
        "description": "Serve hot or cold dusted with icing sugar."
      }
    ],
    "chefNote": "Source: https://thehappyfoodie.co.uk/recipes/ricotta-cake-budino-di-ricotta",
    "addedAt": 1782175194195
  },
  {
    "id": "mealdb_52796",
    "title": "Chicken Alfredo Primavera",
    "description": "Heat 1 tablespoon of butter and 2 tablespoons of olive oil in a large skillet over medium-high heat.",
    "image": "https://www.themealdb.com/images/media/meals/syqypv1486981727.jpg",
    "difficulty": "Medium",
    "time": "—",
    "prepTime": "—",
    "category": "Chicken",
    "tags": [
      "chicken",
      "dairy",
      "imported",
      "italian",
      "mealdb",
      "meat",
      "mediterranean",
      "pasta"
    ],
    "ingredients": [
      {
        "name": "Butter",
        "amount": "2 tablespoons"
      },
      {
        "name": "Olive Oil",
        "amount": "3 tablespoons"
      },
      {
        "name": "Chicken",
        "amount": "5 boneless"
      },
      {
        "name": "Salt",
        "amount": "1 teaspoon"
      },
      {
        "name": "Squash",
        "amount": "1 cut into 1/2-inch cubes"
      },
      {
        "name": "Broccoli",
        "amount": "1 Head chopped"
      },
      {
        "name": "mushrooms",
        "amount": "8-ounce sliced"
      },
      {
        "name": "Pepper",
        "amount": "1 red"
      },
      {
        "name": "onion",
        "amount": "1 chopped"
      },
      {
        "name": "garlic",
        "amount": "3 cloves"
      },
      {
        "name": "red pepper flakes",
        "amount": "1/2 teaspoon"
      },
      {
        "name": "white wine",
        "amount": "1/2 cup"
      },
      {
        "name": "milk",
        "amount": "1/2 cup"
      },
      {
        "name": "heavy cream",
        "amount": "1/2 cup"
      },
      {
        "name": "Parmesan cheese",
        "amount": "1 cup grated"
      },
      {
        "name": "bowtie pasta",
        "amount": "16 ounces"
      },
      {
        "name": "Salt",
        "amount": "pinch"
      },
      {
        "name": "Pepper",
        "amount": "pinch"
      },
      {
        "name": "Parsley",
        "amount": "chopped"
      }
    ],
    "steps": [
      {
        "title": "Step 1",
        "description": "Heat 1 tablespoon of butter and 2 tablespoons of olive oil in a large skillet over medium-high heat."
      },
      {
        "title": "Step 2",
        "description": "Season both sides of each chicken breast with seasoned salt and a pinch of pepper."
      },
      {
        "title": "Step 3",
        "description": "Add the chicken to the skillet and cook for 5-7 minutes on each side, or until cooked through."
      },
      {
        "title": "Step 4",
        "description": "While the chicken is cooking, bring a large pot of water to a boil."
      },
      {
        "title": "Step 5",
        "description": "Season the boiling water with a few generous pinches of kosher salt."
      },
      {
        "title": "Step 6",
        "description": "Add the pasta and give it a stir."
      },
      {
        "title": "Step 7",
        "description": "Cook, stirring occasionally, until al dente, about 12 minutes."
      },
      {
        "title": "Step 8",
        "description": "Reserve 1/2 cup of  pasta water before draining the pasta."
      },
      {
        "title": "Step 9",
        "description": "Remove the chicken from the pan and transfer it to a cutting board; allow it to rest."
      },
      {
        "title": "Step 10",
        "description": "Turn the heat down to medium and dd the remaining 1 tablespoon of butter and olive oil to the same pan you used to cook the chicken."
      },
      {
        "title": "Step 11",
        "description": "Add the veggies (minus the garlic) and red pepper flakes to the pan and stir to coat with the oil and butter (refrain from seasoning with salt until the veggies are finished browning)."
      },
      {
        "title": "Step 12",
        "description": "Cook, stirring often, until the veggies are tender, about 5 minutes."
      },
      {
        "title": "Step 13",
        "description": "Add the garlic and a generous pinch of salt and pepper to the pan and cook for 1 minute."
      },
      {
        "title": "Step 14",
        "description": "Deglaze the pan with the white wine."
      },
      {
        "title": "Step 15",
        "description": "Continue to cook until the wine has reduced by half, about 3 minutes."
      },
      {
        "title": "Step 16",
        "description": "Stir in the milk, heavy cream, and reserved pasta water."
      },
      {
        "title": "Step 17",
        "description": "Bring the mixture to a gentle boil and allow to simmer and reduce for 2-3 minutes."
      },
      {
        "title": "Step 18",
        "description": "Turn off the heat and add the Parmesan cheese and cooked pasta."
      },
      {
        "title": "Step 19",
        "description": "Season with salt and pepper to taste."
      },
      {
        "title": "Step 20",
        "description": "Garnish with Parmesan cheese and chopped parsley, if desired."
      }
    ],
    "addedAt": 1782175194495
  },
  {
    "id": "mealdb_52839",
    "title": "Chilli prawn linguine",
    "description": "Mix the dressing ingredients in a small bowl and season with salt and pepper.",
    "image": "https://www.themealdb.com/images/media/meals/usywpp1511189717.jpg",
    "difficulty": "Medium",
    "time": "—",
    "prepTime": "—",
    "category": "Pasta",
    "tags": [
      "imported",
      "italian",
      "mealdb",
      "mediterranean",
      "pasta"
    ],
    "ingredients": [
      {
        "name": "Linguine Pasta",
        "amount": "280g"
      },
      {
        "name": "Sugar Snap Peas",
        "amount": "200g"
      },
      {
        "name": "Olive Oil",
        "amount": "2 tblsp"
      },
      {
        "name": "Garlic Clove",
        "amount": "2 cloves chopped"
      },
      {
        "name": "Red Chilli",
        "amount": "1 large"
      },
      {
        "name": "King Prawns",
        "amount": "24 Skinned"
      },
      {
        "name": "Cherry Tomatoes",
        "amount": "12"
      },
      {
        "name": "Basil Leaves",
        "amount": "Handful"
      },
      {
        "name": "Lettuce",
        "amount": "Leaves"
      },
      {
        "name": "Bread",
        "amount": "to serve"
      },
      {
        "name": "Fromage Frais",
        "amount": "2 tbsp"
      },
      {
        "name": "Lime",
        "amount": "Grated Zest of 2"
      },
      {
        "name": "Caster Sugar",
        "amount": "2 tsp"
      }
    ],
    "steps": [
      {
        "title": "Step 1",
        "description": "Mix the dressing ingredients in a small bowl and season with salt and pepper."
      },
      {
        "title": "Step 2",
        "description": "Set aside."
      },
      {
        "title": "Step 3",
        "description": "Cook the pasta according to the packet instructions."
      },
      {
        "title": "Step 4",
        "description": "Add the sugar snap peas for the last minute or so of cooking time."
      },
      {
        "title": "Step 5",
        "description": "Meanwhile, heat the oil in a wok or large frying pan, toss in the garlic and chilli and cook over a fairly gentle heat for about 30 seconds without letting the garlic brown."
      },
      {
        "title": "Step 6",
        "description": "Tip in the prawns and cook over a high heat, stirring frequently, for about 3 minutes until they turn pink."
      },
      {
        "title": "Step 7",
        "description": "Add the tomatoes and cook, stirring occasionally, for 3 minutes until they just start to soften."
      },
      {
        "title": "Step 8",
        "description": "Drain the pasta and sugar snaps well, then toss into the prawn mixture."
      },
      {
        "title": "Step 9",
        "description": "Tear in the basil leaves, stir, and season with salt and pepper."
      },
      {
        "title": "Step 10",
        "description": "Serve with salad leaves drizzled with the lime dressing, and warm crusty bread."
      }
    ],
    "chefNote": "Source: https://www.bbcgoodfood.com/recipes/1269/chilli-prawn-linguine",
    "addedAt": 1782175194795
  },
  {
    "id": "mealdb_53064",
    "title": "Fettuccine Alfredo",
    "description": "Cook pasta according to package instructions in a large pot of boiling water and salt.",
    "image": "https://www.themealdb.com/images/media/meals/0jv5gx1661040802.jpg",
    "difficulty": "Medium",
    "time": "—",
    "prepTime": "—",
    "category": "Pasta",
    "tags": [
      "imported",
      "italian",
      "mealdb",
      "mediterranean",
      "pasta"
    ],
    "ingredients": [
      {
        "name": "Fettuccine",
        "amount": "1 lb"
      },
      {
        "name": "Heavy Cream",
        "amount": "1/2 cup"
      },
      {
        "name": "Butter",
        "amount": "1/2 cup"
      },
      {
        "name": "Parmesan",
        "amount": "1/2 cup"
      },
      {
        "name": "Parsley",
        "amount": "2 tbsp"
      },
      {
        "name": "Black Pepper",
        "amount": "to taste"
      }
    ],
    "steps": [
      {
        "title": "Step 1",
        "description": "Cook pasta according to package instructions in a large pot of boiling water and salt."
      },
      {
        "title": "Step 2",
        "description": "Add heavy cream and butter to a large skillet over medium heat until the cream bubbles and the butter melts."
      },
      {
        "title": "Step 3",
        "description": "Whisk in parmesan and add seasoning (salt and black pepper)."
      },
      {
        "title": "Step 4",
        "description": "Let the sauce thicken slightly and then add the pasta and toss until coated in sauce."
      },
      {
        "title": "Step 5",
        "description": "Garnish with parsley, and it's ready."
      }
    ],
    "chefNote": "Source: https://www.delish.com/cooking/recipe-ideas/a55312/best-homemade-fettuccine-alfredo-recipe/",
    "addedAt": 1782175195106
  },
  {
    "id": "mealdb_52835",
    "title": "Fettucine alfredo",
    "description": "In a medium saucepan, stir the clotted cream, butter and cornflour over a low-ish heat and bring to a low simmer.",
    "image": "https://www.themealdb.com/images/media/meals/uquqtu1511178042.jpg",
    "difficulty": "Medium",
    "time": "—",
    "prepTime": "—",
    "category": "Pasta",
    "tags": [
      "imported",
      "italian",
      "mealdb",
      "mediterranean",
      "pasta"
    ],
    "ingredients": [
      {
        "name": "Clotted Cream",
        "amount": "227g"
      },
      {
        "name": "Butter",
        "amount": "25g"
      },
      {
        "name": "Corn Flour",
        "amount": "1 tsp"
      },
      {
        "name": "Parmesan Cheese",
        "amount": "100g"
      },
      {
        "name": "Nutmeg",
        "amount": "Grated"
      },
      {
        "name": "Fettuccine",
        "amount": "250g"
      },
      {
        "name": "Parsley",
        "amount": "Chopped"
      }
    ],
    "steps": [
      {
        "title": "Step 1",
        "description": "In a medium saucepan, stir the clotted cream, butter and cornflour over a low-ish heat and bring to a low simmer."
      },
      {
        "title": "Step 2",
        "description": "Turn off the heat and keep warm."
      },
      {
        "title": "Step 3",
        "description": "Meanwhile, put the cheese and nutmeg in a small bowl and add a good grinding of black pepper, then stir everything together (don’t add any salt at this stage)."
      },
      {
        "title": "Step 4",
        "description": "Put the pasta in another pan with 2 tsp salt, pour over some boiling water and cook following pack instructions (usually 3-4 mins)."
      },
      {
        "title": "Step 5",
        "description": "When cooked, scoop some of the cooking water into a heatproof jug or mug and drain the pasta, but not too thoroughly."
      },
      {
        "title": "Step 6",
        "description": "Add the pasta to the pan with the clotted cream mixture, then sprinkle over the cheese and gently fold everything together over a low heat using a rubber spatula."
      },
      {
        "title": "Step 7",
        "description": "When combined, splash in 3 tbsp of the cooking water."
      },
      {
        "title": "Step 8",
        "description": "At first, the pasta will look wet and sloppy: keep stirring until the water is absorbed and the sauce is glossy."
      },
      {
        "title": "Step 9",
        "description": "Check the seasoning before transferring to heated bowls."
      },
      {
        "title": "Step 10",
        "description": "Sprinkle over some chives or parsley, then serve immediately."
      }
    ],
    "chefNote": "Source: https://www.bbcgoodfood.com/recipes/fettucine-alfredo",
    "addedAt": 1782175195405
  },
  {
    "id": "mealdb_52844",
    "title": "Lasagne",
    "description": "Heat the oil in a large saucepan.",
    "image": "https://www.themealdb.com/images/media/meals/wtsvxx1511296896.jpg",
    "difficulty": "Medium",
    "time": "—",
    "prepTime": "—",
    "category": "Pasta",
    "tags": [
      "imported",
      "italian",
      "mealdb",
      "mediterranean",
      "pasta"
    ],
    "ingredients": [
      {
        "name": "Olive Oil",
        "amount": "1 tblsp"
      },
      {
        "name": "Bacon",
        "amount": "2"
      },
      {
        "name": "Onion",
        "amount": "1 finely chopped"
      },
      {
        "name": "Celery",
        "amount": "1 Stick"
      },
      {
        "name": "Carrots",
        "amount": "1 medium"
      },
      {
        "name": "Garlic",
        "amount": "2 cloves chopped"
      },
      {
        "name": "Minced Beef",
        "amount": "500g"
      },
      {
        "name": "Tomato Puree",
        "amount": "1 tbls"
      },
      {
        "name": "Chopped Tomatoes",
        "amount": "800g"
      },
      {
        "name": "Honey",
        "amount": "1 tblsp"
      },
      {
        "name": "Lasagne Sheets",
        "amount": "500g"
      },
      {
        "name": "Creme Fraiche",
        "amount": "400ml"
      },
      {
        "name": "Mozzarella Balls",
        "amount": "125g"
      },
      {
        "name": "Parmesan Cheese",
        "amount": "50g"
      },
      {
        "name": "Basil Leaves",
        "amount": "Topping"
      }
    ],
    "steps": [
      {
        "title": "Step 1",
        "description": "Heat the oil in a large saucepan."
      },
      {
        "title": "Step 2",
        "description": "Use kitchen scissors to snip the bacon into small pieces, or use a sharp knife to chop it on a chopping board."
      },
      {
        "title": "Step 3",
        "description": "Add the bacon to the pan and cook for just a few mins until starting to turn golden."
      },
      {
        "title": "Step 4",
        "description": "Add the onion, celery and carrot, and cook over a medium heat for 5 mins, stirring occasionally, until softened."
      },
      {
        "title": "Step 5",
        "description": "Add the garlic and cook for 1 min, then tip in the mince and cook, stirring and breaking it up with a wooden spoon, for about 6 mins until browned all over."
      },
      {
        "title": "Step 6",
        "description": "Stir in the tomato purée and cook for 1 min, mixing in well with the beef and vegetables."
      },
      {
        "title": "Step 7",
        "description": "Tip in the chopped tomatoes."
      },
      {
        "title": "Step 8",
        "description": "Fill each can half full with water to rinse out any tomatoes left in the can, and add to the pan."
      },
      {
        "title": "Step 9",
        "description": "Add the honey and season to taste."
      },
      {
        "title": "Step 10",
        "description": "Simmer for 20 mins."
      },
      {
        "title": "Step 11",
        "description": "Heat oven to 200C/180C fan/gas 6."
      },
      {
        "title": "Step 12",
        "description": "To assemble the lasagne, ladle a little of the ragu sauce into the bottom of the roasting tin or casserole dish, spreading the sauce all over the base."
      },
      {
        "title": "Step 13",
        "description": "Place 2 sheets of lasagne on top of the sauce overlapping to make it fit, then repeat with more sauce and another layer of pasta."
      },
      {
        "title": "Step 14",
        "description": "Repeat with a further 2 layers of sauce and pasta, finishing with a layer of pasta."
      },
      {
        "title": "Step 15",
        "description": "Put the crème fraîche in a bowl and mix with 2 tbsp water to loosen it and make a smooth pourable sauce."
      },
      {
        "title": "Step 16",
        "description": "Pour this over the top of the pasta, then top with the mozzarella."
      },
      {
        "title": "Step 17",
        "description": "Sprinkle Parmesan over the top and bake for 25–30 mins until golden and bubbling."
      },
      {
        "title": "Step 18",
        "description": "Serve scattered with basil, if you like."
      }
    ],
    "chefNote": "Source: https://www.bbcgoodfood.com/recipes/classic-lasagne",
    "addedAt": 1782175195740
  },
  {
    "id": "mealdb_52777",
    "title": "Mediterranean Pasta Salad",
    "description": "Bring a large saucepan of salted water to the boil Add the pasta, stir once and cook for about 10 minutes or as directed on the packet.",
    "image": "https://www.themealdb.com/images/media/meals/wvqpwt1468339226.jpg",
    "difficulty": "Medium",
    "time": "—",
    "prepTime": "—",
    "category": "Seafood",
    "tags": [
      "baking",
      "imported",
      "italian",
      "mealdb",
      "mediterranean",
      "pasta",
      "seafood"
    ],
    "ingredients": [
      {
        "name": "mozzarella balls",
        "amount": "200 g"
      },
      {
        "name": "baby plum tomatoes",
        "amount": "250 g"
      },
      {
        "name": "fresh basil",
        "amount": "1  bunch"
      },
      {
        "name": "farfalle",
        "amount": "350 g"
      },
      {
        "name": "extra virgin olive oil",
        "amount": "3  tablespoons"
      },
      {
        "name": "Green Olives",
        "amount": "40 g"
      },
      {
        "name": "tuna",
        "amount": "200 g"
      },
      {
        "name": "salt",
        "amount": "to taste"
      },
      {
        "name": "pepper",
        "amount": "to taste"
      }
    ],
    "steps": [
      {
        "title": "Step 1",
        "description": "Bring a large saucepan of salted water to the boil."
      },
      {
        "title": "Step 2",
        "description": "Add the pasta, stir once and cook for about 10 minutes or as directed on the packet."
      },
      {
        "title": "Step 3",
        "description": "Meanwhile, wash the tomatoes and cut into quarters."
      },
      {
        "title": "Step 4",
        "description": "Slice the olives."
      },
      {
        "title": "Step 5",
        "description": "Wash the basil."
      },
      {
        "title": "Step 6",
        "description": "Put the tomatoes into a salad bowl and tear the basil leaves over them."
      },
      {
        "title": "Step 7",
        "description": "Add a tablespoon of olive oil and mix."
      },
      {
        "title": "Step 8",
        "description": "When the pasta is ready, drain into a colander and run cold water over it to cool it quickly."
      },
      {
        "title": "Step 9",
        "description": "Toss the pasta into the salad bowl with the tomatoes and basil."
      },
      {
        "title": "Step 10",
        "description": "Add the sliced olives, drained mozzarella balls, and chunks of tuna."
      },
      {
        "title": "Step 11",
        "description": "Mix well and let the salad rest for at least half an hour to allow the flavours to mingle."
      },
      {
        "title": "Step 12",
        "description": "Sprinkle the pasta with a generous grind of black pepper and drizzle with the remaining olive oil just before serving."
      }
    ],
    "chefNote": "Source: https://thelemonsqueezy.com/recipe/mediterranean-pasta-salad/",
    "addedAt": 1782175196071
  },
  {
    "id": "mealdb_52810",
    "title": "Osso Buco alla Milanese",
    "description": "Heat the oven to 300 degrees.",
    "image": "https://www.themealdb.com/images/media/meals/wwuqvt1487345467.jpg",
    "difficulty": "Medium",
    "time": "—",
    "prepTime": "—",
    "category": "Miscellaneous",
    "tags": [
      "imported",
      "italian",
      "mealdb",
      "mediterranean",
      "miscellaneous"
    ],
    "ingredients": [
      {
        "name": "Veal",
        "amount": "4 meaty shanks"
      },
      {
        "name": "Flour",
        "amount": "½ cup"
      },
      {
        "name": "Olive Oil",
        "amount": "2 tablespoons"
      },
      {
        "name": "Butter",
        "amount": "3 tablespoons"
      },
      {
        "name": "Onion",
        "amount": "1 medium chopped into ½-inch pieces"
      },
      {
        "name": "Carrots",
        "amount": "1 chopped into ½-inch pieces"
      },
      {
        "name": "Celery",
        "amount": "1 chopped into ½-inch pieces"
      },
      {
        "name": "Fennel",
        "amount": "1 bulb chopped into ½-inch pieces"
      },
      {
        "name": "Garlic",
        "amount": "3 cloves"
      },
      {
        "name": "Orange Zest",
        "amount": "2 strips"
      },
      {
        "name": "Marjoram",
        "amount": "1 ½ teaspoons"
      },
      {
        "name": "Bay Leaf",
        "amount": "1"
      },
      {
        "name": "Dry White Wine",
        "amount": "1 cup"
      },
      {
        "name": "Chicken Stock",
        "amount": "½ cup"
      },
      {
        "name": "Tomatoes",
        "amount": "1 cup chopped with juice"
      },
      {
        "name": "Parsley",
        "amount": "2 tablespoons chopped"
      },
      {
        "name": "Garlic",
        "amount": "1 teaspoon minced"
      },
      {
        "name": "Lemon Zest",
        "amount": "1 teaspoon grated"
      }
    ],
    "steps": [
      {
        "title": "Step 1",
        "description": "Heat the oven to 300 degrees."
      },
      {
        "title": "Step 2",
        "description": "Dredging the shanks: pour the flour into a shallow dish (a pie plate works nicely)."
      },
      {
        "title": "Step 3",
        "description": "Season the veal shanks on all sides with salt and pepper."
      },
      {
        "title": "Step 4",
        "description": "One at a time, roll the shanks around in the flour coat, and shake and pat the shank to remove any excuses flour."
      },
      {
        "title": "Step 5",
        "description": "Discard the remaining flour."
      },
      {
        "title": "Step 6",
        "description": "Browning the shanks: put the oil and 1 tablespoon of the butter in a wide Dutch oven or heavy braising pot (6 to 7 quart) and heat over medium-high heat."
      },
      {
        "title": "Step 7",
        "description": "When the butter has melted and the oil is shimmering, lower the shanks into the pot, flat side down; if the shanks won’t fit without touching one another, do this in batches."
      },
      {
        "title": "Step 8",
        "description": "Brown the shanks, turning once with tongs, until both flat sides are well caramelized, about 5 minutes per side."
      },
      {
        "title": "Step 9",
        "description": "If the butter-oil mixture starts to burn, lower the heat just a bit."
      },
      {
        "title": "Step 10",
        "description": "Transfer the shanks to a large platter or tray and set aside."
      },
      {
        "title": "Step 11",
        "description": "The aromatics: pour off and discard the fat from the pot."
      },
      {
        "title": "Step 12",
        "description": "Wipe out any burnt bits with a damp paper towel, being careful not to remove any delicious little caramelized bits."
      },
      {
        "title": "Step 13",
        "description": "Ad the remaining 2 tablespoons butter to the pot and melt it over medium heat."
      },
      {
        "title": "Step 14",
        "description": "When the butter has stopped foaming, add the onion, carrot, celery, and fennel."
      },
      {
        "title": "Step 15",
        "description": "Season with salt and pepper, stir, and cook the vegetables until they begin to soften but do not brown, about 6 minutes."
      },
      {
        "title": "Step 16",
        "description": "Stir in the garlic, orange zest, marjoram, and bay leaf, and stew for another minute or two."
      },
      {
        "title": "Step 17",
        "description": "The braising liquid: add the wine, increase the heat to high, and bring to a boil."
      },
      {
        "title": "Step 18",
        "description": "Boil, stirring occasionally, to reduce the wine by about half, 5 minutes."
      },
      {
        "title": "Step 19",
        "description": "Add the stock and tomatoes, with their juice, and boil again to reduce the liquid to about 1 cup total, about 10 minutes."
      },
      {
        "title": "Step 20",
        "description": "The braise: Place the shanks in the pot so that they are sitting with the exposed bone facing up, and pour over any juices that accumulated as they sat."
      },
      {
        "title": "Step 21",
        "description": "Cover with parchment paper, pressing down so the parchment nearly touches the veal and the edges hang over the sides of the pot by about an inch."
      },
      {
        "title": "Step 22",
        "description": "Cover tightly with the lid, and slide into the lower part of the oven to braise at a gentle simmer."
      },
      {
        "title": "Step 23",
        "description": "Check the pot after the first 15 minutes, and if the liquid is simmering too aggressively, lower the oven heat by 10 or 15 degrees."
      },
      {
        "title": "Step 24",
        "description": "Continue braising, turning the shanks and spooning some pan juices over the top after the first 40 minutes, until the meat is completely tender and pulling away from the bone, about 2 hours."
      },
      {
        "title": "Step 25",
        "description": "The gremolata: While the shanks are braising, stir together the garlic, parsley, and lemon zest in a small bowl."
      },
      {
        "title": "Step 26",
        "description": "Cover with plastic wrap and set aside in a cool place (or the refrigerator, if your kitchen is very warm.)."
      },
      {
        "title": "Step 27",
        "description": "The finish: When the veal is fork-tender and falling away from the bone, remove the lid and sprinkle over half of the gremolata."
      },
      {
        "title": "Step 28",
        "description": "Return the veal to the oven, uncovered, for another 15 minutes to caramelize it some."
      },
      {
        "title": "Step 29",
        "description": "Using a slotted spatula or spoon, carefully lift the shanks from the braising liquid, doing your best to keep them intact."
      },
      {
        "title": "Step 30",
        "description": "The shanks will be very tender and threatening to fall into pieces, and the marrow will be wobbly inside the bones, so this can be a bit tricky."
      },
      {
        "title": "Step 31",
        "description": "But if they do break apart, don’t worry, the flavor won’t suffer at all."
      },
      {
        "title": "Step 32",
        "description": "Arrange the shanks on a serving platter or other large plate, without stacking, and cover with foil to keep warm."
      },
      {
        "title": "Step 33",
        "description": "Finishing the sauce: Set the braising pot on top of the stove and evaluate the sauce: if there is a visible layer of fat floating on the surface, use a large spoon to skim it off and discard it."
      },
      {
        "title": "Step 34",
        "description": "Taste the sauce for concentration of flavor."
      },
      {
        "title": "Step 35",
        "description": "If it tastes a bit weak or flat, bring it to a boil over high heat, and boil to reduce the volume and intensify the flavor for 5 to 10 minutes."
      },
      {
        "title": "Step 36",
        "description": "Taste again for salt and pepper."
      },
      {
        "title": "Step 37",
        "description": "If the sauce wants more zip, stir in a teaspoon or two of the remaining gremolata."
      },
      {
        "title": "Step 38",
        "description": "Portioning the veal shanks: if the shanks are reasonably sized, serve one per person."
      },
      {
        "title": "Step 39",
        "description": "If the shanks are gargantuan or you’re dealing with modest appetites, pull apart the larger shanks, separating them at their natural seams, and serve smaller amounts."
      },
      {
        "title": "Step 40",
        "description": "Be sure to give the marrow bones to whomever prizes them most."
      },
      {
        "title": "Step 41",
        "description": "Serving: Arrange the veal shanks on warm dinner plates accompanied by the risotto, if serving."
      },
      {
        "title": "Step 42",
        "description": "Just before carrying the plates to the table, sprinkle on the remaining gremolata and then spoon over a generous amount of sauce – the contact with the hot liquid will aromatize the gremolata and perk up everyone’s appetite with the whiff of garlic and lemon."
      }
    ],
    "chefNote": "Source: https://www.cookstr.com/Meat/Osso-Buco-alla-Milanese",
    "addedAt": 1782175196398
  },
  {
    "id": "mealdb_52837",
    "title": "Pilchard puttanesca",
    "description": "Cook the pasta following pack instructions.",
    "image": "https://www.themealdb.com/images/media/meals/vvtvtr1511180578.jpg",
    "difficulty": "Medium",
    "time": "—",
    "prepTime": "—",
    "category": "Pasta",
    "tags": [
      "imported",
      "italian",
      "mealdb",
      "mediterranean",
      "pasta"
    ],
    "ingredients": [
      {
        "name": "Spaghetti",
        "amount": "300g"
      },
      {
        "name": "Olive Oil",
        "amount": "1 tbls"
      },
      {
        "name": "Onion",
        "amount": "1 finely chopped"
      },
      {
        "name": "Garlic",
        "amount": "2 cloves minced"
      },
      {
        "name": "Red Chilli",
        "amount": "1"
      },
      {
        "name": "Tomato Puree",
        "amount": "1 tbls"
      },
      {
        "name": "Pilchards",
        "amount": "425g"
      },
      {
        "name": "Black Olives",
        "amount": "70g"
      },
      {
        "name": "Parmesan",
        "amount": "Shaved"
      }
    ],
    "steps": [
      {
        "title": "Step 1",
        "description": "Cook the pasta following pack instructions."
      },
      {
        "title": "Step 2",
        "description": "Heat the oil in a non-stick frying pan and cook the onion, garlic and chilli for 3-4 mins to soften."
      },
      {
        "title": "Step 3",
        "description": "Stir in the tomato purée and cook for 1 min, then add the pilchards with their sauce."
      },
      {
        "title": "Step 4",
        "description": "Cook, breaking up the fish with a wooden spoon, then add the olives and continue to cook for a few more mins."
      },
      {
        "title": "Step 5",
        "description": "Drain the pasta and add to the pan with 2-3 tbsp of the cooking water."
      },
      {
        "title": "Step 6",
        "description": "Toss everything together well, then divide between plates and serve, scattered with Parmesan."
      }
    ],
    "chefNote": "Source: https://www.bbcgoodfood.com/recipes/pilchard-puttanesca",
    "addedAt": 1782175196704
  },
  {
    "id": "mealdb_53014",
    "title": "Pizza Express Margherita",
    "description": "1 Preheat the oven to 230°C.",
    "image": "https://www.themealdb.com/images/media/meals/x0lk931587671540.jpg",
    "difficulty": "Medium",
    "time": "—",
    "prepTime": "—",
    "category": "Miscellaneous",
    "tags": [
      "imported",
      "italian",
      "mealdb",
      "mediterranean",
      "miscellaneous"
    ],
    "ingredients": [
      {
        "name": "Water",
        "amount": "150ml"
      },
      {
        "name": "Sugar",
        "amount": "1 tsp"
      },
      {
        "name": "Yeast",
        "amount": "15g"
      },
      {
        "name": "Plain Flour",
        "amount": "225g"
      },
      {
        "name": "Salt",
        "amount": "1 1/2 tsp"
      },
      {
        "name": "Olive Oil",
        "amount": "Drizzle"
      },
      {
        "name": "Passata",
        "amount": "80g"
      },
      {
        "name": "Mozzarella",
        "amount": "70g"
      },
      {
        "name": "Oregano",
        "amount": "Peeled and Sliced"
      },
      {
        "name": "Basil",
        "amount": "Leaves"
      },
      {
        "name": "Black Pepper",
        "amount": "Pinch"
      }
    ],
    "steps": [
      {
        "title": "Step 1",
        "description": "1 Preheat the oven to 230°C."
      },
      {
        "title": "Step 2",
        "description": "2 Add the sugar and crumble the fresh yeast into warm water."
      },
      {
        "title": "Step 3",
        "description": "3 Allow the mixture to stand for 10 – 15 minutes in a warm place (we find a windowsill on a sunny day works best) until froth develops on the surface."
      },
      {
        "title": "Step 4",
        "description": "4 Sift the flour and salt into a large mixing bowl, make a well in the middle and pour in the yeast mixture and olive oil."
      },
      {
        "title": "Step 5",
        "description": "5 Lightly flour your hands, and slowly mix the ingredients together until they bind."
      },
      {
        "title": "Step 6",
        "description": "6 Generously dust your surface with flour."
      },
      {
        "title": "Step 7",
        "description": "7 Throw down the dough and begin kneading for 10 minutes until smooth, silky and soft."
      },
      {
        "title": "Step 8",
        "description": "8 Place in a lightly oiled, non-stick baking tray (we use a round one, but any shape will do!)."
      },
      {
        "title": "Step 9",
        "description": "9 Spread the passata on top making sure you go to the edge."
      },
      {
        "title": "Step 10",
        "description": "10 Evenly place the mozzarella (or other cheese) on top, season with the oregano and black pepper, then drizzle with a little olive oil."
      },
      {
        "title": "Step 11",
        "description": "11 Cook in the oven for 10 – 12 minutes until the cheese slightly colours."
      },
      {
        "title": "Step 12",
        "description": "12 When ready, place the basil leaf on top and tuck in!."
      }
    ],
    "chefNote": "Source: https://www.dailymail.co.uk/femail/food/article-8240361/Pizza-Express-release-secret-recipe-Margherita-Pizza-make-home.html",
    "addedAt": 1782175197004
  },
  {
    "id": "mealdb_52780",
    "title": "Potato Gratin with Chicken",
    "description": "15 minute potato gratin with chicken and bacon greens: a gratin always seems more effort and more indulgent than ordinary boiled or roasts, but it doesn't have to take 45mins, it's nice for a change and you can control the calorie content by going with full fat to low fat creme fraiche.",
    "image": "https://www.themealdb.com/images/media/meals/qwrtut1468418027.jpg",
    "difficulty": "Medium",
    "time": "—",
    "prepTime": "—",
    "category": "Chicken",
    "tags": [
      "chicken",
      "imported",
      "italian",
      "mealdb",
      "mediterranean"
    ],
    "ingredients": [
      {
        "name": "Potatoes",
        "amount": "800g"
      },
      {
        "name": "Onions",
        "amount": "3"
      },
      {
        "name": "Olive Oil",
        "amount": "2 tblsp"
      },
      {
        "name": "Chicken Stock",
        "amount": "100ml"
      },
      {
        "name": "Creme Fraiche",
        "amount": "1 pot"
      },
      {
        "name": "Parmesan",
        "amount": "Topping"
      },
      {
        "name": "Chicken Breasts",
        "amount": "4"
      },
      {
        "name": "Bacon",
        "amount": "4"
      },
      {
        "name": "Spinach",
        "amount": "Topping"
      },
      {
        "name": "Peas",
        "amount": "Topping"
      }
    ],
    "steps": [
      {
        "title": "Step 1",
        "description": "15 minute potato gratin with chicken and bacon greens: a gratin always seems more effort and more indulgent than ordinary boiled or roasts, but it doesn't have to take 45mins, it's nice for a change and you can control the calorie content by going with full fat to low fat creme fraiche. (It's always tastes better full fat though obviously!) to serve 4: use 800g of potatoes, finely slice and boil in a pan for about 5-8 mins till firmish, not soft."
      },
      {
        "title": "Step 2",
        "description": "Finely slice 3 onions and place in an oven dish with 2 tblsp of olive oil and 100ml of chicken stock."
      },
      {
        "title": "Step 3",
        "description": "Cook till the onions are soft then drain the potatoes and pour onto the onions."
      },
      {
        "title": "Step 4",
        "description": "Season and spoon over cream or creme fraiche till all is covered but not swimming."
      },
      {
        "title": "Step 5",
        "description": "Grate Parmesan over the top then finish under the grill till nicely golden. serve with chicken and bacon, peas and spinach."
      }
    ],
    "chefNote": "Source: https://www.instagram.com/p/BHxR7hYBJ6P",
    "addedAt": 1782175197306
  },
  {
    "id": "mealdb_52811",
    "title": "Ribollita",
    "description": "Put 2 tablespoons of the oil in a large pot over medium heat.",
    "image": "https://www.themealdb.com/images/media/meals/xrrwpx1487347049.jpg",
    "difficulty": "Medium",
    "time": "—",
    "prepTime": "—",
    "category": "Vegetarian",
    "tags": [
      "imported",
      "italian",
      "mealdb",
      "mediterranean",
      "vegetarian"
    ],
    "ingredients": [
      {
        "name": "Olive Oil",
        "amount": "5 tablespoons"
      },
      {
        "name": "Onion",
        "amount": "1 chopped"
      },
      {
        "name": "Carrots",
        "amount": "1 chopped"
      },
      {
        "name": "Celery",
        "amount": "1 stalk chopped"
      },
      {
        "name": "Garlic",
        "amount": "1 tablespoon minced"
      },
      {
        "name": "Cannellini Beans",
        "amount": "2 cups"
      },
      {
        "name": "Canned tomatoes",
        "amount": "1"
      },
      {
        "name": "Water",
        "amount": "4 cups"
      },
      {
        "name": "Rosemary",
        "amount": "1 fresh sprig"
      },
      {
        "name": "Thyme",
        "amount": "1 fresh sprig"
      },
      {
        "name": "Kale",
        "amount": "1 pound chopped"
      },
      {
        "name": "Wholegrain Bread",
        "amount": "4 thick slices"
      },
      {
        "name": "Red Onions",
        "amount": "1 thinly sliced"
      },
      {
        "name": "Parmesan",
        "amount": "½ cup freshly grated"
      }
    ],
    "steps": [
      {
        "title": "Step 1",
        "description": "Put 2 tablespoons of the oil in a large pot over medium heat."
      },
      {
        "title": "Step 2",
        "description": "When it’s hot, add onion, carrot, celery and garlic; sprinkle with salt and pepper and cook, stirring occasionally, until vegetables are soft, 5 to 10 minutes."
      },
      {
        "title": "Step 3",
        "description": "Heat the oven to 500 degrees."
      },
      {
        "title": "Step 4",
        "description": "Drain the beans; if they’re canned, rinse them as well."
      },
      {
        "title": "Step 5",
        "description": "Add them to the pot along with tomatoes and their juices and stock, rosemary and thyme."
      },
      {
        "title": "Step 6",
        "description": "Bring to a boil, then reduce heat so the soup bubbles steadily; cover and cook, stirring once or twice to break up the tomatoes, until the flavors meld, 15 to 20 minutes."
      },
      {
        "title": "Step 7",
        "description": "Fish out and discard rosemary and thyme stems, if you like, and stir in kale."
      },
      {
        "title": "Step 8",
        "description": "Taste and adjust seasoning."
      },
      {
        "title": "Step 9",
        "description": "Lay bread slices on top of the stew so they cover the top and overlap as little as possible."
      },
      {
        "title": "Step 10",
        "description": "Scatter red onion slices over the top, drizzle with the remaining 3 tablespoons oil and sprinkle with Parmesan."
      },
      {
        "title": "Step 11",
        "description": "Put the pot in the oven and bake until the bread, onions and cheese are browned and crisp, 10 to 15 minutes. (If your pot fits under the broiler, you can also brown the top there.) Divide the soup and bread among 4 bowls and serve."
      }
    ],
    "chefNote": "Source: https://cooking.nytimes.com/recipes/1016052-ribollita",
    "addedAt": 1782175197607
  },
  {
    "id": "mealdb_52783",
    "title": "Rigatoni with fennel sausage sauce",
    "description": "Heat a tablespoon of oil in a large saute pan for which you have a lid.",
    "image": "https://www.themealdb.com/images/media/meals/qtqvys1468573168.jpg",
    "difficulty": "Medium",
    "time": "—",
    "prepTime": "—",
    "category": "Lamb",
    "tags": [
      "imported",
      "italian",
      "lamb",
      "mealdb",
      "mediterranean",
      "pasta"
    ],
    "ingredients": [
      {
        "name": "olive oil",
        "amount": "2½ tbsp"
      },
      {
        "name": "Italian fennel sausages",
        "amount": "6 cut into 1.5cm-thick slices"
      },
      {
        "name": "onion",
        "amount": "1 large peeled and chopped"
      },
      {
        "name": "fennel bulb",
        "amount": "1 trimmed and roughly chopped; reserve any fronds to garnish"
      },
      {
        "name": "smoky paprika",
        "amount": "½ tsp"
      },
      {
        "name": "garlic",
        "amount": "1 clove, peeled and sliced"
      },
      {
        "name": "fennel seeds",
        "amount": "2 tsp lightly toasted and then gently crushed"
      },
      {
        "name": "red wine",
        "amount": "100ml"
      },
      {
        "name": "chopped tomatoes",
        "amount": "400g tinned"
      },
      {
        "name": "caster sugar",
        "amount": "½ tsp"
      },
      {
        "name": "pitted black olives",
        "amount": "50g cut in half lengthways"
      },
      {
        "name": "rigatoni",
        "amount": "500g"
      },
      {
        "name": "pecorino",
        "amount": "30g roughly crumbled into 0.5cm pieces"
      },
      {
        "name": "anchovy fillet",
        "amount": "1  rinsed and patted dry"
      },
      {
        "name": "garlic",
        "amount": "1 clove, peeled and crushed"
      },
      {
        "name": "olive oil",
        "amount": "60ml"
      },
      {
        "name": "basil leaves",
        "amount": "50g torn"
      }
    ],
    "steps": [
      {
        "title": "Step 1",
        "description": "Heat a tablespoon of oil in a large saute pan for which you have a lid."
      },
      {
        "title": "Step 2",
        "description": "Add the sausage pieces and fry on a medium-high heat for 10 minutes, stirring regularly, until golden-brown all over."
      },
      {
        "title": "Step 3",
        "description": "Transfer the sausages to a plate, then add the onion and fennel to the hot pan and fry for 15 minutes, stirring once in a while, until soft and caramelised; if the pan goes a bit dry, add a teaspoon or so of extra oil."
      },
      {
        "title": "Step 4",
        "description": "Stir in the paprika, garlic and half the fennel seeds, fry for two minutes more, then pour on the wine and boil for 30 seconds, to reduce by half."
      },
      {
        "title": "Step 5",
        "description": "Add the tomatoes, sugar, 100ml water, the seared sausage and half a teaspoon of salt, cover and simmer for 30 minutes; remove the lid after 10 minutes, and cook until the sauce is thick and rich."
      },
      {
        "title": "Step 6",
        "description": "Remove from the heat, stir through the olives and remaining fennel seeds and set aside until you’re ready to serve."
      },
      {
        "title": "Step 7",
        "description": "Bring a large pot of salted water to a boil, add the pasta and cook for 12-14 minutes (or according to the instructions on the packet), until al dente."
      },
      {
        "title": "Step 8",
        "description": "Meanwhile, reheat the sauce."
      },
      {
        "title": "Step 9",
        "description": "Drain the pasta, return it to the pot, stir in a tablespoon of oil, then divide between the bowls."
      },
      {
        "title": "Step 10",
        "description": "Put all the pesto ingredients except the basil in the small bowl of a food processor."
      },
      {
        "title": "Step 11",
        "description": "Add a tablespoon of water and blitz to a rough paste."
      },
      {
        "title": "Step 12",
        "description": "Add the basil, then blitz until just combined (the pesto has a much better texture if the basil is not overblended)."
      },
      {
        "title": "Step 13",
        "description": "Spoon over the ragù and top with a spoonful of pesto."
      },
      {
        "title": "Step 14",
        "description": "Finish with a sprinkling of chopped fennel fronds, if you have any, and serve at once."
      }
    ],
    "chefNote": "Source: http://www.ottolenghi.co.uk/recipes/meat/rigatoni-with-fennel-sausage-sauce-and-pecorino-and-anchovy-pesto-shop",
    "addedAt": 1782175197910
  },
  {
    "id": "mealdb_52823",
    "title": "Salmon Prawn Risotto",
    "description": "Melt the butter in a thick-based pan and gently cook the onion without colour until it is soft.",
    "image": "https://www.themealdb.com/images/media/meals/xxrxux1503070723.jpg",
    "difficulty": "Medium",
    "time": "—",
    "prepTime": "—",
    "category": "Seafood",
    "tags": [
      "fish",
      "imported",
      "italian",
      "mealdb",
      "mediterranean",
      "seafood"
    ],
    "ingredients": [
      {
        "name": "butter",
        "amount": "50g/2oz"
      },
      {
        "name": "onion",
        "amount": "1 finely chopped"
      },
      {
        "name": "rice",
        "amount": "150g"
      },
      {
        "name": "white wine",
        "amount": "125ml"
      },
      {
        "name": "vegetable stock",
        "amount": "1 litre hot"
      },
      {
        "name": "lemon",
        "amount": "The juice and zest of one"
      },
      {
        "name": "King Prawns",
        "amount": "240g large"
      },
      {
        "name": "salmon",
        "amount": "150g"
      },
      {
        "name": "asparagus",
        "amount": "100g tips blanched briefly in boiling water"
      },
      {
        "name": "black pepper",
        "amount": "ground"
      },
      {
        "name": "Parmesan",
        "amount": "50g shavings"
      }
    ],
    "steps": [
      {
        "title": "Step 1",
        "description": "Melt the butter in a thick-based pan and gently cook the onion without colour until it is soft."
      },
      {
        "title": "Step 2",
        "description": "Add the rice and stir to coat all the grains in the butter."
      },
      {
        "title": "Step 3",
        "description": "Add the wine and cook gently stirring until it is absorbed."
      },
      {
        "title": "Step 4",
        "description": "Gradually add the hot stock, stirring until each addition is absorbed."
      },
      {
        "title": "Step 5",
        "description": "Keep stirring until the rice is tender."
      },
      {
        "title": "Step 6",
        "description": "Season with the lemon juice and zest, and pepper to taste. (there will probably be sufficient saltiness from the salmon to not need to add salt) Stir gently to heat through."
      },
      {
        "title": "Step 7",
        "description": "Serve scattered with the Parmesan and seasonal vegetables."
      },
      {
        "title": "Step 8",
        "description": "Grill the salmon and gently place onto the risotto with the prawns and asparagus."
      }
    ],
    "chefNote": "Source: http://www.rangemaster.co.uk/rangemaster-owners/recipes-ideas-inspiration/recipes/mains/prawn-and-hot-smoked-salmon-risotto-with-asparagus",
    "addedAt": 1782175198238
  },
  {
    "id": "mealdb_52982",
    "title": "Spaghetti alla Carbonara",
    "description": "STEP 1 Put a large saucepan of water on to boil.",
    "image": "https://www.themealdb.com/images/media/meals/llcbn01574260722.jpg",
    "difficulty": "Medium",
    "time": "—",
    "prepTime": "—",
    "category": "Pasta",
    "tags": [
      "bbq",
      "breakfast",
      "imported",
      "italian",
      "mealdb",
      "mediterranean",
      "pasta"
    ],
    "ingredients": [
      {
        "name": "Spaghetti",
        "amount": "320g"
      },
      {
        "name": "Egg Yolks",
        "amount": "6"
      },
      {
        "name": "Salt",
        "amount": "As required"
      },
      {
        "name": "Bacon",
        "amount": "150g"
      },
      {
        "name": "Pecorino",
        "amount": "50g"
      },
      {
        "name": "Black Pepper",
        "amount": "As required"
      }
    ],
    "steps": [
      {
        "title": "Step 1",
        "description": "STEP 1."
      },
      {
        "title": "Step 2",
        "description": "Put a large saucepan of water on to boil."
      },
      {
        "title": "Step 3",
        "description": "STEP 2."
      },
      {
        "title": "Step 4",
        "description": "Finely chop the 100g pancetta, having first removed any rind."
      },
      {
        "title": "Step 5",
        "description": "Finely grate 50g pecorino cheese and 50g parmesan and mix them together."
      },
      {
        "title": "Step 6",
        "description": "STEP 3."
      },
      {
        "title": "Step 7",
        "description": "Beat the 3 large eggs in a medium bowl and season with a little freshly grated black pepper."
      },
      {
        "title": "Step 8",
        "description": "Set everything aside."
      },
      {
        "title": "Step 9",
        "description": "STEP 4."
      },
      {
        "title": "Step 10",
        "description": "Add 1 tsp salt to the boiling water, add 350g spaghetti and when the water comes back to the boil, cook at a constant simmer, covered, for 10 minutes or until al dente (just cooked)."
      },
      {
        "title": "Step 11",
        "description": "STEP 5."
      },
      {
        "title": "Step 12",
        "description": "Squash 2 peeled plump garlic cloves with the blade of a knife, just to bruise it."
      },
      {
        "title": "Step 13",
        "description": "STEP 6."
      },
      {
        "title": "Step 14",
        "description": "While the spaghetti is cooking, fry the pancetta with the garlic."
      },
      {
        "title": "Step 15",
        "description": "Drop 50g unsalted butter into a large frying pan or wok and, as soon as the butter has melted, tip in the pancetta and garlic."
      },
      {
        "title": "Step 16",
        "description": "STEP 7."
      },
      {
        "title": "Step 17",
        "description": "Leave to cook on a medium heat for about 5 minutes, stirring often, until the pancetta is golden and crisp."
      },
      {
        "title": "Step 18",
        "description": "The garlic has now imparted its flavour, so take it out with a slotted spoon and discard."
      },
      {
        "title": "Step 19",
        "description": "STEP 8."
      },
      {
        "title": "Step 20",
        "description": "Keep the heat under the pancetta on low."
      },
      {
        "title": "Step 21",
        "description": "When the pasta is ready, lift it from the water with a pasta fork or tongs and put it in the frying pan with the pancetta."
      },
      {
        "title": "Step 22",
        "description": "Don’t worry if a little water drops in the pan as well (you want this to happen) and don’t throw the pasta water away yet."
      },
      {
        "title": "Step 23",
        "description": "STEP 9."
      },
      {
        "title": "Step 24",
        "description": "Mix most of the cheese in with the eggs, keeping a small handful back for sprinkling over later."
      },
      {
        "title": "Step 25",
        "description": "STEP 10."
      },
      {
        "title": "Step 26",
        "description": "Take the pan of spaghetti and pancetta off the heat."
      },
      {
        "title": "Step 27",
        "description": "Now quickly pour in the eggs and cheese."
      },
      {
        "title": "Step 28",
        "description": "Using the tongs or a long fork, lift up the spaghetti so it mixes easily with the egg mixture, which thickens but doesn’t scramble, and everything is coated."
      },
      {
        "title": "Step 29",
        "description": "STEP 11."
      },
      {
        "title": "Step 30",
        "description": "Add extra pasta cooking water to keep it saucy (several tablespoons should do it)."
      },
      {
        "title": "Step 31",
        "description": "You don’t want it wet, just moist."
      },
      {
        "title": "Step 32",
        "description": "Season with a little salt, if needed."
      },
      {
        "title": "Step 33",
        "description": "STEP 12."
      },
      {
        "title": "Step 34",
        "description": "Use a long-pronged fork to twist the pasta on to the serving plate or bowl."
      },
      {
        "title": "Step 35",
        "description": "Serve immediately with a little sprinkling of the remaining cheese and a grating of black pepper."
      },
      {
        "title": "Step 36",
        "description": "If the dish does get a little dry before serving, splash in some more hot pasta water and the glossy sauciness will be revived."
      }
    ],
    "chefNote": "Source: https://www.bbcgoodfood.com/recipes/ultimate-spaghetti-carbonara-recipe",
    "addedAt": 1782175198580
  },
  {
    "id": "mealdb_52770",
    "title": "Spaghetti Bolognese",
    "description": "Put the onion and oil in a large pan and fry over a fairly high heat for 3-4 mins.",
    "image": "https://www.themealdb.com/images/media/meals/sutysw1468247559.jpg",
    "difficulty": "Medium",
    "time": "—",
    "prepTime": "—",
    "category": "Beef",
    "tags": [
      "beef",
      "imported",
      "italian",
      "mealdb",
      "meat",
      "mediterranean",
      "pasta"
    ],
    "ingredients": [
      {
        "name": "onions",
        "amount": "2"
      },
      {
        "name": "olive oil",
        "amount": "1tbsp"
      },
      {
        "name": "garlic",
        "amount": "1 clove"
      },
      {
        "name": "lean minced beef",
        "amount": "500g"
      },
      {
        "name": "mushrooms",
        "amount": "90g"
      },
      {
        "name": "dried oregano",
        "amount": "1tsp"
      },
      {
        "name": "tomatoes",
        "amount": "400g can"
      },
      {
        "name": "hot beef stock",
        "amount": "300ml"
      },
      {
        "name": "tomato puree",
        "amount": "1tbsp"
      },
      {
        "name": "worcestershire sauce",
        "amount": "1tbsp"
      },
      {
        "name": "spaghetti",
        "amount": "350g"
      },
      {
        "name": "parmesan",
        "amount": "Topping"
      }
    ],
    "steps": [
      {
        "title": "Step 1",
        "description": "Put the onion and oil in a large pan and fry over a fairly high heat for 3-4 mins."
      },
      {
        "title": "Step 2",
        "description": "Add the garlic and mince and fry until they both brown."
      },
      {
        "title": "Step 3",
        "description": "Add the mushrooms and herbs, and cook for another couple of mins."
      },
      {
        "title": "Step 4",
        "description": "Stir in the tomatoes, beef stock, tomato ketchup or purée, Worcestershire sauce and seasoning."
      },
      {
        "title": "Step 5",
        "description": "Bring to the boil, then reduce the heat, cover and simmer, stirring occasionally, for 30 mins."
      },
      {
        "title": "Step 6",
        "description": "Meanwhile, cook the spaghetti in a large pan of boiling, salted water, according to packet instructions."
      },
      {
        "title": "Step 7",
        "description": "Drain well, run hot water through it, put it back in the pan and add a dash of olive oil, if you like, then stir in the meat sauce."
      },
      {
        "title": "Step 8",
        "description": "Serve in hot bowls and hand round Parmesan cheese, for sprinkling on top."
      }
    ],
    "addedAt": 1782175198903
  }
] satisfies Recipe[];
