import type { Recipe } from '../types';

// Generated by scripts/fetch-recipe-api-recipes.mjs
// Source: recipeapi.io, cuisine=, search=mediterranean, generatedAt=2026-06-23T00:37:36.144Z
export const RECIPE_API_SEED_RECIPES = [
  {
    "id": "api_7835",
    "title": "Mediterranean Chickpea Bowl",
    "description": "A fresh and flavorful Mediterranean chickpea bowl featuring crisp vegetables, herbs, and feta cheese, dressed in a zesty lemon and olive oil dressing. Perfect as a nutritious and satisfying vegetarian main dish.",
    "image": "",
    "difficulty": "Easy",
    "time": "15 mins",
    "prepTime": "15 mins",
    "yields": "4 servings",
    "category": "Main",
    "tags": [
      "gluten free",
      "greek",
      "halal",
      "kosher",
      "main",
      "mediterranean",
      "nut free",
      "vegetarian"
    ],
    "ingredients": [
      {
        "name": "Olive oil",
        "amount": "3 tbsp"
      },
      {
        "name": "Salt",
        "amount": "1 pinch"
      },
      {
        "name": "Black pepper",
        "amount": "1 pinch"
      },
      {
        "name": "Tomato",
        "amount": "2 piece"
      },
      {
        "name": "Red onion",
        "amount": "0.5 piece"
      },
      {
        "name": "Garlic",
        "amount": "1 clove"
      },
      {
        "name": "Parsley",
        "amount": "10 g"
      },
      {
        "name": "Lemon juice",
        "amount": "30 ml"
      },
      {
        "name": "Cucumber",
        "amount": "1 piece"
      },
      {
        "name": "Feta cheese",
        "amount": "100 g"
      },
      {
        "name": "Chickpea",
        "amount": "400 g"
      }
    ],
    "steps": [
      {
        "title": "Step 1",
        "description": "Rinse and drain the chickpeas thoroughly and place them in a large bowl."
      },
      {
        "title": "Step 2",
        "description": "Chop the cucumber, tomato, and red onion into bite-sized pieces and add them to the bowl with the chickpeas."
      },
      {
        "title": "Step 3",
        "description": "Add the chopped parsley and crumbled feta cheese to the bowl."
      },
      {
        "title": "Step 4",
        "description": "In a small bowl, whisk together the olive oil, lemon juice, minced garlic, salt, and black pepper to make the dressing."
      },
      {
        "title": "Step 5",
        "description": "Pour the dressing over the chickpea mixture and toss everything gently to combine."
      },
      {
        "title": "Step 6",
        "description": "Serve the Mediterranean chickpea bowl chilled or at room temperature, optionally garnished with extra parsley leaves."
      }
    ],
    "addedAt": 1782175056144
  },
  {
    "id": "api_10117",
    "title": "Roasted Mediterranean Vegetable Medley",
    "description": "A simple and flavorful roasted vegetable medley inspired by Mediterranean cuisine, featuring eggplant, zucchini, bell pepper, and tomato seasoned with herbs and garlic.",
    "image": "",
    "difficulty": "Easy",
    "time": "45 mins",
    "prepTime": "15 mins",
    "bakeTime": "30 mins",
    "yields": "4 servings",
    "category": "Side Dish",
    "tags": [
      "dairy free",
      "gluten free",
      "halal",
      "kosher",
      "mediterranean",
      "nut free",
      "portuguese",
      "side dish",
      "vegan",
      "vegetarian"
    ],
    "ingredients": [
      {
        "name": "Olive oil",
        "amount": "3 tbsp"
      },
      {
        "name": "Salt",
        "amount": "1 tsp"
      },
      {
        "name": "Black pepper",
        "amount": "1 tsp"
      },
      {
        "name": "Tomato",
        "amount": "2 piece"
      },
      {
        "name": "Garlic",
        "amount": "3 clove"
      },
      {
        "name": "Dried thyme",
        "amount": "1 tsp"
      },
      {
        "name": "Parsley",
        "amount": "2 tbsp"
      },
      {
        "name": "Dried oregano",
        "amount": "1 tsp"
      },
      {
        "name": "Bell pepper",
        "amount": "1 piece"
      },
      {
        "name": "Zucchini",
        "amount": "2 piece"
      },
      {
        "name": "Eggplant",
        "amount": "1 piece"
      }
    ],
    "steps": [
      {
        "title": "Step 1",
        "description": "Preheat the oven to 200°C (390°F)."
      },
      {
        "title": "Step 2",
        "description": "Chop the eggplant, zucchini, bell pepper, and tomato into similar-sized chunks for even cooking."
      },
      {
        "title": "Step 3",
        "description": "Peel and halve the garlic cloves."
      },
      {
        "title": "Step 4",
        "description": "In a large mixing bowl, combine the chopped vegetables and garlic."
      },
      {
        "title": "Step 5",
        "description": "Drizzle the olive oil over the vegetables, then sprinkle with dried oregano, dried thyme, salt, and black pepper."
      },
      {
        "title": "Step 6",
        "description": "Toss everything together until the vegetables are evenly coated with oil and seasonings."
      },
      {
        "title": "Step 7",
        "description": "Spread the vegetables out in a single layer on a baking sheet lined with parchment paper."
      },
      {
        "title": "Step 8",
        "description": "Roast in the preheated oven for about 25-30 minutes, turning halfway through, until the vegetables are tender and lightly caramelized."
      },
      {
        "title": "Step 9",
        "description": "Remove from the oven and let cool slightly."
      },
      {
        "title": "Step 10",
        "description": "Sprinkle chopped fresh parsley over the roasted vegetables before serving."
      }
    ],
    "addedAt": 1782175056144
  }
] satisfies Recipe[];
